In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook, tqdm

In [2]:
new_main_2014 = pd.read_csv('data/ml_2014.csv', low_memory=False)
print("The data has a size of {}".format(new_main_2014.shape))

The data has a size of (824769, 32)


In [3]:
new_main_2014.head(1)

Unnamed: 0         npi specialty_description nppes_provider_state  \
0           0  1710946280       Family Practice                   IL   

   t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                    2468.12                      125              27.6   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  ...  \
0               20.0             65.0              20.0  ...   

   antipsych_cost_per_claim_ge65  antipsych_claim_per_bene_ge65  \
0                         5075.0                            0.0   

   total_30_day_fill_count  total_day_supply  total_30_day_fill_count_ge65  \
0                  10155.0            295208                        8076.8   

   total_day_supply_ge65  opioid_day_supply  opioid_prescriber_rate  \
0               235344.0            13345.0                    6.74   

   is_excluded       year  
0            0  2014-2015  

[1 rows x 32 columns]

In [4]:
new_main_2014.drop(['Unnamed: 0'], axis=1, inplace = True)

In [5]:
new_main_2014.drop(['npi', 'specialty_description','nppes_provider_state','year'], axis=1, inplace = True)

In [6]:
new_main_2014.head(1)

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                    2468.12                      125              27.6   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
0               20.0             65.0              20.0            64.0   

   t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
0            6415.0                 6057.0                 2552.0  ...   

   antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
0                      234.0                         5075.0   

   antipsych_claim_per_bene_ge65  total_30_day_fill_count  total_day_supply  \
0                            0.0                  10155.0            295208   

   total_30_day_fill_count_ge65  total_day_supply_ge65  opioid_day_supply  \
0                        8076.8               235344.0            13345.0   

   opioid_prescriber_rate  is_excluded  
0                    6.74            0  

[1 rows x 27 columns]

In [7]:
len(new_main_2014[new_main_2014['is_excluded'] == 1])

152

In [8]:
dropIndex = new_main_2014[new_main_2014['is_excluded'] == 1].index

In [9]:
len(new_main_2014[new_main_2014['is_excluded'] == 0])

824617

In [10]:
only_excluded = new_main_2014[new_main_2014['is_excluded'] == 1]
new_main_2014.drop(dropIndex, inplace = True)
new_main_2014 = new_main_2014.sample(frac=1)
random_sample = new_main_2014.iloc[0:164802]
new_df = pd.concat([only_excluded, random_sample])
new_main_2014 = new_main_2014.drop(new_main_2014.iloc[0:164802].index, axis = 0)
new_df = new_df.sample(frac=1)
#part_d_df.iloc[0:85000].index

In [11]:
#new_df.drop(['Unnamed: 0'], axis=1, inplace = True)
new_df.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
321659                    2119.12                      118              22.7   
567436                    3052.79                        8               2.0   
742942                    3707.75                      202              31.3   
449003                     125.74                        1               1.2   
298961                    8460.63                       14               4.7   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
321659               20.0             67.0              20.0            67.0   
567436                0.0              0.0               0.0             0.0   
742942               20.0             73.0              20.0            72.0   
449003                0.0              0.0               0.0             0.0   
298961               60.0             92.0              60.0            92.0   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
321659            6456.0                 6800.0                 2339.0  ...   
567436           14731.0                    0.0                    0.0  ...   
742942            5948.0                 5784.0                 3001.0  ...   
449003            1636.0                 1428.0                  123.0  ...   
298961            8987.0                 9177.0                  430.0  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
321659                      211.0                            0.0   
567436                      137.0                            0.0   
742942                      263.0                        12940.0   
449003                      100.0                            0.0   
298961                        0.0                            0.0   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
321659                            0.0                   7595.4   
567436                            0.0                    277.9   
742942                            0.0                  22684.8   
449003                            0.0                     62.0   
298961                            0.0                   2555.4   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
321659            217811                        4664.6               135462.0   
567436              6444                           0.0                    0.0   
742942            646441                       16411.6               470463.0   
449003               530                          37.0                  298.0   
298961             65730                        2090.8                54115.0   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
321659            12431.0                    7.76            0  
567436                0.0                    0.00            0  
742942            13572.0                    3.92            0  
449003              137.0                   40.32            0  
298961                0.0                    0.00            0  

[5 rows x 27 columns]

In [12]:
new_main_2014.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count               6.598150e+05            659815.000000     659815.000000   
mean                2.402264e+03                27.610836          6.890625   
std                 7.567974e+03                43.991670          7.633431   
min                 0.000000e+00                 0.000000          0.000000   
25%                 2.043050e+02                 2.000000          2.000000   
50%                 9.080800e+02                 8.000000          3.800000   
75%                 2.588965e+03                31.000000          9.000000   
max                 1.713763e+06               455.000000        281.200000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      659815.000000    659815.000000     659815.000000   659815.000000   
mean           14.497155        37.858997         13.998515       37.730244   
std            19.143759        36.929100         17.604538       36.588462   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        41.000000         10.000000       42.000000   
75%            20.000000        72.000000         20.000000       71.000000   
max           100.000000       100.000000        100.000000      100.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count      6.598150e+05           6.598150e+05          659815.000000  ...   
mean       1.004104e+04           8.193826e+03             521.828393  ...   
std        3.333227e+04           2.562018e+04             747.576661  ...   
min        0.000000e+00           0.000000e+00               0.000000  ...   
25%        2.815000e+03           1.711000e+03               0.000000  ...   
50%        5.460000e+03           4.758000e+03             233.000000  ...   
75%        8.802000e+03           7.662000e+03             707.000000  ...   
max        4.438712e+06           2.983256e+06           20177.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              659815.000000                  659815.000000   
mean                   93.930906                    2045.094730   
std                    85.258545                    8053.817582   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                   113.000000                       0.000000   
75%                   147.000000                       0.000000   
max                  1683.000000                  317762.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  659815.000000            659815.000000   
mean                       28.881389              2389.650059   
std                       146.768116              4846.472289   
min                         0.000000                11.000000   
25%                         0.000000               133.000000   
50%                         0.000000               424.000000   
75%                         0.000000              2166.800000   
max                      6685.000000            196744.400000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      6.598150e+05                 659815.000000           6.598150e+05   
mean       6.618931e+04                   1903.759183           5.306331e+04   
std        1.358101e+05                   4163.648316           1.170170e+05   
min        1.100000e+01                      0.000000           0.000000e+00   
25%        2.073000e+03                     66.000000           8.930000e+02   
50%        9.835000e+03                    270.300000           6.138000e+03   
75%        5.994650e+04                   1495.350000           4.116200e+04   
max        4.430842e+06                 171557.400

In [13]:
import math

In [14]:
from sklearn import decomposition
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, auc
from sklearn.utils import resample
from sklearn.preprocessing import label_binarize
from sklearn.svm import SVC
from scipy.stats import pointbiserialr

In [15]:
#part_d_excluded = new_df[new_df["is_excluded"]==1]

fudge = resample(only_excluded, replace=True, n_samples=1000000, random_state = 0)
#fudge.drop(['Unnamed: 0'], axis=1, inplace = True)
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count             1000000.000000           1000000.000000    1000000.000000   
mean                 3150.722557                38.776671         10.993695   
std                  5463.758747                55.252335         10.339939   
min                    59.070000                 1.000000          0.000000   
25%                   346.880000                 3.000000          2.500000   
50%                  1512.350000                14.000000          8.400000   
75%                  3321.330000                60.000000         17.700000   
max                 43171.580000               316.000000         46.700000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count     1000000.000000   1000000.000000    1000000.000000  1000000.000000   
mean           13.645670        38.821432         13.253340       38.601731   
std            16.738395        37.113234         15.436989       36.585586   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        46.000000         10.000000       49.000000   
75%            20.000000        74.000000         20.000000       73.000000   
max           100.000000       100.000000         70.000000       99.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count    1000000.000000         1000000.000000         1000000.000000  ...   
mean       10453.972544            8612.802950             798.699745  ...   
std        17409.055306           18372.884388            1009.535097  ...   
min          513.000000               0.000000               0.000000  ...   
25%         3953.000000            3236.000000               0.000000  ...   
50%         6324.000000            5431.000000             278.000000  ...   
75%        11347.000000            8461.000000            1365.000000  ...   
max       127759.000000          141958.000000            4555.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count             1000000.000000                 1000000.000000   
mean                   80.345682                    4707.449884   
std                    91.006088                   13909.056013   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   144.000000                       0.000000   
max                   360.000000                   75695.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                 1000000.000000           1000000.000000   
mean                       50.197072              3246.905538   
std                       182.572157              6900.937992   
min                         0.000000                11.000000   
25%                         0.000000               114.000000   
50%                         0.000000               730.500000   
75%                         0.000000              3647.900000   
max                      1144.000000             50893.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      1.000000e+06                1000000.000000           1.000000e+06   
mean       9.037432e+04                   2152.621185           5.998181e+04   
std        1.879131e+05                   5223.634249           1.415779e+05   
min        1.340000e+02                      0.000000           0.000000e+00   
25%        2.726000e+03                     40.000000           5.740000e+02   
50%        1.914400e+04                    306.500000           8.248000e+03   
75%        1.029520e+05                   1616.400000           4.759000e+04   
max        1.475342e+06                  36180.100

In [16]:
std = fudge.describe().loc["std"]
std = std[0:26]

In [17]:
rtstd = std.map(lambda x : math.sqrt(x)/2) #use half of square root of standard deviation as the range for gaussian normal
rtstd = rtstd.to_dict()

In [18]:
for key in rtstd:
    #fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, rtstd[key])))
    fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, 2)))
fudge = fudge[fudge>=0]
fudge.dropna(inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [19]:
rtstd

{'t_cost_per_claim_excluded': 36.95862127853042,
 't_claim_count_schedule2': 3.716595715991059,
 't_claim_per_bene': 1.6077887981447745,
 '%b2bg_claim_count': 2.0456291878722968,
 '%b2bg_drug_cost': 3.0460315814744163,
 '%b2t_claim_count': 1.9644966660377785,
 '%b2t_drug_cost': 3.024301013019353,
 't_cost_per_claim': 65.97168958288619,
 't_cost_per_claim_ge65': 67.7733066709067,
 't_claim_per_bene_ge65': 15.88659102416956,
 'mapd_cost_per_claim': 77.03180529674783,
 'pdp_cost_per_claim': 63.09677127775354,
 'lis_cost_per_claim': 70.00299236163667,
 'nonlis_cost_per_claim': 69.05639128174583,
 'opioid_cost_per_claim': 41.107161118370975,
 'opioid_claim_per_bene': 9.33143185654378,
 'antibiotic_cost_per_claim': 17.61630692029542,
 'antibiotic_claim_per_bene': 4.769855541400064,
 'antipsych_cost_per_claim_ge65': 58.96833051015352,
 'antipsych_claim_per_bene_ge65': 6.755963239477275,
 'total_30_day_fill_count': 41.535942242610446,
 'total_day_supply': 216.74470852217993,
 'total_30_day_fil

In [20]:
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              123616.000000            123616.000000     123616.000000   
mean                 4708.639399               120.558560         20.492198   
std                  5396.165961                84.224962         10.957845   
min                    65.485191                 0.002928          0.009644   
25%                  1690.468104                62.596692         12.008492   
50%                  3082.393091                94.808331         19.375238   
75%                  7389.782619               146.885006         25.088894   
max                 43177.055334               324.656886         53.323206   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      123616.000000    123616.000000     123616.000000   123616.000000   
mean           25.360720        70.622473         23.081155       69.798584   
std            17.920664        16.731747         10.171619       14.970601   
min             0.001028         0.001012          0.003819        0.000357   
25%            18.548167        62.878732         18.519865       62.756503   
50%            20.526521        71.830507         20.452921       71.163462   
75%            23.743202        81.019796         23.319768       80.623411   
max           107.463765       106.475449         70.403493      104.650844   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     123616.000000          123616.000000          123616.000000  ...   
mean       10457.910885            9797.724909            1984.668959  ...   
std        15491.164596           16948.236755            1113.982048  ...   
min          507.637919               0.057512               0.000411  ...   
25%         5722.636303            4684.895099            1165.635373  ...   
50%         6742.476357            6364.500303            1863.307296  ...   
75%         8987.421323            9285.395562            2550.588200  ...   
max       127764.576050          141963.511175            4562.870367  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              123616.000000                  123616.000000   
mean                  170.199402                    9453.179023   
std                    77.882288                   17106.926781   
min                     0.000266                       0.000028   
25%                   132.817352                       3.339718   
50%                   162.136466                    4646.729389   
75%                   205.803990                    9796.579547   
max                   368.012588                   75702.722567   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  123616.000000            123616.000000   
mean                      279.468632             12233.991362   
std                       369.465875             14211.082643   
min                         0.000020                51.522800   
25%                         1.217301              4026.446276   
50%                         3.371413              5936.770485   
75%                       510.941725             14131.664367   
max                      1151.220955             50899.555145   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      1.236160e+05                 123616.000000           1.236160e+05   
mean       3.338060e+05                   9047.964265           2.466285e+05   
std        3.774809e+05                  10987.640700           2.902608e+05   
min        4.662412e+02                      0.219585           2.970895e-01   
25%        1.029519e+05                   2279.396515           6.650073e+04   
50%        1.614055e+05                   3627.444213           1.051995e+05   
75%        4.094866e+05                  11411.549944           3.295275e+05   
max        1.475349e+06                  36188.107

In [21]:
only_excluded.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count                 152.000000               152.000000        152.000000   
mean                 3153.463947                38.796053         10.994079   
std                  5488.541157                55.332869         10.364977   
min                    59.070000                 1.000000          0.000000   
25%                   392.975000                 3.000000          2.500000   
50%                  1535.305000                14.500000          8.750000   
75%                  3262.275000                60.250000         17.550000   
max                 43171.580000               316.000000         46.700000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count         152.000000       152.000000        152.000000      152.000000   
mean           13.684211        38.914474         13.289474       38.690789   
std            16.823360        37.255329         15.516550       36.723097   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        47.500000         10.000000       49.000000   
75%            20.000000        74.000000         20.000000       73.000000   
max           100.000000       100.000000         70.000000       99.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count        152.000000             152.000000             152.000000  ...   
mean       10459.098684            8620.434211             799.848684  ...   
std        17470.684992           18447.315456            1012.789079  ...   
min          513.000000               0.000000               0.000000  ...   
25%         3988.250000            3173.000000               0.000000  ...   
50%         6343.500000            5471.500000             292.000000  ...   
75%        11387.000000            8467.750000            1368.000000  ...   
max       127759.000000          141958.000000            4555.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count                 152.000000                     152.000000   
mean                   80.355263                    4697.427632   
std                    91.269081                   13938.727514   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   144.000000                       0.000000   
max                   360.000000                   75695.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                     152.000000               152.000000   
mean                       50.151316              3243.644737   
std                       182.923635              6897.706409   
min                         0.000000                11.000000   
25%                         0.000000               116.325000   
50%                         0.000000               732.100000   
75%                         0.000000              3732.500000   
max                      1144.000000             50893.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      1.520000e+02                    152.000000           1.520000e+02   
mean       9.031497e+04                   2149.421053           5.991819e+04   
std        1.879340e+05                   5221.425961           1.416086e+05   
min        1.340000e+02                      0.000000           0.000000e+00   
25%        2.774000e+03                     41.725000           6.482500e+02   
50%        1.935050e+04                    315.650000           8.387500e+03   
75%        1.041380e+05                   1674.550000           4.915400e+04   
max        1.475342e+06                  36180.100

In [22]:
fudge.shape

(123616, 27)

In [23]:
fudge=fudge.sample(n=10000)
fudge.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
668474                5696.851270               139.976772         17.823615   
757358                2974.814524                73.394591         17.480726   
165926                1303.329917                87.284602         15.875228   
696149                1592.712097                94.412452          9.549383   
129452                4134.478916               108.442452         15.894405   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
668474          29.971733        89.111164         27.940467       89.628629   
757358          19.252822        86.060762         21.625968       85.410027   
165926          20.024624        60.345586         20.965132       63.435651   
696149          20.031883        78.986163         18.049502       80.592835   
129452          30.787926        67.818454         31.277672       73.174755   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
668474      18827.737342            9479.241738            1746.566070  ...   
757358      11505.920655            9587.111925            1868.295000  ...   
165926       5217.321642            4236.217725            1483.355628  ...   
696149       5795.908779            5412.180228            1058.719815  ...   
129452       7272.303768            7087.627012            1768.170222  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
668474                 231.223404                    3703.826402   
757358                 148.441737                   11112.790782   
165926                 132.653770                    1798.139787   
696149                 121.131786                    3416.252988   
129452                 166.115529                       1.830123   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
668474                       2.909762              9385.636180   
757358                       2.621925              6439.745662   
165926                       0.835967              5187.421336   
696149                       0.868168              5373.941838   
129452                       1.567277              8426.255195   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
668474     266591.049815                   6924.535518          198014.863680   
757358     190586.786093                   3827.132117          113188.084592   
165926     148352.822788                   3928.456463          113074.257100   
696149     154981.004090                   2932.794384           84925.632618   
129452     241226.287488                   5924.215453          170197.626157   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
668474        5941.818070                2.026520            1  
757358       13739.785153               13.495057            1  
165926        5854.957936                4.553120            1  
696149        8180.489758                7.916064            1  
129452        8452.620591                2.969009            1  

[5 rows x 27 columns]

In [24]:
ag_2014 = pd.concat([new_main_2014, fudge])
ag_2014.dropna(inplace=True)

In [25]:
ag_2014[ag_2014["is_excluded"]==1].shape

(10000, 27)

In [26]:
ag_2014.shape

(669815, 27)

#Applying PCA, 2 components and 3 components for variance visualization

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_), color='r')

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_cross_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

plt.vlines(1, color='grey', ymax=0.1, ymin=0, linestyle=':')
plt.vlines(2, color='grey', ymax=0.1, ymin=0, linestyle=':')

plt.annotate('1 components', xy=(0.6, 0.05), xytext=(0.9, 0.05), fontsize=15, rotation=90)
plt.annotate('2 components', xy=(1.6, 0.05), xytext=(1.9, 0.05), fontsize=15, rotation=90)

plt.savefig('VarExp.jpeg', dpi=1000)
plt.tight_layout()
plt.show()

In [27]:
#Training without Upsampling or Downsampling
#fudged data (ag_2014) only for train, regular data (new_df) only for test

X_train = ag_2014.drop(['is_excluded'], axis=1)
y_train = ag_2014['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X = new_main_2014.drop(['is_excluded'], axis=1)
#y = new_main_2014['is_excluded']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [29]:
print(pca.explained_variance_ratio_)

[8.05846276e-01 1.31919738e-01 2.39058880e-02 9.99466787e-03
 7.59151425e-03 7.21617189e-03 4.71538661e-03 2.56196630e-03
 2.15820313e-03 1.47767358e-03 1.34258363e-03 9.40235158e-04
 3.11855841e-04 1.09964509e-05 5.82666283e-06 4.27667431e-07
 3.14860826e-07 1.36659990e-07 6.64037863e-08 5.49787526e-08
 8.28588024e-09 4.17442882e-09 3.23463393e-09 2.99813822e-10
 2.37802605e-10]


In [30]:
Labels = ag_2014.drop(["is_excluded"],axis = 1).columns

In [31]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 't_cost_per_claim',
 't_cost_per_claim_ge65',
 'lis_cost_per_claim',
 'mapd_cost_per_claim',
 'total_day_supply_ge65',
 'nonlis_cost_per_claim',
 't_cost_per_claim',
 't_cost_per_claim_excluded',
 'antipsych_cost_per_claim_ge65',
 'antibiotic_cost_per_claim',
 'opioid_day_supply',
 'opioid_cost_per_claim',
 'total_30_day_fill_count',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 '%b2bg_drug_cost',
 'total_30_day_fill_count_ge65',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2bg_drug_cost']

In [32]:
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [33]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

152


In [34]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [35]:
clf.feature_importances_

array([0.06958229, 0.05248172, 0.02528291, 0.03067203, 0.0690438 ,
       0.02346707, 0.02992143, 0.03606364, 0.05525843, 0.03079472,
       0.03627594, 0.05764387, 0.04878965, 0.04980935, 0.08755016,
       0.03426022, 0.04782816, 0.0303114 , 0.02265331, 0.02848129,
       0.01013285, 0.02802846, 0.0315929 , 0.01512124, 0.04895317])

coef_df = pd.DataFrame(clf.feature_importances_, Labels, columns = ["Importances"])
coef_df.sort_values("Importances", ascending = False)

check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [36]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(y_pred_prob)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

[[1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]
 ...
 [0.   1.  ]
 [0.   1.  ]
 [0.04 0.96]]
1.0


array([[659815,      0],
       [     2,   9998]], dtype=int64)

In [37]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(y_pred_prob)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.6066339415911534


array([[164802,      0],
       [   152,      0]], dtype=int64)

In [38]:
#Upsampling only

ag_2014_majority = ag_2014[ag_2014['is_excluded'] == 0]
ag_2014_minority = ag_2014[ag_2014['is_excluded'] > 0]

# Increase by 10 times
ag_2014_minority_upsampled = resample(ag_2014_minority, replace=True, n_samples=100000, random_state=42) 
ag_2014_upsampled = pd.concat([ag_2014_majority, ag_2014_minority_upsampled])  
ag_2014_upsampled['is_excluded'].value_counts()

0    659815
1    100000
Name: is_excluded, dtype: int64

In [39]:
#fudged data (ag_2014) only for train, regular data (new_df) only for test
X_train = ag_2014_upsampled.drop(['is_excluded'], axis=1)
y_train = ag_2014_upsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [40]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [41]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [42]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[659815,      0],
       [     0, 100000]], dtype=int64)

In [43]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5282423637232303


array([[164802,      0],
       [   152,      0]], dtype=int64)

In [44]:
#Training on downsampled only and testing on regular

ag_2014_majority = ag_2014[ag_2014['is_excluded'] == 0]
ag_2014_minority = ag_2014[ag_2014['is_excluded'] > 0]

# Reduce by 10 times
ag_2014_majority_downsampled = resample(ag_2014_majority, replace=True, n_samples=81980, random_state=42) 
ag_2014_downsampled = pd.concat([ag_2014_majority_downsampled, ag_2014_minority]) 
ag_2014_downsampled['is_excluded'].value_counts()

0    81980
1    10000
Name: is_excluded, dtype: int64

In [45]:
#fudged data (ag_2014) only for train, regular data (new_df) only for test
X_train = ag_2014_downsampled.drop(['is_excluded'], axis=1)
y_train = ag_2014_downsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [46]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [47]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [48]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[81980,     0],
       [    3,  9997]], dtype=int64)

In [49]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.6078240858727443


array([[164802,      0],
       [   152,      0]], dtype=int64)

In [50]:
#Upsampling/downsampling on training and testing on regular

ag_2014_majority = ag_2014[ag_2014['is_excluded'] == 0]
ag_2014_minority = ag_2014[ag_2014['is_excluded'] > 0]

ag_2014_updownsampled = pd.concat([ag_2014_majority_downsampled, ag_2014_minority_upsampled]) 
ag_2014_updownsampled['is_excluded'].value_counts()

1    100000
0     81980
Name: is_excluded, dtype: int64

In [51]:
#fudged data (ag_2014) only for train, regular data (new_df) only for test

X_train = ag_2014_updownsampled.drop(['is_excluded'], axis=1)
y_train = ag_2014_updownsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [52]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [53]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [54]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

0.9999999999999999


array([[ 81980,      0],
       [     0, 100000]], dtype=int64)

In [55]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.45556813311540034


array([[164801,      1],
       [   152,      0]], dtype=int64)

In conclusion, results from downsampling is the best.

In [56]:
#Classification Model Comparisons

def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn

from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import cross_validate, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, auc, recall_score, precision_score, accuracy_score, f1_score

seed = 42

#Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

scoring = {'AUC': 'roc_auc', 'Accuracy': 'accuracy', 'F1': 'f1'}

names = ["Naive Bayes", "Nearest Neighbors", "RBF SVM", 
         "AdaBoost", "GradientBoost", "ExtraTrees", "Random Forest"]

classifiers = [
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            SVC(kernel="rbf", C=1, probability=True),
            AdaBoostClassifier(n_estimators=25, random_state=seed),
            GradientBoostingClassifier(n_estimators=1000, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),]

trace_dict = {'x_vals':[], 'y_vals':[], 'y_error':[], 'colors':[], 'names':[]}
                                                                                         
#iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    cv_results = cross_validate(clf, X, y, scoring=scoring, cv=5, return_train_score=True)
    print('########################### \nFor {}'.format(name))
    for score in scoring:
        print('{0:s}: Mean-{1:.4f}  STD-{2:.4f}'.format(score, cv_results['test_'+score].mean(),\
                                                        cv_results['test_'+score].std()))
    
    trace_dict['x_vals'].append(counter)
    counter += 1
    trace_dict['y_vals'].append(cv_results['test_F1'].mean())
    trace_dict['y_error'].append()
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)
    trace_dict['y_error'].append(np.std(cv_results['test_F1']))

In [57]:
# Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

names = ["GradientBoost", "ExtraTrees", "Random Forest", "Naive Bayes", "Nearest Neighbors", "AdaBoost"]

classifiers = [
            GradientBoostingClassifier(n_estimators=50, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),      
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            AdaBoostClassifier(n_estimators=25, random_state=seed)]

In [58]:
trace_dict = {'x_vals':[], 'y_vals':[], 'colors':[], 'names':[]}
                                                                                         
# iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    X_train = ag_2014.drop(['is_excluded'], axis=1)
    y_train = ag_2014['is_excluded']
    X_test = new_df.drop(['is_excluded'], axis =1)
    y_test = new_df["is_excluded"]
    clf.fit(X_train, y_train)
    y_pred_prob = clf.predict_proba(X_test)
    cv_results = roc_auc_score(y_test, y_pred_prob[:,1])
    print('########################### \nFor {}'.format(name))
              
    trace_dict['x_vals'].append(counter)
    counter += 1
    print(cv_results)
    trace_dict['y_vals'].append(cv_results.mean())
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)

########################### 
For GradientBoost
0.5759742432545851
########################### 
For ExtraTrees
0.758388315579972
########################### 
For Random Forest
0.64086714663657
########################### 
For Naive Bayes
0.5728354887108549
########################### 
For Nearest Neighbors
0.8418498330372842
########################### 
For AdaBoost
0.47708097005082334



In [59]:
# Plotting ROC curves of the models
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
import plotly

n_classes = 1
fpr = dict()
tpr = dict()
roc_auc = dict()
plt.figure()
lw = 2
trace_dict = {}

for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    y_score = clf.fit(X_train, y_train).predict_proba(X_test)
    fpr[name], tpr[name], _ = roc_curve(y_test[:], y_score[:, 1])
    roc_auc[name] = auc(fpr[name], tpr[name])
    trace_dict.update({'trace' + name: go.Scatter(x=fpr[name], y=tpr[name], mode='lines', 
                                       line=dict(color=color, width=lw),
                                       showlegend=True,
                                       name='{0:s} AUC: {1:.2f}'.format(name, roc_auc[name]))})
trace_guess = go.Scatter(x=[0, 1], y=[0, 1], 
                mode='lines', 
                line=dict(color='navy', width=lw, dash='dash'),
                showlegend=False)
data = [trace_dict[trace] for trace in trace_dict] + [trace_guess]
layout = go.Layout(title='Receiver Operating Characteristics',
                   xaxis=dict(title='False Positive Rate'),
                   yaxis=dict(title='True Positive Rate'),
                   margin=go.Margin(l=50, r=50, b=30, t=65, pad=4),
                   legend=dict(x=0.7, y=0.4, font=dict(size=18))
                  )
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='ROCs')

<Figure size 432x288 with 0 Axes>