In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook, tqdm

In [2]:
new_main_2013 = pd.read_csv('data/ml_2013.csv', low_memory=False)
print("The data has a size of {}".format(new_main_2013.shape))

The data has a size of (795269, 32)


In [3]:
new_main_2013.head(1)

Unnamed: 0         npi specialty_description nppes_provider_state  \
0           0  1043564164    Nurse Practitioner                   NC   

   t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     163.38                       12              14.2   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  ...  \
0                0.0              0.0               0.0  ...   

   antipsych_cost_per_claim_ge65  antipsych_claim_per_bene_ge65  \
0                            0.0                            0.0   

   total_30_day_fill_count  total_day_supply  total_30_day_fill_count_ge65  \
0                    435.3             11982                         324.5   

   total_day_supply_ge65  opioid_day_supply  opioid_prescriber_rate  \
0                 8902.0              286.0                    4.14   

   is_excluded       year  
0            0  2013-2014  

[1 rows x 32 columns]

In [4]:
new_main_2013.drop(['Unnamed: 0'], axis=1, inplace = True)

In [5]:
new_main_2013.drop(['npi', 'specialty_description','nppes_provider_state','year'], axis=1, inplace = True)

In [6]:
new_main_2013.head(1)

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     163.38                       12              14.2   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
0                0.0              0.0               0.0             0.0   

   t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
0            5523.0                 5594.0                    0.0  ...   

   antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
0                        0.0                            0.0   

   antipsych_claim_per_bene_ge65  total_30_day_fill_count  total_day_supply  \
0                            0.0                    435.3             11982   

   total_30_day_fill_count_ge65  total_day_supply_ge65  opioid_day_supply  \
0                         324.5                 8902.0              286.0   

   opioid_prescriber_rate  is_excluded  
0                    4.14            0  

[1 rows x 27 columns]

In [7]:
len(new_main_2013[new_main_2013['is_excluded'] == 1])

149

In [8]:
dropIndex = new_main_2013[new_main_2013['is_excluded'] == 1].index

In [9]:
len(new_main_2013[new_main_2013['is_excluded'] == 0])

795120

In [10]:
only_excluded = new_main_2013[new_main_2013['is_excluded'] == 1]
new_main_2013.drop(dropIndex, inplace = True)
new_main_2013 = new_main_2013.sample(frac=1)
random_sample = new_main_2013.iloc[0:158905]
new_df = pd.concat([only_excluded, random_sample])
new_main_2013 = new_main_2013.drop(new_main_2013.iloc[0:158905].index, axis = 0)
new_df = new_df.sample(frac=1)
#part_d_df.iloc[0:85000].index

In [11]:
#new_df.drop(['Unnamed: 0'], axis=1, inplace = True)
new_df.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
419054                      92.64                        2               1.8   
467987                      71.76                        1               1.6   
76646                      128.88                        2               3.7   
73186                      242.46                        7               4.4   
401423                      82.08                        1               2.4   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
419054                0.0              0.0               0.0             0.0   
467987                0.0              0.0               0.0             0.0   
76646                 0.0              0.0               0.0             0.0   
73186                 0.0              0.0               0.0             0.0   
401423                0.0              0.0               0.0             0.0   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
419054            2827.0                 2643.0                  177.0  ...   
467987            1314.0                 1317.0                  130.0  ...   
76646            21012.0                18169.0                  271.0  ...   
73186            17738.0                24815.0                  376.0  ...   
401423            1032.0                 1152.0                    0.0  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
419054                      113.0                            0.0   
467987                      108.0                            0.0   
76646                         0.0                            0.0   
73186                       219.0                            0.0   
401423                      154.0                            0.0   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
419054                            0.0                    168.0   
467987                            0.0                    119.0   
76646                             0.0                    249.8   
73186                             0.0                    334.2   
401423                            0.0                     51.0   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
419054              2247                         138.0                 1791.0   
467987               818                          35.0                  219.0   
76646               6064                          48.8                 1344.0   
73186               9178                         191.2                 5174.0   
401423               370                          38.0                  312.0   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
419054                0.0                    0.00            0  
467987              107.0                   31.93            0  
76646               201.0                    8.98            0  
73186               669.0                    8.30            0  
401423               67.0                   33.33            0  

[5 rows x 27 columns]

In [12]:
new_main_2013.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              636215.000000            636215.000000     636215.000000   
mean                 1836.282726                27.917775          7.117135   
std                  2985.902516                44.562494          7.804312   
min                     0.000000                 0.000000          0.000000   
25%                   205.890000                 2.000000          2.100000   
50%                   871.900000                 8.000000          4.000000   
75%                  2340.370000                32.000000          9.400000   
max                303224.730000               443.000000        163.300000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      636215.000000    636215.000000     636215.000000   636215.000000   
mean           15.292550        37.685982         14.650205       37.510893   
std            20.244528        36.977417         18.339022       36.561451   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        41.000000         10.000000       42.000000   
75%            20.000000        72.000000         20.000000       71.000000   
max           100.000000       100.000000        100.000000      100.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count      6.362150e+05           6.362150e+05          636215.000000  ...   
mean       8.465823e+03           6.952572e+03             539.581536  ...   
std        2.300236e+04           1.612463e+04             770.646011  ...   
min        1.330000e+02           0.000000e+00               0.000000  ...   
25%        2.861000e+03           1.774000e+03               0.000000  ...   
50%        5.270000e+03           4.618000e+03             237.000000  ...   
75%        8.329000e+03           7.287000e+03             735.000000  ...   
max        4.176549e+06           4.653559e+06           18124.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              636215.000000                  636215.000000   
mean                   94.321119                    1992.996449   
std                    86.080733                    7297.196846   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                   113.000000                       0.000000   
75%                   148.000000                       0.000000   
max                  1493.000000                  221112.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  636215.000000            636215.000000   
mean                       29.333678              2341.584946   
std                       147.508595              4713.483537   
min                         0.000000                11.000000   
25%                         0.000000               132.000000   
50%                         0.000000               421.000000   
75%                         0.000000              2146.800000   
max                      4105.000000            195795.400000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      6.362150e+05                 636215.000000           6.362150e+05   
mean       6.474972e+04                   1859.885899           5.175653e+04   
std        1.318290e+05                   4040.756731           1.133393e+05   
min        1.100000e+01                      0.000000           0.000000e+00   
25%        2.099500e+03                     65.000000           8.920000e+02   
50%        9.835000e+03                    265.800000           6.094000e+03   
75%        5.926650e+04                   1473.700000           4.044750e+04   
max        4.339426e+06                 172463.400

In [13]:
import math

In [14]:
from sklearn import decomposition
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, auc
from sklearn.utils import resample
from sklearn.preprocessing import label_binarize
from sklearn.svm import SVC
from scipy.stats import pointbiserialr

In [15]:
#part_d_excluded = new_df[new_df["is_excluded"]==1]

fudge = resample(only_excluded, replace=True, n_samples=1000000, random_state = 0)
#fudge.drop(['Unnamed: 0'], axis=1, inplace = True)
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count             1000000.000000           1000000.000000    1000000.000000   
mean                 2173.779019                38.549723         10.594993   
std                  3039.341050                54.631701         10.996814   
min                    44.000000                 1.000000          0.000000   
25%                   392.510000                 3.000000          3.300000   
50%                  1249.020000                15.000000          6.700000   
75%                  2442.450000                54.000000         13.000000   
max                 21781.130000               294.000000         55.700000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count     1000000.000000   1000000.000000    1000000.000000  1000000.000000   
mean           17.202480        43.846418         16.393030       43.107044   
std            18.800145        36.448761         16.225792       35.621032   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            20.000000        62.000000         20.000000       62.000000   
75%            30.000000        74.000000         30.000000       73.000000   
max           100.000000       100.000000         80.000000       99.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     1000000.00000         1000000.000000         1000000.000000  ...   
mean         7477.14970            5706.396810             847.008251  ...   
std          7225.77665            5968.023372            1073.144021  ...   
min           460.00000               0.000000               0.000000  ...   
25%          4398.00000            2306.000000               0.000000  ...   
50%          5940.00000            5152.000000             498.000000  ...   
75%          7998.00000            6861.000000            1211.000000  ...   
max         55647.00000           54687.000000            5703.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count             1000000.000000                 1000000.000000   
mean                   98.130000                    3866.755627   
std                    99.435978                    9154.513922   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                   112.000000                       0.000000   
75%                   172.000000                       0.000000   
max                   428.000000                   46820.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                 1000000.000000           1000000.000000   
mean                       61.885326              2653.045659   
std                       192.002207              4861.701784   
min                         0.000000                23.000000   
25%                         0.000000               161.600000   
50%                         0.000000               802.000000   
75%                         0.000000              2883.700000   
max                       907.000000             31945.900000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count    1000000.000000                1000000.000000         1000000.000000   
mean       72322.989048                   1722.344637           47133.638141   
std       130522.776365                   3826.535082          103505.629528   
min          202.000000                      0.000000               0.000000   
25%         3756.000000                     51.000000            1063.000000   
50%        21761.000000                    348.300000            9810.000000   
75%        81124.000000                   1530.000000           42967.000000   
max       838598.000000                  28669.200

In [16]:
std = fudge.describe().loc["std"]
std = std[0:26]

In [17]:
rtstd = std.map(lambda x : math.sqrt(x)/2) #use half of square root of standard deviation as the range for gaussian normal
rtstd = rtstd.to_dict()

In [18]:
for key in rtstd:
    #fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, rtstd[key])))
    fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, 2)))
fudge = fudge[fudge>=0]
fudge.dropna(inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [19]:
rtstd

{'t_cost_per_claim_excluded': 27.56510951465134,
 't_claim_count_schedule2': 3.695663044319792,
 't_claim_per_bene': 1.6580722340938179,
 '%b2bg_claim_count': 2.167956673640725,
 '%b2bg_drug_cost': 3.0186404698994176,
 '%b2t_claim_count': 2.014062570022093,
 '%b2t_drug_cost': 2.9841678740729662,
 't_cost_per_claim': 42.50228420227383,
 't_cost_per_claim_ge65': 38.62649146557551,
 't_claim_per_bene_ge65': 16.379438491165413,
 'mapd_cost_per_claim': 36.728859150984555,
 'pdp_cost_per_claim': 42.965906425220766,
 'lis_cost_per_claim': 58.42314094115782,
 'nonlis_cost_per_claim': 36.45880056527369,
 'opioid_cost_per_claim': 36.70026419399047,
 'opioid_claim_per_bene': 9.187693029244286,
 'antibiotic_cost_per_claim': 29.137484263562207,
 'antibiotic_claim_per_bene': 4.985879512524026,
 'antipsych_cost_per_claim_ge65': 47.83961204335617,
 'antipsych_claim_per_bene_ge65': 6.928243051545445,
 'total_30_day_fill_count': 34.862952342871424,
 'total_day_supply': 180.63968027883968,
 'total_30_day

In [20]:
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              141681.000000            141681.000000     141681.000000   
mean                 2705.881783               121.122820         23.902216   
std                  1968.939106                76.486305         13.097121   
min                    84.439635                 0.007586          0.003882   
25%                  1775.441214                62.796520         13.354577   
50%                  2289.765899               106.148829         22.556502   
75%                  3059.279193               146.571006         28.726760   
max                 21785.662377               300.734881         62.203813   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      141681.000000    141681.000000     141681.000000   141681.000000   
mean           24.236245        71.311660         23.888470       69.091155   
std             7.038982        14.022935          6.914676       11.945687   
min             0.001018         0.002867          0.002755        0.000166   
25%            19.515351        65.568426         19.378789       65.260137   
50%            22.332627        71.487188         21.875690       70.360132   
75%            29.796029        77.779056         29.552338       75.142335   
max           106.769306       104.377496         85.699078      102.449506   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     141681.000000          141681.000000          141681.000000  ...   
mean        6595.053606            6365.308270            2309.055252  ...   
std         2956.750994            2896.853617            1314.229294  ...   
min          520.824904               0.065079               0.001222  ...   
25%         5422.754301            5028.306376            1259.780977  ...   
50%         5852.119027            5913.060071            2252.109755  ...   
75%         7149.808571            6676.641984            2696.989238  ...   
max        55650.269587           54690.783735            5710.751515  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              141681.000000                  141681.000000   
mean                  195.761808                   10876.643230   
std                    67.990553                   11695.787396   
min                     0.001219                       0.000031   
25%                   153.201663                       3.160455   
50%                   197.340146                   10169.586338   
75%                   229.861821                   13780.194590   
max                   434.203758                   46826.411129   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  141681.000000            141681.000000   
mean                      270.488059              9058.123173   
std                       337.129364              8418.666890   
min                         0.000053                37.672535   
25%                         1.108354              3535.982500   
50%                         2.832944              5614.155217   
75%                       603.348114             13702.255326   
max                       914.347431             31953.099863   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count     141681.000000                 141681.000000          141681.000000   
mean      245507.256244                   6732.048598          182256.735667   
std       218816.240544                   7115.517310          188700.427656   
min          199.209592                      0.004005               0.032977   
25%        98604.040973                   1789.314401           50760.529560   
50%       157269.563118                   3745.398592          106760.892503   
75%       384386.728695                   9935.243390          254102.561054   
max       838604.341945                  28675.906

In [21]:
only_excluded.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count                 149.000000               149.000000        149.000000   
mean                 2171.259262                38.577181         10.600000   
std                  3042.098054                54.862134         11.044009   
min                    44.000000                 1.000000          0.000000   
25%                   392.510000                 3.000000          3.300000   
50%                  1249.020000                15.000000          6.700000   
75%                  2442.450000                54.000000         13.000000   
max                 21781.130000               294.000000         55.700000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count         149.000000       149.000000        149.000000      149.000000   
mean           17.181208        43.812081         16.375839       43.073826   
std            18.855085        36.578196         16.283583       35.748388   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            20.000000        62.000000         20.000000       62.000000   
75%            30.000000        74.000000         30.000000       73.000000   
max           100.000000       100.000000         80.000000       99.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count        149.000000             149.000000             149.000000  ...   
mean        7475.798658            5703.731544             847.630872  ...   
std         7257.423619            5996.467731            1078.169904  ...   
min          460.000000               0.000000               0.000000  ...   
25%         4398.000000            2306.000000               0.000000  ...   
50%         5940.000000            5152.000000             498.000000  ...   
75%         7998.000000            6861.000000            1211.000000  ...   
max        55647.000000           54687.000000            5703.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count                 149.000000                     149.000000   
mean                   98.093960                    3878.463087   
std                    99.765762                    9204.066253   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                   112.000000                       0.000000   
75%                   172.000000                       0.000000   
max                   428.000000                   46820.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                     149.000000               149.000000   
mean                       61.959732              2654.093960   
std                       192.786637              4882.087242   
min                         0.000000                23.000000   
25%                         0.000000               161.600000   
50%                         0.000000               802.000000   
75%                         0.000000              2883.700000   
max                       907.000000             31945.900000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count        149.000000                    149.000000             149.000000   
mean       72350.187919                   1724.177181           47183.523490   
std       131106.061835                   3848.187495          104121.610141   
min          202.000000                      0.000000               0.000000   
25%         3756.000000                     51.000000            1063.000000   
50%        21761.000000                    348.300000            9810.000000   
75%        81124.000000                   1530.000000           42967.000000   
max       838598.000000                  28669.200

In [22]:
fudge.shape

(141681, 27)

In [23]:
fudge=fudge.sample(n=10000)
fudge.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
127536                3191.316505               211.886799         28.433183   
50230                 2288.334322                98.317154         27.149104   
323396                5993.973858               290.448401         57.031497   
428100                2911.662720               149.364779         21.087367   
127536                3189.539217               211.428166         24.100692   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
127536          19.176324        68.195597         20.629335       69.924933   
50230           27.798729        67.974749         29.606469       69.590592   
323396          31.073854        82.450360         30.902192       78.237954   
428100          20.340847        96.084114         24.588945       70.966504   
127536          15.820852        69.722884         20.254329       67.877908   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
127536       5663.450458            5150.807190            2615.245545  ...   
50230        7375.352001            6796.715817            2350.873214  ...   
323396       6241.516505            6181.528965            5704.260145  ...   
428100       5696.539354            5914.173100            2374.661238  ...   
127536       5666.615529            5151.515196            2612.040476  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
127536                 210.254453                   12781.647704   
50230                  234.454407                   11212.108906   
323396                 212.116160                   13614.693660   
428100                 206.986211                    4909.485001   
127536                 204.238451                   12778.526027   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
127536                     603.839404             16095.224951   
50230                      622.026946              4068.356848   
323396                     906.287655             30202.853050   
428100                     481.492576             13705.122470   
127536                     604.962607             16092.182372   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
127536     418477.516282                   9937.860423          254103.015728   
50230      109476.633177                   2933.104860           77618.609625   
323396     838597.753877                  28670.634054          794793.020344   
428100     384386.690478                  12598.407965          352661.073157   
127536     418479.823345                   9932.773186          254107.466053   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
127536       13421.241159                7.080584            1  
50230         1380.307824                3.441356            1  
323396       13997.944931                2.445354            1  
428100        8629.479327                3.713558            1  
127536       13419.485235                4.805825            1  

[5 rows x 27 columns]

In [24]:
ag_2013 = pd.concat([new_main_2013, fudge])
ag_2013.dropna(inplace=True)

In [25]:
ag_2013[ag_2013["is_excluded"]==1].shape

(10000, 27)

In [26]:
ag_2013.shape

(646215, 27)

#Applying PCA, 2 components and 3 components for variance visualization

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_), color='r')

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_cross_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

plt.vlines(1, color='grey', ymax=0.1, ymin=0, linestyle=':')
plt.vlines(2, color='grey', ymax=0.1, ymin=0, linestyle=':')

plt.annotate('1 components', xy=(0.6, 0.05), xytext=(0.9, 0.05), fontsize=15, rotation=90)
plt.annotate('2 components', xy=(1.6, 0.05), xytext=(1.9, 0.05), fontsize=15, rotation=90)

plt.savefig('VarExp.jpeg', dpi=1000)
plt.tight_layout()
plt.show()

In [27]:
#Training without Upsampling or Downsampling
#fudged data (ag_2013) only for train, regular data (new_df) only for test

X_train = ag_2013.drop(['is_excluded'], axis=1)
y_train = ag_2013['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X = new_main_2013.drop(['is_excluded'], axis=1)
#y = new_main_2013['is_excluded']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [29]:
print(pca.explained_variance_ratio_)

[8.99826165e-01 5.77817446e-02 1.30509980e-02 8.73634316e-03
 7.21120335e-03 4.71554680e-03 2.77151436e-03 1.51722526e-03
 1.40428501e-03 1.38414222e-03 1.09947417e-03 2.71060335e-04
 2.13766709e-04 9.08453215e-06 6.25148270e-06 5.07959335e-07
 3.72421582e-07 1.59680343e-07 7.61721820e-08 5.95358548e-08
 9.80389516e-09 4.69392324e-09 3.86344968e-09 3.90175693e-10
 3.24146314e-10]


In [30]:
Labels = ag_2013.drop(["is_excluded"],axis = 1).columns

In [31]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 't_cost_per_claim',
 'lis_cost_per_claim',
 'total_day_supply_ge65',
 'mapd_cost_per_claim',
 't_cost_per_claim',
 'pdp_cost_per_claim',
 'antipsych_cost_per_claim_ge65',
 'antibiotic_cost_per_claim',
 't_cost_per_claim_ge65',
 'opioid_day_supply',
 'opioid_cost_per_claim',
 't_cost_per_claim_excluded',
 't_claim_per_bene_ge65',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 '%b2bg_drug_cost',
 'total_30_day_fill_count_ge65',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2t_claim_count']

In [32]:
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [33]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

149


In [34]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [35]:
clf.feature_importances_

array([0.04200799, 0.04956647, 0.04334527, 0.05261777, 0.0329294 ,
       0.03302599, 0.02796783, 0.04044855, 0.03462859, 0.04628797,
       0.04416189, 0.05051496, 0.04015588, 0.08052933, 0.07030226,
       0.04068815, 0.07118106, 0.02715963, 0.0442618 , 0.03228607,
       0.00926979, 0.01021636, 0.03040648, 0.01368969, 0.0323508 ])

coef_df = pd.DataFrame(clf.feature_importances_, Labels, columns = ["Importances"])
coef_df.sort_values("Importances", ascending = False)

check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [36]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(y_pred_prob)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
1.0


array([[636215,      0],
       [     5,   9995]], dtype=int64)

In [37]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(y_pred_prob)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.6851952192110055


array([[158905,      0],
       [   147,      2]], dtype=int64)

In [38]:
#Upsampling only

ag_2013_majority = ag_2013[ag_2013['is_excluded'] == 0]
ag_2013_minority = ag_2013[ag_2013['is_excluded'] > 0]

# Increase by 10 times
ag_2013_minority_upsampled = resample(ag_2013_minority, replace=True, n_samples=100000, random_state=42) 
ag_2013_upsampled = pd.concat([ag_2013_majority, ag_2013_minority_upsampled])  
ag_2013_upsampled['is_excluded'].value_counts()

0    636215
1    100000
Name: is_excluded, dtype: int64

In [39]:
#fudged data (ag_2013) only for train, regular data (new_df) only for test
X_train = ag_2013_upsampled.drop(['is_excluded'], axis=1)
y_train = ag_2013_upsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [40]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [41]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [42]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[636215,      0],
       [     0, 100000]], dtype=int64)

In [43]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5471758800634122


array([[158905,      0],
       [   149,      0]], dtype=int64)

In [44]:
#Training on downsampled only and testing on regular

ag_2013_majority = ag_2013[ag_2013['is_excluded'] == 0]
ag_2013_minority = ag_2013[ag_2013['is_excluded'] > 0]

# Reduce by 10 times
ag_2013_majority_downsampled = resample(ag_2013_majority, replace=True, n_samples=81980, random_state=42) 
ag_2013_downsampled = pd.concat([ag_2013_majority_downsampled, ag_2013_minority]) 
ag_2013_downsampled['is_excluded'].value_counts()

0    81980
1    10000
Name: is_excluded, dtype: int64

In [45]:
#fudged data (ag_2013) only for train, regular data (new_df) only for test
X_train = ag_2013_downsampled.drop(['is_excluded'], axis=1)
y_train = ag_2013_downsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [46]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [47]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [48]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[81980,     0],
       [    2,  9998]], dtype=int64)

In [49]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5627687726130741


array([[158905,      0],
       [   149,      0]], dtype=int64)

In [50]:
#Upsampling/downsampling on training and testing on regular

ag_2013_majority = ag_2013[ag_2013['is_excluded'] == 0]
ag_2013_minority = ag_2013[ag_2013['is_excluded'] > 0]

ag_2013_updownsampled = pd.concat([ag_2013_majority_downsampled, ag_2013_minority_upsampled]) 
ag_2013_updownsampled['is_excluded'].value_counts()

1    100000
0     81980
Name: is_excluded, dtype: int64

In [51]:
#fudged data (ag_2013) only for train, regular data (new_df) only for test

X_train = ag_2013_updownsampled.drop(['is_excluded'], axis=1)
y_train = ag_2013_updownsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [52]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [53]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [54]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[ 81980,      0],
       [     0, 100000]], dtype=int64)

In [55]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.49239026567940114


array([[158905,      0],
       [   149,      0]], dtype=int64)

In conclusion, results from downsampling is the best.

In [56]:
#Classification Model Comparisons

def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn

from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import cross_validate, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, auc, recall_score, precision_score, accuracy_score, f1_score

seed = 42

#Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

scoring = {'AUC': 'roc_auc', 'Accuracy': 'accuracy', 'F1': 'f1'}

names = ["Naive Bayes", "Nearest Neighbors", "RBF SVM", 
         "AdaBoost", "GradientBoost", "ExtraTrees", "Random Forest"]

classifiers = [
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            SVC(kernel="rbf", C=1, probability=True),
            AdaBoostClassifier(n_estimators=25, random_state=seed),
            GradientBoostingClassifier(n_estimators=1000, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),]

trace_dict = {'x_vals':[], 'y_vals':[], 'y_error':[], 'colors':[], 'names':[]}
                                                                                         
#iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    cv_results = cross_validate(clf, X, y, scoring=scoring, cv=5, return_train_score=True)
    print('########################### \nFor {}'.format(name))
    for score in scoring:
        print('{0:s}: Mean-{1:.4f}  STD-{2:.4f}'.format(score, cv_results['test_'+score].mean(),\
                                                        cv_results['test_'+score].std()))
    
    trace_dict['x_vals'].append(counter)
    counter += 1
    trace_dict['y_vals'].append(cv_results['test_F1'].mean())
    trace_dict['y_error'].append()
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)
    trace_dict['y_error'].append(np.std(cv_results['test_F1']))

In [57]:
# Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

names = ["GradientBoost", "ExtraTrees", "Random Forest", "Naive Bayes", "Nearest Neighbors", "AdaBoost"]

classifiers = [
            GradientBoostingClassifier(n_estimators=50, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),      
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            AdaBoostClassifier(n_estimators=25, random_state=seed)]

In [58]:
trace_dict = {'x_vals':[], 'y_vals':[], 'colors':[], 'names':[]}
                                                                                         
# iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    X_train = ag_2013.drop(['is_excluded'], axis=1)
    y_train = ag_2013['is_excluded']
    X_test = new_df.drop(['is_excluded'], axis =1)
    y_test = new_df["is_excluded"]
    clf.fit(X_train, y_train)
    y_pred_prob = clf.predict_proba(X_test)
    cv_results = roc_auc_score(y_test, y_pred_prob[:,1])
    print('########################### \nFor {}'.format(name))
              
    trace_dict['x_vals'].append(counter)
    counter += 1
    print(cv_results)
    trace_dict['y_vals'].append(cv_results.mean())
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)

########################### 
For GradientBoost
0.5675222142139293
########################### 
For ExtraTrees
0.7600591421703357
########################### 
For Random Forest
0.6604852546865935
########################### 
For Naive Bayes
0.5988794748624658
########################### 
For Nearest Neighbors
0.8420585808624418
########################### 
For AdaBoost
0.5109130038229334



In [59]:
# Plotting ROC curves of the models
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
import plotly

n_classes = 1
fpr = dict()
tpr = dict()
roc_auc = dict()
plt.figure()
lw = 2
trace_dict = {}

for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    y_score = clf.fit(X_train, y_train).predict_proba(X_test)
    fpr[name], tpr[name], _ = roc_curve(y_test[:], y_score[:, 1])
    roc_auc[name] = auc(fpr[name], tpr[name])
    trace_dict.update({'trace' + name: go.Scatter(x=fpr[name], y=tpr[name], mode='lines', 
                                       line=dict(color=color, width=lw),
                                       showlegend=True,
                                       name='{0:s} AUC: {1:.2f}'.format(name, roc_auc[name]))})
trace_guess = go.Scatter(x=[0, 1], y=[0, 1], 
                mode='lines', 
                line=dict(color='navy', width=lw, dash='dash'),
                showlegend=False)
data = [trace_dict[trace] for trace in trace_dict] + [trace_guess]
layout = go.Layout(title='Receiver Operating Characteristics',
                   xaxis=dict(title='False Positive Rate'),
                   yaxis=dict(title='True Positive Rate'),
                   margin=go.Margin(l=50, r=50, b=30, t=65, pad=4),
                   legend=dict(x=0.7, y=0.4, font=dict(size=18))
                  )
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='ROCs')

<Figure size 432x288 with 0 Axes>