In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook, tqdm

In [2]:
new_main_2017 = pd.read_csv('data/ml_2017.csv', low_memory=False)
print("The data has a size of {}".format(new_main_2017.shape))

The data has a size of (904999, 32)


In [3]:
new_main_2017.head(1)

Unnamed: 0         npi specialty_description nppes_provider_state  \
0           0  1023417649     Internal Medicine                   PA   

   t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     512.29                       14               2.7   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  ...  \
0                0.0              0.0               0.0  ...   

   antipsych_cost_per_claim_ge65  antipsych_claim_per_bene_ge65  \
0                            0.0                            0.0   

   total_30_day_fill_count  total_day_supply  total_30_day_fill_count_ge65  \
0                    605.0             13547                         533.9   

   total_day_supply_ge65  opioid_day_supply  opioid_prescriber_rate  \
0                12009.0                0.0                     0.0   

   is_excluded       year  
0            0  2017-2018  

[1 rows x 32 columns]

In [4]:
new_main_2017.drop(['Unnamed: 0'], axis=1, inplace = True)

In [5]:
new_main_2017.drop(['npi', 'specialty_description','nppes_provider_state','year'], axis=1, inplace = True)

In [6]:
new_main_2017.head(1)

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     512.29                       14               2.7   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
0                0.0              0.0               0.0             0.0   

   t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
0            6966.0                 5285.0                  269.0  ...   

   antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
0                      116.0                            0.0   

   antipsych_claim_per_bene_ge65  total_30_day_fill_count  total_day_supply  \
0                            0.0                    605.0             13547   

   total_30_day_fill_count_ge65  total_day_supply_ge65  opioid_day_supply  \
0                         533.9                12009.0                0.0   

   opioid_prescriber_rate  is_excluded  
0                     0.0            0  

[1 rows x 27 columns]

In [7]:
len(new_main_2017[new_main_2017['is_excluded'] == 1])

101

In [8]:
dropIndex = new_main_2017[new_main_2017['is_excluded'] == 1].index

In [9]:
len(new_main_2017[new_main_2017['is_excluded'] == 0])

904898

In [10]:
only_excluded = new_main_2017[new_main_2017['is_excluded'] == 1]
new_main_2017.drop(dropIndex, inplace = True)
new_main_2017 = new_main_2017.sample(frac=1)
random_sample = new_main_2017.iloc[0:180899]
new_df = pd.concat([only_excluded, random_sample])
new_main_2017 = new_main_2017.drop(new_main_2017.iloc[0:180899].index, axis = 0)
new_df = new_df.sample(frac=1)
#part_d_df.iloc[0:85000].index

In [11]:
#new_df.drop(['Unnamed: 0'], axis=1, inplace = True)
new_df.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
640617                    1943.33                       13               4.1   
750391                    1573.63                        5               2.9   
768194                    1278.57                       20              17.3   
596409                     280.36                       11               1.7   
689207                      87.83                        1               1.6   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
640617               10.0             63.0              10.0            63.0   
750391               20.0             44.0              20.0            44.0   
768194               20.0             64.0              20.0            64.0   
596409               10.0             36.0              10.0            36.0   
689207                0.0              0.0               0.0             0.0   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
640617            8379.0                 7896.0                  360.0  ...   
750391            7508.0                 9285.0                  329.0  ...   
768194           10612.0                11221.0                 2105.0  ...   
596409            1506.0                 1582.0                  160.0  ...   
689207             520.0                    0.0                    0.0  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
640617                        0.0                            0.0   
750391                      133.0                            0.0   
768194                      244.0                        59451.0   
596409                      105.0                            0.0   
689207                      129.0                            0.0   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
640617                            0.0                    635.5   
750391                            0.0                    260.9   
768194                            0.0                   1012.5   
596409                            0.0                    383.1   
689207                            0.0                     33.0   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
640617             17957                         377.2                10549.0   
750391              6834                         158.9                 4192.0   
768194             28409                         417.8                11915.0   
596409              4122                         217.0                 2194.0   
689207               261                           0.0                    0.0   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
640617            10307.0                   59.67            0  
750391                0.0                    0.00            0  
768194             2850.0                    9.96            0  
596409                0.0                    0.00            0  
689207                0.0                    0.00            0  

[5 rows x 27 columns]

In [12]:
new_main_2017.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count               7.239990e+05            723999.000000     723999.000000   
mean                2.211595e+03                25.530519          6.389761   
std                 5.780364e+03                40.552056          7.114598   
min                 0.000000e+00                 0.000000          0.000000   
25%                 1.670100e+02                 2.000000          1.900000   
50%                 6.741900e+02                 7.000000          3.600000   
75%                 2.370290e+03                29.000000          8.300000   
max                 1.713038e+06               393.000000        307.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      723999.000000    723999.000000     723999.000000   723999.000000   
mean           12.569051        38.906029         12.347517       38.846846   
std            16.528388        37.132151         15.887904       36.907153   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        42.000000         10.000000       43.000000   
75%            20.000000        73.000000         20.000000       73.000000   
max           100.000000       100.000000        100.000000      100.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count      7.239990e+05           7.239990e+05          723999.000000  ...   
mean       1.253042e+04           1.026093e+04             478.928703  ...   
std        5.398670e+04           3.652764e+04             686.064979  ...   
min        0.000000e+00           0.000000e+00               0.000000  ...   
25%        2.355000e+03           1.397000e+03               0.000000  ...   
50%        5.505000e+03           4.658000e+03             222.000000  ...   
75%        9.334000e+03           7.992000e+03             652.000000  ...   
max        1.712797e+07           7.622389e+06           27000.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              723999.000000                  723999.000000   
mean                   92.371187                    1382.985420   
std                    82.630107                    6956.817534   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                   113.000000                       0.000000   
75%                   143.000000                       0.000000   
max                  3422.000000                  479253.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  723999.000000            723999.000000   
mean                       28.341136              2507.240687   
std                       144.814574              5137.089381   
min                         0.000000                11.000000   
25%                         0.000000               141.000000   
50%                         0.000000               444.900000   
75%                         0.000000              2266.000000   
max                      6007.000000            447960.500000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      7.239990e+05                 723999.000000           7.239990e+05   
mean       6.969298e+04                   2032.622450           5.681541e+04   
std        1.438730e+05                   4460.559101           1.252993e+05   
min        1.100000e+01                      0.000000           0.000000e+00   
25%        2.168000e+03                     72.000000           9.720000e+02   
50%        1.027400e+04                    298.000000           6.691000e+03   
75%        6.273600e+04                   1609.700000           4.438300e+04   
max        5.634058e+06                 379751.000

In [13]:
import math

In [14]:
from sklearn import decomposition
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, auc
from sklearn.utils import resample
from sklearn.preprocessing import label_binarize
from sklearn.svm import SVC
from scipy.stats import pointbiserialr

In [15]:
#part_d_excluded = new_df[new_df["is_excluded"]==1]

fudge = resample(only_excluded, replace=True, n_samples=1000000, random_state = 0)
#fudge.drop(['Unnamed: 0'], axis=1, inplace = True)
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count             1000000.000000           1000000.000000    1000000.000000   
mean                 5194.967630                38.609067          9.485671   
std                 28249.745002                55.813583          9.620971   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count     1000000.000000   1000000.000000    1000000.000000  1000000.000000   
mean           11.374050        36.234950         10.876360       36.026284   
std            14.980311        36.168503         12.989995       35.937057   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count    1000000.000000         1000000.000000         1000000.000000  ...   
mean       10551.133795            8908.213605             751.031469  ...   
std        17528.724650           16454.262782             932.513383  ...   
min          294.000000               0.000000               0.000000  ...   
25%         4406.000000            2876.000000               0.000000  ...   
50%         7223.000000            5345.000000             378.000000  ...   
75%        10419.000000            7982.000000            1163.000000  ...   
max       141957.000000          125896.000000            4355.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count             1000000.000000                 1000000.000000   
mean                   77.438471                    2743.050558   
std                    88.433065                    8561.702769   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   157.000000                     633.000000   
max                   322.000000                   50758.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                 1000000.000000           1000000.000000   
mean                       43.789287              3131.733322   
std                       158.750327              5513.810033   
min                         0.000000                13.000000   
25%                         0.000000               109.000000   
50%                         0.000000               632.600000   
75%                         0.000000              3164.200000   
max                       803.000000             33073.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count    1000000.000000                1000000.000000         1000000.000000   
mean       88423.346199                   2090.284659           59364.759391   
std       156739.468845                   4178.857341          118866.398677   
min          221.000000                      0.000000               0.000000   
25%         2955.000000                     62.000000            1280.000000   
50%        18369.000000                    368.400000           10843.000000   
75%        90194.000000                   1882.600000           52000.000000   
max       934916.000000                  22770.800

In [16]:
std = fudge.describe().loc["std"]
std = std[0:26]

In [17]:
rtstd = std.map(lambda x : math.sqrt(x)/2) #use half of square root of standard deviation as the range for gaussian normal
rtstd = rtstd.to_dict()

In [18]:
for key in rtstd:
    #fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, rtstd[key])))
    fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, 2)))
fudge = fudge[fudge>=0]
fudge.dropna(inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [19]:
rtstd

{'t_cost_per_claim_excluded': 84.03830228283725,
 't_claim_count_schedule2': 3.735424432090368,
 't_claim_per_bene': 1.5508844893809823,
 '%b2bg_claim_count': 1.9352203219559672,
 '%b2bg_drug_cost': 3.007012758064355,
 '%b2t_claim_count': 1.802081760350314,
 '%b2t_drug_cost': 2.99737621069871,
 't_cost_per_claim': 66.19804500548426,
 't_cost_per_claim_ge65': 64.13708518052151,
 't_claim_per_bene_ge65': 15.268541048298102,
 'mapd_cost_per_claim': 64.61408506431768,
 'pdp_cost_per_claim': 67.25735816485223,
 'lis_cost_per_claim': 68.22596052313033,
 'nonlis_cost_per_claim': 62.07153722436618,
 'opioid_cost_per_claim': 46.504668620058595,
 'opioid_claim_per_bene': 8.847407251096762,
 'antibiotic_cost_per_claim': 29.817508674809556,
 'antibiotic_claim_per_bene': 4.701942818546453,
 'antipsych_cost_per_claim_ge65': 46.26473486591827,
 'antipsych_claim_per_bene_ge65': 6.299808071086247,
 'total_30_day_fill_count': 37.12751686106159,
 'total_day_supply': 197.95167898077315,
 'total_30_day_fil

In [20]:
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              115020.000000            115020.000000     115020.000000   
mean                 3620.440014               121.796508         21.059942   
std                  3351.937990                76.062795         10.511540   
min                    41.434751                 0.007947          0.008382   
25%                  1819.191869                62.424880         13.996954   
50%                  3002.566527               117.601585         19.608105   
75%                  4191.784871               152.179567         24.847275   
max                286887.504557               305.889940         53.288143   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      115020.000000    115020.000000     115020.000000   115020.000000   
mean           17.642962        66.652208         17.643202       66.167208   
std             6.744974        12.650744          6.751661       12.649563   
min             0.001331         0.001250          0.000528        0.002098   
25%            11.498131        63.835498         11.487487       63.456317   
50%            18.982799        68.939246         18.984291       68.693956   
75%            21.215446        73.466242         21.231879       72.921545   
max            64.086000       104.757918         66.724604      104.553769   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     115020.000000          115020.000000          115020.000000  ...   
mean        8202.252845            7535.053842            2019.749603  ...   
std         5412.909876            4741.734793            1058.971552  ...   
min          366.877688               1.212781               0.000925  ...   
25%         5312.957350            4754.084023            1418.601093  ...   
50%         5957.502048            5688.139523            1768.442371  ...   
75%        10246.472842            9553.972714            2606.703935  ...   
max       141958.472729          125898.700115            4362.475358  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              115020.000000                  115020.000000   
mean                  168.453609                    8510.089217   
std                    51.586517                   14300.084406   
min                     0.000164                       0.000140   
25%                   157.500934                     754.146670   
50%                   172.391331                    3287.697825   
75%                   209.919668                    4982.195986   
max                   328.291117                   50760.552899   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  115020.000000            115020.000000   
mean                      247.844387             10443.221261   
std                       307.834687              8896.147327   
min                         0.000116                35.825144   
25%                         1.157015              3233.028388   
50%                         3.053487              9283.952234   
75%                       623.065456             13861.983980   
max                       810.327031             33080.252020   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count     115020.000000                 115020.000000          115020.000000   
mean      294409.215004                   7264.580999          205487.963975   
std       252005.648105                   6937.908084          196614.246996   
min          231.667649                      0.651231               2.332491   
25%        91532.068940                   2205.988371           63403.745682   
50%       268680.588902                   5177.180204          147270.675733   
75%       390052.589368                   9289.277173          270397.723430   
max       934922.722389                  22779.937

In [21]:
only_excluded.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count                 101.000000               101.000000        101.000000   
mean                 5221.393465                38.673267          9.499010   
std                 28518.834547                56.116684          9.667021   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count         101.000000       101.000000        101.000000      101.000000   
mean           11.386139        36.306931         10.891089       36.099010   
std            15.035272        36.333935         13.045996       36.102771   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count        101.000000             101.000000             101.000000  ...   
mean       10562.524752            8919.534653             751.980198  ...   
std        17653.641240           16564.118105             937.517232  ...   
min          294.000000               0.000000               0.000000  ...   
25%         4406.000000            2876.000000               0.000000  ...   
50%         7223.000000            5345.000000             378.000000  ...   
75%        10419.000000            7982.000000            1163.000000  ...   
max       141957.000000          125896.000000            4355.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count                 101.000000                     101.000000   
mean                   77.495050                    2757.247525   
std                    88.851182                    8633.955942   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   157.000000                     633.000000   
max                   322.000000                   50758.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                     101.000000               101.000000   
mean                       44.079208              3136.292079   
std                       159.991417              5542.441612   
min                         0.000000                13.000000   
25%                         0.000000               109.000000   
50%                         0.000000               632.600000   
75%                         0.000000              3164.200000   
max                       803.000000             33073.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count        101.000000                    101.000000             101.000000   
mean       88552.960396                   2093.873267           59466.841584   
std       157554.695894                   4202.779267          119551.162208   
min          221.000000                      0.000000               0.000000   
25%         2955.000000                     62.000000            1280.000000   
50%        18369.000000                    368.400000           10843.000000   
75%        90194.000000                   1882.600000           52000.000000   
max       934916.000000                  22770.800

In [22]:
fudge.shape

(115020, 27)

In [23]:
fudge=fudge.sample(n=10000)
fudge.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
394626                1323.329265               117.960642         16.464682   
15936                 3561.291022               137.947148         31.843531   
250232                2055.281024               134.330214         22.985749   
250232                2055.190318               132.749968         20.829365   
15591                 5737.192401               176.507527         18.419334   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
394626           9.837992        70.346432          8.351582       67.363500   
15936           19.538723        76.957262         20.084003       79.614832   
250232          20.879553        69.376491         19.953949       69.090820   
250232          17.620837        65.455473         20.019689       71.674797   
15591           21.442674        77.075079         17.329945       77.804503   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
394626       5544.216032            5165.236987            1418.593027  ...   
15936        7989.761622            7771.028694            3902.728009  ...   
250232       5318.587272            4757.997034            2070.333504  ...   
250232       5318.625497            4755.367022            2068.797384  ...   
15591       10250.591760            9559.121916            1860.035355  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
394626                 172.946116                     758.364345   
15936                  171.163517                   32837.827028   
250232                 155.020715                    4457.316968   
250232                 153.661973                    4454.701063   
15591                  193.655422                    1922.713762   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
394626                       1.487764              7731.162156   
15936                        3.411723             10495.749012   
250232                     460.975632              9670.868369   
250232                     460.973392              9667.486234   
15591                        2.859027             19479.821606   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
394626     219194.751741                   5177.729582          147273.750216   
15936      302809.913750                   7308.775344          211947.297951   
250232     268678.018926                   7809.690992          219079.777835   
250232     268676.155425                   7810.655306          219082.046845   
15591      551912.308973                  17043.344787          484195.717507   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
394626       15821.462328               14.086673            1  
15936        11385.897766                5.671517            1  
250232       10879.099277                5.862675            1  
250232       10878.199591                3.976740            1  
15591         5479.418904                1.729178            1  

[5 rows x 27 columns]

In [24]:
ag_2017 = pd.concat([new_main_2017, fudge])
ag_2017.dropna(inplace=True)

In [25]:
ag_2017[ag_2017["is_excluded"]==1].shape

(10000, 27)

In [26]:
ag_2017.shape

(733999, 27)

#Applying PCA, 2 components and 3 components for variance visualization

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_), color='r')

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_cross_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

plt.vlines(1, color='grey', ymax=0.1, ymin=0, linestyle=':')
plt.vlines(2, color='grey', ymax=0.1, ymin=0, linestyle=':')

plt.annotate('1 components', xy=(0.6, 0.05), xytext=(0.9, 0.05), fontsize=15, rotation=90)
plt.annotate('2 components', xy=(1.6, 0.05), xytext=(1.9, 0.05), fontsize=15, rotation=90)

plt.savefig('VarExp.jpeg', dpi=1000)
plt.tight_layout()
plt.show()

In [27]:
#Training without Upsampling or Downsampling
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017.drop(['is_excluded'], axis=1)
y_train = ag_2017['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X = new_main_2017.drop(['is_excluded'], axis=1)
#y = new_main_2017['is_excluded']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [29]:
print(pca.explained_variance_ratio_)

[7.13700535e-01 2.00719035e-01 3.17619178e-02 1.73367337e-02
 1.44752287e-02 7.28680091e-03 5.22912319e-03 5.04097367e-03
 1.81973459e-03 9.79282418e-04 8.22399523e-04 4.64093694e-04
 3.48778557e-04 1.05592297e-05 4.03529308e-06 3.34100413e-07
 2.27012538e-07 1.03203708e-07 4.80720203e-08 4.52092520e-08
 5.18160730e-09 2.81574566e-09 2.49100454e-09 2.24581498e-10
 1.48346426e-10]


In [30]:
Labels = ag_2017.drop(["is_excluded"],axis = 1).columns

In [31]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 'lis_cost_per_claim',
 'mapd_cost_per_claim',
 'pdp_cost_per_claim',
 'mapd_cost_per_claim',
 't_cost_per_claim',
 'total_day_supply_ge65',
 't_cost_per_claim_ge65',
 'antibiotic_cost_per_claim',
 'antipsych_cost_per_claim_ge65',
 'antipsych_cost_per_claim_ge65',
 't_cost_per_claim_excluded',
 'opioid_cost_per_claim',
 'total_30_day_fill_count',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 'total_30_day_fill_count_ge65',
 'total_30_day_fill_count_ge65',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2t_drug_cost']

In [32]:
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [33]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [34]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


coef_df = pd.DataFrame(clf.feature_importances_, Labels, columns = ["Importances"])
coef_df.sort_values("Importances", ascending = False)

check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [35]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(y_pred_prob)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
0.9999993587698325


array([[723897,    102],
       [    25,   9975]], dtype=int64)

In [36]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(y_pred_prob)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.6037749088039335


array([[180869,     30],
       [    84,     17]], dtype=int64)

In [37]:
#Upsampling only

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Increase by 10 times
ag_2017_minority_upsampled = resample(ag_2017_minority, replace=True, n_samples=100000, random_state=42) 
ag_2017_upsampled = pd.concat([ag_2017_majority, ag_2017_minority_upsampled])  
ag_2017_upsampled['is_excluded'].value_counts()

0    723999
1    100000
Name: is_excluded, dtype: int64

In [38]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_upsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_upsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [39]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [40]:
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [41]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

0.9999999956906017


array([[723872,    127],
       [     2,  99998]], dtype=int64)

In [42]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.49969043499411275


array([[180829,     70],
       [   101,      0]], dtype=int64)

In [43]:
#Training on downsampled only and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Reduce by 10 times
ag_2017_majority_downsampled = resample(ag_2017_majority, replace=True, n_samples=81980, random_state=42) 
ag_2017_downsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority]) 
ag_2017_downsampled['is_excluded'].value_counts()

0    81980
1    10000
Name: is_excluded, dtype: int64

In [44]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_downsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_downsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [45]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [46]:
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [47]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

0.9999943101976092


array([[81891,    89],
       [   25,  9975]], dtype=int64)

In [48]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5021904351309431


array([[180607,    292],
       [   101,      0]], dtype=int64)

In [49]:
#Upsampling/downsampling on training and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

ag_2017_updownsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority_upsampled]) 
ag_2017_updownsampled['is_excluded'].value_counts()

1    100000
0     81980
Name: is_excluded, dtype: int64

In [50]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017_updownsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_updownsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [51]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [52]:
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [53]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

0.9999999597462796


array([[81856,   124],
       [    2, 99998]], dtype=int64)

In [54]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.49917633596647853


array([[180719,    180],
       [   101,      0]], dtype=int64)

In conclusion, results from downsampling is the best.

In [55]:
#Classification Model Comparisons

def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn

from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import cross_validate, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, auc, recall_score, precision_score, accuracy_score, f1_score

seed = 42

#Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

scoring = {'AUC': 'roc_auc', 'Accuracy': 'accuracy', 'F1': 'f1'}

names = ["Naive Bayes", "Nearest Neighbors", "RBF SVM", 
         "AdaBoost", "GradientBoost", "ExtraTrees", "Random Forest"]

classifiers = [
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            SVC(kernel="rbf", C=1, probability=True),
            AdaBoostClassifier(n_estimators=25, random_state=seed),
            GradientBoostingClassifier(n_estimators=1000, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),]

trace_dict = {'x_vals':[], 'y_vals':[], 'y_error':[], 'colors':[], 'names':[]}
                                                                                         
#iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    cv_results = cross_validate(clf, X, y, scoring=scoring, cv=5, return_train_score=True)
    print('########################### \nFor {}'.format(name))
    for score in scoring:
        print('{0:s}: Mean-{1:.4f}  STD-{2:.4f}'.format(score, cv_results['test_'+score].mean(),\
                                                        cv_results['test_'+score].std()))
    
    trace_dict['x_vals'].append(counter)
    counter += 1
    trace_dict['y_vals'].append(cv_results['test_F1'].mean())
    trace_dict['y_error'].append()
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)
    trace_dict['y_error'].append(np.std(cv_results['test_F1']))

In [68]:
# Identifying the best model algorithm
#colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

#names = ["GradientBoost", "ExtraTrees", "Random Forest", "Naive Bayes", "Nearest Neighbors", "AdaBoost"]

colors = ["rgb(76,000,153)"]

names = ["Nearest Neighbors"]

classifiers = [KNeighborsClassifier(n_neighbors=1)]

In [69]:
trace_dict = {'x_vals':[], 'y_vals':[], 'colors':[], 'names':[]}
                                                                                         
# iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    X_train = ag_2017.drop(['is_excluded'], axis=1)
    y_train = ag_2017['is_excluded']
    X_test = new_df.drop(['is_excluded'], axis =1)
    y_test = new_df["is_excluded"]
    clf.fit(X_train, y_train)
    y_pred_prob = clf.predict_proba(X_test)
    cv_results = roc_auc_score(y_test, y_pred_prob[:,1])
    print('########################### \nFor {}'.format(name))
              
    trace_dict['x_vals'].append(counter)
    counter += 1
    print(cv_results)
    trace_dict['y_vals'].append(cv_results.mean())
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)

########################### 
For Nearest Neighbors
0.8365756199277328

