In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook, tqdm

In [2]:
new_main_2017 = pd.read_csv('data/ml_2017.csv', low_memory=False)
print("The data has a size of {}".format(new_main_2017.shape))

The data has a size of (904999, 32)


In [3]:
new_main_2017.head(1)

Unnamed: 0         npi specialty_description nppes_provider_state  \
0           0  1023417649     Internal Medicine                   PA   

   t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     512.29                       14               2.7   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  ...  \
0                0.0              0.0               0.0  ...   

   antipsych_cost_per_claim_ge65  antipsych_claim_per_bene_ge65  \
0                            0.0                            0.0   

   total_30_day_fill_count  total_day_supply  total_30_day_fill_count_ge65  \
0                    605.0             13547                         533.9   

   total_day_supply_ge65  opioid_day_supply  opioid_prescriber_rate  \
0                12009.0                0.0                     0.0   

   is_excluded       year  
0            0  2017-2018  

[1 rows x 32 columns]

In [4]:
new_main_2017.drop(['Unnamed: 0'], axis=1, inplace = True)

In [5]:
new_main_2017.drop(['npi', 'specialty_description','nppes_provider_state','year'], axis=1, inplace = True)

In [6]:
new_main_2017.head(1)

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     512.29                       14               2.7   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
0                0.0              0.0               0.0             0.0   

   t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
0            6966.0                 5285.0                  269.0  ...   

   antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
0                      116.0                            0.0   

   antipsych_claim_per_bene_ge65  total_30_day_fill_count  total_day_supply  \
0                            0.0                    605.0             13547   

   total_30_day_fill_count_ge65  total_day_supply_ge65  opioid_day_supply  \
0                         533.9                12009.0                0.0   

   opioid_prescriber_rate  is_excluded  
0                     0.0            0  

[1 rows x 27 columns]

In [7]:
len(new_main_2017[new_main_2017['is_excluded'] == 1])

101

In [8]:
dropIndex = new_main_2017[new_main_2017['is_excluded'] == 1].index

In [9]:
len(new_main_2017[new_main_2017['is_excluded'] == 0])

904898

In [10]:
only_excluded = new_main_2017[new_main_2017['is_excluded'] == 1]
new_main_2017.drop(dropIndex, inplace = True)
new_main_2017 = new_main_2017.sample(frac=1)
random_sample = new_main_2017.iloc[0:85000]
new_df = pd.concat([only_excluded, random_sample])
new_main_2017 = new_main_2017.drop(new_main_2017.iloc[0:85000].index, axis = 0)
new_df = new_df.sample(frac=1)
#part_d_df.iloc[0:85000].index

In [11]:
#new_df.drop(['Unnamed: 0'], axis=1, inplace = True)
new_df.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
79693                     2847.86                       27               8.0   
678135                     333.61                        4               2.2   
653216                     199.20                        3               2.4   
555001                     230.88                        5               5.7   
497439                      45.77                        1               0.0   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
79693                10.0             75.0              10.0            75.0   
678135                0.0              0.0               0.0             0.0   
653216               10.0             74.0              10.0            74.0   
555001                0.0              0.0               0.0             0.0   
497439                0.0              0.0               0.0             0.0   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
79693            14184.0                15171.0                  761.0  ...   
678135             441.0                  448.0                  193.0  ...   
653216            5132.0                 5717.0                  234.0  ...   
555001            1899.0                    0.0                    0.0  ...   
497439            1607.0                    0.0                    0.0  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
79693                         0.0                        10776.0   
678135                      137.0                            0.0   
653216                      111.0                            0.0   
555001                      140.0                            0.0   
497439                        0.0                            0.0   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
79693                             0.0                   1552.7   
678135                            0.0                    329.0   
653216                            0.0                    513.6   
555001                            0.0                    131.5   
497439                            0.0                     32.0   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
79693              45226                        1335.4                39090.0   
678135              1745                          58.0                  280.0   
653216             14542                         462.5                13166.0   
555001              1816                           0.0                    0.0   
497439               813                           0.0                    0.0   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
79693                 0.0                    0.00            0  
678135              443.0                   44.07            0  
653216                0.0                    0.00            0  
555001              170.0                   19.33            0  
497439                0.0                    0.00            0  

[5 rows x 27 columns]

In [12]:
new_main_2017.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count               8.198980e+05            819898.000000     819898.000000   
mean                2.207052e+03                25.573253          6.398950   
std                 5.651176e+03                40.594888          7.126311   
min                 0.000000e+00                 0.000000          0.000000   
25%                 1.672025e+02                 2.000000          1.900000   
50%                 6.770150e+02                 7.000000          3.600000   
75%                 2.373195e+03                29.000000          8.300000   
max                 1.713038e+06               394.000000        307.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      819898.000000    819898.000000     819898.000000   819898.000000   
mean           12.579845        38.953683         12.359586       38.895528   
std            16.520176        37.135421         15.884833       36.910883   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        42.000000         10.000000       43.000000   
75%            20.000000        73.000000         20.000000       73.000000   
max           100.000000       100.000000        100.000000      100.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count      8.198980e+05           8.198980e+05          819898.000000  ...   
mean       1.255764e+04           1.029871e+04             479.690372  ...   
std        5.528685e+04           3.672366e+04             686.553647  ...   
min        0.000000e+00           0.000000e+00               0.000000  ...   
25%        2.356000e+03           1.399000e+03               0.000000  ...   
50%        5.507000e+03           4.656000e+03             222.000000  ...   
75%        9.337000e+03           7.995000e+03             653.000000  ...   
max        1.712797e+07           7.622389e+06           27000.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              819898.000000                  819898.000000   
mean                   92.387698                    1387.327954   
std                    82.651732                    6982.805288   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                   113.000000                       0.000000   
75%                   143.000000                       0.000000   
max                  3422.000000                  479253.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  819898.000000            819898.000000   
mean                       28.261862              2510.303035   
std                       144.255109              5118.216743   
min                         0.000000                11.000000   
25%                         0.000000               141.000000   
50%                         0.000000               446.100000   
75%                         0.000000              2269.375000   
max                      6007.000000            202437.100000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      8.198980e+05                 819898.000000           8.198980e+05   
mean       6.979217e+04                   2034.813123           5.688922e+04   
std        1.438924e+05                   4444.228562           1.253090e+05   
min        1.100000e+01                      0.000000           0.000000e+00   
25%        2.169000e+03                     72.100000           9.740000e+02   
50%        1.030800e+04                    298.800000           6.714000e+03   
75%        6.287900e+04                   1611.700000           4.445200e+04   
max        3.705620e+06                 178412.300

In [13]:
import math

In [14]:
from sklearn import decomposition
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, auc
from sklearn.utils import resample
from sklearn.preprocessing import label_binarize
from sklearn.svm import SVC
from scipy.stats import pointbiserialr

In [15]:
fudge = resample(only_excluded, replace=True, n_samples=1000000, random_state = 0)
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count             1000000.000000           1000000.000000    1000000.000000   
mean                 5194.967630                38.609067          9.485671   
std                 28249.745002                55.813583          9.620971   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count     1000000.000000   1000000.000000    1000000.000000  1000000.000000   
mean           11.374050        36.234950         10.876360       36.026284   
std            14.980311        36.168503         12.989995       35.937057   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count    1000000.000000         1000000.000000         1000000.000000  ...   
mean       10551.133795            8908.213605             751.031469  ...   
std        17528.724650           16454.262782             932.513383  ...   
min          294.000000               0.000000               0.000000  ...   
25%         4406.000000            2876.000000               0.000000  ...   
50%         7223.000000            5345.000000             378.000000  ...   
75%        10419.000000            7982.000000            1163.000000  ...   
max       141957.000000          125896.000000            4355.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count             1000000.000000                 1000000.000000   
mean                   77.438471                    2743.050558   
std                    88.433065                    8561.702769   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   157.000000                     633.000000   
max                   322.000000                   50758.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                 1000000.000000           1000000.000000   
mean                       43.789287              3131.733322   
std                       158.750327              5513.810033   
min                         0.000000                13.000000   
25%                         0.000000               109.000000   
50%                         0.000000               632.600000   
75%                         0.000000              3164.200000   
max                       803.000000             33073.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count    1000000.000000                1000000.000000         1000000.000000   
mean       88423.346199                   2090.284659           59364.759391   
std       156739.468845                   4178.857341          118866.398677   
min          221.000000                      0.000000               0.000000   
25%         2955.000000                     62.000000            1280.000000   
50%        18369.000000                    368.400000           10843.000000   
75%        90194.000000                   1882.600000           52000.000000   
max       934916.000000                  22770.800

In [16]:
std = fudge.describe().loc["std"]
std = std[0:26]

In [17]:
rtstd = std.map(lambda x : math.sqrt(x)/2) #use half of square root of standard deviation as the range for gaussian normal
rtstd = rtstd.to_dict()

In [18]:
for key in rtstd:
    fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, 2)))
fudge = fudge[fudge>=0]
fudge.dropna(inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [19]:
rtstd

{'t_cost_per_claim_excluded': 84.03830228283725,
 't_claim_count_schedule2': 3.735424432090368,
 't_claim_per_bene': 1.5508844893809823,
 '%b2bg_claim_count': 1.9352203219559672,
 '%b2bg_drug_cost': 3.007012758064355,
 '%b2t_claim_count': 1.802081760350314,
 '%b2t_drug_cost': 2.99737621069871,
 't_cost_per_claim': 66.19804500548426,
 't_cost_per_claim_ge65': 64.13708518052151,
 't_claim_per_bene_ge65': 15.268541048298102,
 'mapd_cost_per_claim': 64.61408506431768,
 'pdp_cost_per_claim': 67.25735816485223,
 'lis_cost_per_claim': 68.22596052313033,
 'nonlis_cost_per_claim': 62.07153722436618,
 'opioid_cost_per_claim': 46.504668620058595,
 'opioid_claim_per_bene': 8.847407251096762,
 'antibiotic_cost_per_claim': 29.817508674809556,
 'antibiotic_claim_per_bene': 4.701942818546453,
 'antipsych_cost_per_claim_ge65': 46.26473486591827,
 'antipsych_claim_per_bene_ge65': 6.299808071086247,
 'total_30_day_fill_count': 37.12751686106159,
 'total_day_supply': 197.95167898077315,
 'total_30_day_fil

In [20]:
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              114753.000000            114753.000000     114753.000000   
mean                 3604.772728               121.787620         21.021195   
std                  3219.610723                76.061258         10.501383   
min                    39.189077                 0.012687          0.001407   
25%                  1819.170459                62.398594         14.028269   
50%                  2714.007273               117.664938         19.587042   
75%                  4191.566990               152.109427         24.773036   
max                286889.566429               307.370431         53.495408   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      114753.000000    114753.000000     114753.000000   114753.000000   
mean           17.622265        66.611975         17.611336       66.124299   
std             6.732663        12.673598          6.740611       12.664882   
min             0.001897         0.002179          0.002824        0.000276   
25%            11.473624        63.796197         11.451939       63.462338   
50%            18.962528        68.958756         18.952374       68.681884   
75%            21.212128        73.455783         21.202358       72.893880   
max            64.615098       104.556156         66.423324      101.839607   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     114753.000000          114753.000000          114753.000000  ...   
mean        8184.372230            7525.197724            2017.473622  ...   
std         5351.108154            4715.798348            1059.488606  ...   
min          366.756987               0.037359               0.004461  ...   
25%         5312.896842            4753.875221            1418.552248  ...   
50%         5957.271861            5687.933465            1768.040308  ...   
75%        10246.318571            9553.748541            2606.588800  ...   
max       141957.045408          125898.239503            4362.525890  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              114753.000000                  114753.000000   
mean                  168.300173                    8518.416888   
std                    51.464787                   14308.446552   
min                     0.000421                       0.000196   
25%                   157.475494                     754.397201   
50%                   172.262575                    3287.737085   
75%                   209.654923                    4982.228217   
max                   328.103469                   50762.085492   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  114753.000000            114753.000000   
mean                      248.053202             10437.566752   
std                       307.776888              8894.332334   
min                         0.000060                35.326785   
25%                         1.158585              3232.442768   
50%                         3.058247              9283.894880   
75%                       622.938553             13861.731636   
max                       810.870371             33080.654119   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count     114753.000000                 114753.000000          114753.000000   
mean      294272.202253                   7262.013051          205438.808669   
std       251965.589835                   6936.166485          196588.556099   
min          232.203694                      0.908414               0.786024   
25%        91531.589368                   2205.800843           63403.438943   
50%       268680.621393                   5177.313420          147270.926572   
75%       390052.398799                   9289.133322          270397.622946   
max       934925.328873                  22777.801

In [21]:
only_excluded.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count                 101.000000               101.000000        101.000000   
mean                 5221.393465                38.673267          9.499010   
std                 28518.834547                56.116684          9.667021   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count         101.000000       101.000000        101.000000      101.000000   
mean           11.386139        36.306931         10.891089       36.099010   
std            15.035272        36.333935         13.045996       36.102771   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count        101.000000             101.000000             101.000000  ...   
mean       10562.524752            8919.534653             751.980198  ...   
std        17653.641240           16564.118105             937.517232  ...   
min          294.000000               0.000000               0.000000  ...   
25%         4406.000000            2876.000000               0.000000  ...   
50%         7223.000000            5345.000000             378.000000  ...   
75%        10419.000000            7982.000000            1163.000000  ...   
max       141957.000000          125896.000000            4355.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count                 101.000000                     101.000000   
mean                   77.495050                    2757.247525   
std                    88.851182                    8633.955942   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   157.000000                     633.000000   
max                   322.000000                   50758.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                     101.000000               101.000000   
mean                       44.079208              3136.292079   
std                       159.991417              5542.441612   
min                         0.000000                13.000000   
25%                         0.000000               109.000000   
50%                         0.000000               632.600000   
75%                         0.000000              3164.200000   
max                       803.000000             33073.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count        101.000000                    101.000000             101.000000   
mean       88552.960396                   2093.873267           59466.841584   
std       157554.695894                   4202.779267          119551.162208   
min          221.000000                      0.000000               0.000000   
25%         2955.000000                     62.000000            1280.000000   
50%        18369.000000                    368.400000           10843.000000   
75%        90194.000000                   1882.600000           52000.000000   
max       934916.000000                  22770.800

In [22]:
fudge.shape

(114753, 27)

In [23]:
fudge=fudge.sample(n=10000)
fudge.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
214693                2121.176977                64.413782         16.067390   
488570               11006.347029               300.312044         45.473867   
658804                4739.494435                39.540261         12.172344   
658804                4743.715397                42.970036          6.778396   
214693                2121.834333                65.725541         12.320800   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
214693          21.136860        72.542177         21.327641       72.232507   
488570          32.043299        74.051736         28.138096       72.359164   
658804          16.435084        63.215824         21.724164       70.467014   
658804          18.067027        70.243218         20.198516       66.061486   
214693          19.789818        75.446816         18.142438       73.189610   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
214693       9999.816258           13684.163587            1123.659607  ...   
488570      12810.614209           12160.912634            4355.783721  ...   
658804      17797.456577           15800.656208             887.968952  ...   
658804      17794.891477           15800.897331             886.551282  ...   
214693      10001.157946           13684.709573            1123.405824  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
214693                 213.218877                       0.914062   
488570                 223.897765                    3289.174842   
658804                 181.966568                   48027.808828   
658804                 185.985271                   48021.582337   
214693                 215.307882                       1.842466   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
214693                       1.322300              4239.745588   
488570                     713.356477             33071.670138   
658804                     313.799525              1723.010705   
658804                     311.393503              1719.846722   
214693                       1.905251              4236.211656   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
214693     110546.039636                   2337.597890           63980.489340   
488570     934917.017058                  22771.572733          647619.858484   
658804      48997.221251                    947.944780           27251.172898   
658804      48999.620825                    950.434577           27250.979584   
214693     110547.471383                   2339.364624           63979.371886   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
214693        3107.264260               10.725904            1  
488570       26079.876517                5.258821            1  
658804        5331.478091                9.506070            1  
658804        5329.253363               10.009164            1  
214693        3106.873020               10.822310            1  

[5 rows x 27 columns]

In [24]:
ag_2017 = pd.concat([new_main_2017, fudge])
ag_2017.dropna(inplace=True)

In [25]:
ag_2017[ag_2017["is_excluded"]==1].shape

(10000, 27)

In [26]:
ag_2017.shape

(829898, 27)

In [27]:
#Training without Upsampling or Downsampling
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017.drop(['is_excluded'], axis=1)
y_train = ag_2017['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
Labels = ag_2017.drop(["is_excluded"],axis = 1).columns
Labels

Index(['t_cost_per_claim_excluded', 't_claim_count_schedule2',
       't_claim_per_bene', '%b2bg_claim_count', '%b2bg_drug_cost',
       '%b2t_claim_count', '%b2t_drug_cost', 't_cost_per_claim',
       't_cost_per_claim_ge65', 't_claim_per_bene_ge65', 'mapd_cost_per_claim',
       'pdp_cost_per_claim', 'lis_cost_per_claim', 'nonlis_cost_per_claim',
       'opioid_cost_per_claim', 'opioid_claim_per_bene',
       'antibiotic_cost_per_claim', 'antibiotic_claim_per_bene',
       'antipsych_cost_per_claim_ge65', 'antipsych_claim_per_bene_ge65',
       'total_30_day_fill_count', 'total_day_supply',
       'total_30_day_fill_count_ge65', 'total_day_supply_ge65',
       'opioid_day_supply', 'opioid_prescriber_rate'],
      dtype='object')

In [29]:
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [32]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [33]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [34]:
clf.feature_importances_

array([0.01080784, 0.03446143, 0.00831461, 0.13520194, 0.00705207,
       0.12377602, 0.0096685 , 0.0205414 , 0.012638  , 0.02037893,
       0.01093643, 0.02456064, 0.01464233, 0.00953282, 0.02899283,
       0.0167995 , 0.01887954, 0.02082444, 0.09890562, 0.22906446,
       0.02336224, 0.01751885, 0.02311043, 0.02409952, 0.04276276,
       0.01316685])

In [35]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(y_pred_prob)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
1.0


array([[819898,      0],
       [     1,   9999]], dtype=int64)

In [36]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(y_pred_prob)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.6431304018637158


array([[85000,     0],
       [   97,     4]], dtype=int64)

In [37]:
#Upsampling only

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Increase by 10 times
ag_2017_minority_upsampled = resample(ag_2017_minority, replace=True, n_samples=100000, random_state=42) 
ag_2017_upsampled = pd.concat([ag_2017_majority, ag_2017_minority_upsampled])  
ag_2017_upsampled['is_excluded'].value_counts()

0    819898
1    100000
Name: is_excluded, dtype: int64

In [38]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_upsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_upsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [39]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [40]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[819898,      0],
       [     0, 100000]], dtype=int64)

In [41]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.638190099009901


array([[85000,     0],
       [   96,     5]], dtype=int64)

In [42]:
#Training on downsampled only and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Reduce by 10 times
ag_2017_majority_downsampled = resample(ag_2017_majority, replace=True, n_samples=81980, random_state=42) 
ag_2017_downsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority]) 
ag_2017_downsampled['is_excluded'].value_counts()

0    81980
1    10000
Name: is_excluded, dtype: int64

In [43]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_downsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_downsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [44]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [45]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[81980,     0],
       [    0, 10000]], dtype=int64)

In [46]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.6351530576587071


array([[85000,     0],
       [   97,     4]], dtype=int64)

In [47]:
#Upsampling/downsampling on training and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

ag_2017_updownsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority_upsampled]) 
ag_2017_updownsampled['is_excluded'].value_counts()

1    100000
0     81980
Name: is_excluded, dtype: int64

In [48]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017_updownsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_updownsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [49]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [50]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[ 81980,      0],
       [     0, 100000]], dtype=int64)

In [51]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5723686080372743


array([[85000,     0],
       [   96,     5]], dtype=int64)

In conclusion, results from downsampling is the best.

In [52]:
#Classification Model Comparisons

def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn

from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import cross_validate, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, auc, recall_score, precision_score, accuracy_score, f1_score

seed = 42

#Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

scoring = {'AUC': 'roc_auc', 'Accuracy': 'accuracy', 'F1': 'f1'}

names = ["Naive Bayes", "Nearest Neighbors", "RBF SVM", 
         "AdaBoost", "GradientBoost", "ExtraTrees", "Random Forest"]

classifiers = [
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            SVC(kernel="rbf", C=1, probability=True),
            AdaBoostClassifier(n_estimators=25, random_state=seed),
            GradientBoostingClassifier(n_estimators=1000, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),]

trace_dict = {'x_vals':[], 'y_vals':[], 'y_error':[], 'colors':[], 'names':[]}
                                                                                         
#iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    cv_results = cross_validate(clf, X, y, scoring=scoring, cv=5, return_train_score=True)
    print('########################### \nFor {}'.format(name))
    for score in scoring:
        print('{0:s}: Mean-{1:.4f}  STD-{2:.4f}'.format(score, cv_results['test_'+score].mean(),\
                                                        cv_results['test_'+score].std()))
    
    trace_dict['x_vals'].append(counter)
    counter += 1
    trace_dict['y_vals'].append(cv_results['test_F1'].mean())
    trace_dict['y_error'].append()
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)
    trace_dict['y_error'].append(np.std(cv_results['test_F1']))

In [53]:
# Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

names = ["GradientBoost", "ExtraTrees", "Random Forest", "Naive Bayes", "Nearest Neighbors", "AdaBoost"]

classifiers = [
            GradientBoostingClassifier(n_estimators=50, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),      
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            AdaBoostClassifier(n_estimators=25, random_state=seed)]

In [54]:
trace_dict = {'x_vals':[], 'y_vals':[], 'colors':[], 'names':[]}
                                                                                         
# iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    X_train = ag_2017.drop(['is_excluded'], axis=1)
    y_train = ag_2017['is_excluded']
    X_test = new_df.drop(['is_excluded'], axis =1)
    y_test = new_df["is_excluded"]
    clf.fit(X_train, y_train)
    y_pred_prob = clf.predict_proba(X_test)
    cv_results = roc_auc_score(y_test, y_pred_prob[:,1])
    print('########################### \nFor {}'.format(name))
              
    trace_dict['x_vals'].append(counter)
    counter += 1
    print(cv_results)
    trace_dict['y_vals'].append(cv_results.mean())
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)

########################### 
For GradientBoost
0.5772728013977868
########################### 
For ExtraTrees
0.7565524752475247
########################### 
For Random Forest
0.6579040186371578
########################### 
For Naive Bayes
0.5662556202679091
########################### 
For Nearest Neighbors
0.8364836342457777
########################### 
For AdaBoost
0.4403175888177053

