In [951]:
#some of these we do not need

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm_notebook, tqdm
import glob, os, csv
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
import plotly
from sklearn.preprocessing import LabelEncoder

In [952]:
#import final dataset

new_main_2017 = pd.read_csv('data/ml_2017_ED.csv', low_memory=False)
print("The data has a size of {}".format(new_main_2017.shape))

The data has a size of (904999, 215)


In [953]:
new_main_2017.drop(['Unnamed: 0'], axis=1, inplace = True)

In [954]:
len(new_main_2017[new_main_2017['is_excluded'] == 1])

101

In [955]:
dropIndex = new_main_2017[new_main_2017['is_excluded'] == 1].index

In [956]:
len(new_main_2017[new_main_2017['is_excluded'] == 0])

904898

In [957]:
only_excluded = new_main_2017[new_main_2017['is_excluded'] == 1]
new_main_2017.drop(dropIndex, inplace = True)
new_main_2017 = new_main_2017.sample(frac=1)
random_sample = new_main_2017.iloc[0:45000]
new_df = pd.concat([only_excluded, random_sample])
new_main_2017 = new_main_2017.drop(new_main_2017.iloc[0:45000].index, axis = 0)
new_df = new_df.sample(frac=1)
#part_d_df.iloc[0:85000].index

In [958]:
new_df.shape

(45101, 214)

In [959]:
new_df[new_df["is_excluded"]==1].shape

(101, 214)

In [960]:
#new_df.drop(['Unnamed: 0'], axis=1, inplace = True)
new_df.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
312406                     360.00                        1               0.0   
483015                     575.78                        1               1.1   
488107                    3432.42                      198              32.0   
247771                     715.17                       11               2.1   
603592                     431.42                        4               2.1   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
312406                 20               22              20.0            22.0   
483015                  0                0               0.0             0.0   
488107                 20               69              20.0            69.0   
247771                  0                0               0.0             0.0   
603592                  0                0               0.0             0.0   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
312406             31.94                  31.94                   0.00  ...   
483015             15.05                   0.00                   0.00  ...   
488107             52.76                  52.74                  32.31  ...   
247771             15.12                  15.74                   2.10  ...   
603592             19.19                  18.78                   0.00  ...   

        x0_Technician  x0_Technician/Technologist  x0_Thoracic Surgery  \
312406            0.0                         0.0                  0.0   
483015            0.0                         0.0                  0.0   
488107            0.0                         0.0                  0.0   
247771            0.0                         0.0                  0.0   
603592            0.0                         0.0                  0.0   

        x0_Thoracic Surgery (Cardiothoracic Vascular Surgery)  \
312406                                                0.0       
483015                                                0.0       
488107                                                0.0       
247771                                                0.0       
603592                                                0.0       

        x0_Undefined Physician type  x0_Unknown Supplier/Provider Specialty  \
312406                          0.0                                     0.0   
483015                          0.0                                     0.0   
488107                          0.0                                     0.0   
247771                          0.0                                     0.0   
603592                          0.0                                     0.0   

        x0_Urology  x0_Vascular Surgery  x0_Veterinarian  \
312406         0.0                  0.0              0.0   
483015         0.0                  0.0              0.0   
488107         0.0                  0.0              0.0   
247771         0.0                  0.0              0.0   
603592         0.0                  0.0              0.0   

        x0_Voluntary Health or Charitable Agency  
312406                                       0.0  
483015                                       0.0  
488107                                       0.0  
247771                                       0.0  
603592                                       0.0  

[5 rows x 214 columns]

In [961]:
new_main_2017.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count               8.598980e+05            859898.000000     859898.000000   
mean                2.208292e+03                25.551911          6.393863   
std                 5.577477e+03                40.579043          7.120737   
min                 0.000000e+00                 0.000000          0.000000   
25%                 1.670600e+02                 2.000000          1.900000   
50%                 6.751750e+02                 7.000000          3.600000   
75%                 2.372338e+03                29.000000          8.300000   
max                 1.713038e+06               394.000000        307.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      859898.000000    859898.000000     859898.000000   859898.000000   
mean           12.573596        38.934385         12.354396       38.876066   
std            16.515220        37.128926         15.883274       36.904866   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        42.000000         10.000000       43.000000   
75%            20.000000        73.000000         20.000000       73.000000   
max           100.000000       100.000000        100.000000      100.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     859898.000000          859898.000000          859898.000000  ...   
mean         125.527621             102.910113               4.792052  ...   
std          548.149234             367.340633               6.858154  ...   
min            0.000000               0.000000               0.000000  ...   
25%           23.520000              13.960000               0.000000  ...   
50%           55.060000              46.550000               2.220000  ...   
75%           93.320000              79.940000               6.530000  ...   
max       171279.730000           76223.890000             270.000000  ...   

       x0_Technician  x0_Technician/Technologist  x0_Thoracic Surgery  \
count  859898.000000               859898.000000        859898.000000   
mean        0.000001                    0.000001             0.001277   
std         0.001078                    0.001078             0.035711   
min         0.000000                    0.000000             0.000000   
25%         0.000000                    0.000000             0.000000   
50%         0.000000                    0.000000             0.000000   
75%         0.000000                    0.000000             0.000000   
max         1.000000                    1.000000             1.000000   

       x0_Thoracic Surgery (Cardiothoracic Vascular Surgery)  \
count                                      859898.000000       
mean                                            0.000077       
std                                             0.008761       
min                                             0.000000       
25%                                             0.000000       
50%                                             0.000000       
75%                                             0.000000       
max                                             1.000000       

       x0_Undefined Physician type  x0_Unknown Supplier/Provider Specialty  \
count                859898.000000                           859898.000000   
mean                      0.000327                                0.000003   
std                       0.018074                                0.001868   
min                       0.000000                                0.000000   
25%                       0.000000                                0.000000   
50%                       0.000000                                0.000000   
75%                       0.000000                                0.000000   
max                  

In [962]:
import math

In [963]:
from sklearn import decomposition
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, auc
from sklearn.utils import resample
from sklearn.preprocessing import label_binarize
from sklearn.svm import SVC
from scipy.stats import pointbiserialr

In [964]:
#part_d_excluded = new_df[new_df["is_excluded"]==1]

fudge = resample(only_excluded, replace=True, n_samples=1000000, random_state = 0)
#fudge.drop(['Unnamed: 0'], axis=1, inplace = True)
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count             1000000.000000           1000000.000000    1000000.000000   
mean                 5194.967630                38.609067          9.485671   
std                 28249.745002                55.813583          9.620971   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count     1000000.000000   1000000.000000    1000000.000000  1000000.000000   
mean           11.374050        36.234950         10.876360       36.026284   
std            14.980311        36.168503         12.989995       35.937057   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count    1000000.000000         1000000.000000         1000000.000000  ...   
mean         105.511338              89.082136               7.510315  ...   
std          175.287247             164.542628               9.325134  ...   
min            2.940000               0.000000               0.000000  ...   
25%           44.060000              28.760000               0.000000  ...   
50%           72.230000              53.450000               3.780000  ...   
75%          104.190000              79.820000              11.630000  ...   
max         1419.570000            1258.960000              43.550000  ...   

       x0_Technician  x0_Technician/Technologist  x0_Thoracic Surgery  \
count      1000000.0                   1000000.0            1000000.0   
mean             0.0                         0.0                  0.0   
std              0.0                         0.0                  0.0   
min              0.0                         0.0                  0.0   
25%              0.0                         0.0                  0.0   
50%              0.0                         0.0                  0.0   
75%              0.0                         0.0                  0.0   
max              0.0                         0.0                  0.0   

       x0_Thoracic Surgery (Cardiothoracic Vascular Surgery)  \
count                                          1000000.0       
mean                                                 0.0       
std                                                  0.0       
min                                                  0.0       
25%                                                  0.0       
50%                                                  0.0       
75%                                                  0.0       
max                                                  0.0       

       x0_Undefined Physician type  x0_Unknown Supplier/Provider Specialty  \
count                    1000000.0                               1000000.0   
mean                           0.0                                     0.0   
std                            0.0                                     0.0   
min                            0.0                                     0.0   
25%                            0.0                                     0.0   
50%                            0.0                                     0.0   
75%                            0.0                                     0.0   
max                  

In [965]:
std = fudge.describe().loc["std"]
std = std[0:26]

In [966]:
rtstd = std.map(lambda x : math.sqrt(x)/2) #use half of square root of standard deviation as the range for gaussian normal
rtstd = rtstd.to_dict()

In [967]:
for key in rtstd:
    #fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, rtstd[key])))
    fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, 2)))
fudge = fudge[fudge>=0]
fudge.dropna(inplace = True)

In [968]:
rtstd

{'t_cost_per_claim_excluded': 84.03830228283725,
 't_claim_count_schedule2': 3.735424432090368,
 't_claim_per_bene': 1.5508844893809823,
 '%b2bg_claim_count': 1.9352203219559672,
 '%b2bg_drug_cost': 3.007012758064355,
 '%b2t_claim_count': 1.802081760350314,
 '%b2t_drug_cost': 2.99737621069871,
 't_cost_per_claim': 6.619804500549423,
 't_cost_per_claim_ge65': 6.413708518062818,
 't_claim_per_bene_ge65': 1.5268541048291235,
 'mapd_cost_per_claim': 6.461408506432181,
 'pdp_cost_per_claim': 6.725735816482665,
 'lis_cost_per_claim': 6.822596052308591,
 'nonlis_cost_per_claim': 6.207153722441226,
 'opioid_cost_per_claim': 4.650466862010797,
 'opioid_claim_per_bene': 0.884740725108428,
 'antibiotic_cost_per_claim': 2.981750867470343,
 'antibiotic_claim_per_bene': 0.47019428185377854,
 'antipsych_cost_per_claim_ge65': 4.626473486567583,
 'antipsych_claim_per_bene_ge65': 0.6299808071079215,
 'total_30_day_fill_count': 37.12751686106159,
 'total_day_supply': 197.95167898077315,
 'total_30_day_fi

In [969]:
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count               88281.000000             88281.000000      88281.000000   
mean                 3747.745133               125.434456         21.629325   
std                  3269.923129                77.738069         10.654792   
min                    40.581854                 0.040886          0.001187   
25%                  1820.027629                63.406462         14.537087   
50%                  3007.428370               119.578493         19.875231   
75%                  4194.375358               153.856141         25.203185   
max                286887.199536               306.192027         52.961321   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count       88281.000000     88281.000000      88281.000000    88281.000000   
mean           17.854085        66.872532         17.835089       66.384547   
std             6.817487        12.444216          6.820129       12.471399   
min             0.000229         0.003683          0.002632        0.002952   
25%            11.661222        64.337976         11.631126       64.071378   
50%            19.090495        69.197625         19.083683       68.923785   
75%            21.329298        73.598983         21.327016       72.997830   
max           101.262303       103.344559         64.538281      104.246521   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count      88281.000000           88281.000000           88281.000000  ...   
mean          83.326128              76.263445              20.714751  ...   
std           56.145210              49.456262              10.868217  ...   
min            0.590797               0.376323               0.005793  ...   
25%           52.368257              46.604592              13.645851  ...   
50%           66.808808              58.490087              18.822920  ...   
75%          102.559949              95.114346              24.974830  ...   
max         1418.569429            1258.419274              52.877148  ...   

       x0_Technician  x0_Technician/Technologist  x0_Thoracic Surgery  \
count        88281.0                     88281.0              88281.0   
mean             0.0                         0.0                  0.0   
std              0.0                         0.0                  0.0   
min              0.0                         0.0                  0.0   
25%              0.0                         0.0                  0.0   
50%              0.0                         0.0                  0.0   
75%              0.0                         0.0                  0.0   
max              0.0                         0.0                  0.0   

       x0_Thoracic Surgery (Cardiothoracic Vascular Surgery)  \
count                                            88281.0       
mean                                                 0.0       
std                                                  0.0       
min                                                  0.0       
25%                                                  0.0       
50%                                                  0.0       
75%                                                  0.0       
max                                                  0.0       

       x0_Undefined Physician type  x0_Unknown Supplier/Provider Specialty  \
count                      88281.0                                 88281.0   
mean                           0.0                                     0.0   
std                            0.0                                     0.0   
min                            0.0                                     0.0   
25%                            0.0                                     0.0   
50%                            0.0                                     0.0   
75%                            0.0                                     0.0   
max                  

In [970]:
only_excluded.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count                 101.000000               101.000000        101.000000   
mean                 5221.393465                38.673267          9.499010   
std                 28518.834547                56.116684          9.667021   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count         101.000000       101.000000        101.000000      101.000000   
mean           11.386139        36.306931         10.891089       36.099010   
std            15.035272        36.333935         13.045996       36.102771   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count        101.000000             101.000000             101.000000  ...   
mean         105.625248              89.195347               7.519802  ...   
std          176.536412             165.641181               9.375172  ...   
min            2.940000               0.000000               0.000000  ...   
25%           44.060000              28.760000               0.000000  ...   
50%           72.230000              53.450000               3.780000  ...   
75%          104.190000              79.820000              11.630000  ...   
max         1419.570000            1258.960000              43.550000  ...   

       x0_Technician  x0_Technician/Technologist  x0_Thoracic Surgery  \
count          101.0                       101.0                101.0   
mean             0.0                         0.0                  0.0   
std              0.0                         0.0                  0.0   
min              0.0                         0.0                  0.0   
25%              0.0                         0.0                  0.0   
50%              0.0                         0.0                  0.0   
75%              0.0                         0.0                  0.0   
max              0.0                         0.0                  0.0   

       x0_Thoracic Surgery (Cardiothoracic Vascular Surgery)  \
count                                              101.0       
mean                                                 0.0       
std                                                  0.0       
min                                                  0.0       
25%                                                  0.0       
50%                                                  0.0       
75%                                                  0.0       
max                                                  0.0       

       x0_Undefined Physician type  x0_Unknown Supplier/Provider Specialty  \
count                        101.0                                   101.0   
mean                           0.0                                     0.0   
std                            0.0                                     0.0   
min                            0.0                                     0.0   
25%                            0.0                                     0.0   
50%                            0.0                                     0.0   
75%                            0.0                                     0.0   
max                  

In [971]:
fudge.shape

(88281, 214)

In [972]:
fudge=fudge.sample(n=10000)
fudge.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
235793                3757.537601               137.212854         27.700654   
603391                1009.169823                63.091539         10.652017   
15591                 5734.372180               178.160264         18.985526   
644968                2604.965748               155.185270         15.314054   
664035                1206.313386                75.023475         21.136299   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
235793          19.575717        73.050063         17.725569       69.180630   
603391          21.058391        73.211929         19.748291       70.978407   
15591           19.485741        75.751471         16.964015       74.883987   
644968           8.998308        65.285045          7.754750       64.248823   
664035           9.025529        53.524799         12.304987       50.092747   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
235793         51.252484              52.462136              22.012217  ...   
603391         48.212959              53.237440               9.154770  ...   
15591         102.942107              94.869710              19.728961  ...   
644968         79.958981              79.175419              14.103589  ...   
664035         34.247355              31.449229              17.758831  ...   

        x0_Technician  x0_Technician/Technologist  x0_Thoracic Surgery  \
235793            0.0                         0.0                  0.0   
603391            0.0                         0.0                  0.0   
15591             0.0                         0.0                  0.0   
644968            0.0                         0.0                  0.0   
664035            0.0                         0.0                  0.0   

        x0_Thoracic Surgery (Cardiothoracic Vascular Surgery)  \
235793                                                0.0       
603391                                                0.0       
15591                                                 0.0       
644968                                                0.0       
664035                                                0.0       

        x0_Undefined Physician type  x0_Unknown Supplier/Provider Specialty  \
235793                          0.0                                     0.0   
603391                          0.0                                     0.0   
15591                           0.0                                     0.0   
644968                          0.0                                     0.0   
664035                          0.0                                     0.0   

        x0_Urology  x0_Vascular Surgery  x0_Veterinarian  \
235793         0.0                  0.0              0.0   
603391         0.0                  0.0              0.0   
15591          0.0                  0.0              0.0   
644968         0.0                  0.0              0.0   
664035         0.0                  0.0              0.0   

        x0_Voluntary Health or Charitable Agency  
235793                                       0.0  
603391                                       0.0  
15591                                        0.0  
644968                                       0.0  
664035                                       0.0  

[5 rows x 214 columns]

In [973]:
ag_2017 = pd.concat([new_main_2017, fudge])
ag_2017.dropna(inplace=True)

In [974]:
ag_2017[ag_2017["is_excluded"]==1].shape

(10000, 214)

In [975]:
ag_2017.shape

(869898, 214)

#Applying PCA, 2 components and 3 components for variance visualization

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_), color='r')

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_cross_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

plt.vlines(1, color='grey', ymax=0.1, ymin=0, linestyle=':')
plt.vlines(2, color='grey', ymax=0.1, ymin=0, linestyle=':')

plt.annotate('1 components', xy=(0.6, 0.05), xytext=(0.9, 0.05), fontsize=15, rotation=90)
plt.annotate('2 components', xy=(1.6, 0.05), xytext=(1.9, 0.05), fontsize=15, rotation=90)

plt.savefig('VarExp.jpeg', dpi=1000)
plt.tight_layout()
plt.show()

In [976]:
#Training without Upsampling or Downsampling
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017.drop(['is_excluded'], axis=1)
y_train = ag_2017['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X = new_main_2017.drop(['is_excluded'], axis=1)
#y = new_main_2017['is_excluded']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [977]:
#pca = decomposition.PCA(n_components='mle')
#X_train = pca.fit_transform(X_train)
#X_test = pca.fit_transform(X_test)

In [978]:
#print(pca.explained_variance_ratio_)

In [979]:
Labels = ag_2017.drop(["is_excluded"],axis = 1).columns

In [980]:
#new Labels after PCA
#most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
#most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
#dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
#newLabels = list(dic.values())
#newLabels

In [981]:
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [982]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [983]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [984]:
clf.feature_importances_

array([2.88889046e-02, 4.23470972e-02, 2.02675777e-02, 7.42631749e-02,
       1.45590495e-02, 5.11252490e-02, 1.59181648e-02, 1.97333898e-02,
       2.19978780e-02, 2.42101890e-02, 1.77825889e-02, 1.39430596e-02,
       2.01129237e-02, 1.97935239e-02, 3.06445362e-02, 1.66279052e-02,
       3.97384541e-02, 4.08705569e-02, 6.03980620e-02, 1.37851897e-01,
       3.33215019e-02, 4.71181840e-02, 5.58998754e-02, 4.68484560e-02,
       4.44275941e-02, 2.58138870e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.26024142e-07,
       0.00000000e+00, 4.06619299e-09, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.50517373e-06, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.89754401e-06, 0.00000000e+00,
       2.13585575e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.62858814e-04, 0.00000000e+00, 7.08370711e-07,
      

coef_df = pd.DataFrame(clf.feature_importances_, Labels, columns = ["Importances"])
coef_df.sort_values("Importances", ascending = False)

check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [985]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(y_pred_prob)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

[[1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]
 ...
 [0.04 0.96]
 [0.   1.  ]
 [0.   1.  ]]
1.0


array([[859898,      0],
       [     0,  10000]], dtype=int64)

In [986]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(y_pred_prob)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.7308545654565457


array([[45000,     0],
       [   94,     7]], dtype=int64)

In [987]:
#Upsampling only

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Increase by 10 times
ag_2017_minority_upsampled = resample(ag_2017_minority, replace=True, n_samples=100000, random_state=42) 
ag_2017_upsampled = pd.concat([ag_2017_majority, ag_2017_minority_upsampled])  
ag_2017_upsampled['is_excluded'].value_counts()

0    859898
1    100000
Name: is_excluded, dtype: int64

In [988]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_upsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_upsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [989]:
#pca = decomposition.PCA(n_components='mle')
#X_train = pca.fit_transform(X_train)
#X_test = pca.fit_transform(X_test)

In [990]:
#print(pca.explained_variance_ratio_)

In [991]:
#Labels = df.drop(["is_excluded"],axis = 1).columns

In [992]:
#new Labels after PCA
#most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
#most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
#dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
#newLabels = list(dic.values())
#newLabels

In [993]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [994]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [995]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

100000


In [996]:
clf.feature_importances_

array([1.14569816e-02, 2.53026904e-02, 1.42149507e-02, 3.47206269e-02,
       9.37259044e-03, 3.80489982e-02, 1.11290928e-02, 9.85964417e-03,
       6.43729170e-03, 5.63225953e-02, 1.42624163e-02, 1.68635900e-02,
       9.29483154e-03, 1.31640383e-02, 2.96477040e-02, 3.58533768e-02,
       1.68205676e-02, 2.58207136e-02, 7.46478779e-02, 3.03155064e-01,
       3.55002693e-02, 3.69646298e-02, 3.11013020e-02, 2.59267541e-02,
       6.76268167e-02, 1.40780669e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.52739483e-06, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 5.38783043e-06, 0.00000000e+00,
       3.59601863e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.70685538e-05, 0.00000000e+00, 1.45258624e-06,
      

#check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [997]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[859898,      0],
       [     0, 100000]], dtype=int64)

In [998]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.6816496149614961


array([[45000,     0],
       [   96,     5]], dtype=int64)

In [999]:
#Training on downsampled only and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Reduce by 10 times
ag_2017_majority_downsampled = resample(ag_2017_majority, replace=True, n_samples=81980, random_state=42) 
ag_2017_downsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority]) 
ag_2017_downsampled['is_excluded'].value_counts()

0    81980
1    10000
Name: is_excluded, dtype: int64

In [1000]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_downsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_downsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [1001]:
#pca = decomposition.PCA(n_components='mle')
#X_train = pca.fit_transform(X_train)
#X_test = pca.fit_transform(X_test)

In [1002]:
#print(pca.explained_variance_ratio_)

In [1003]:
#Labels = df.drop(["is_excluded"],axis = 1).columns

In [1004]:
#new Labels after PCA
#most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
#most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
#dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
#newLabels = list(dic.values())
#newLabels

In [1005]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [1006]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x) == 1:
        count +=1
print(count)

101


In [1007]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [1008]:
clf.feature_importances_

array([2.83441006e-02, 1.92625956e-02, 3.39764189e-02, 3.39828079e-02,
       9.73316444e-03, 3.43743622e-02, 1.29753499e-02, 1.46279704e-02,
       1.36398115e-02, 4.61035153e-02, 1.73574093e-02, 1.12321780e-02,
       1.58327391e-02, 1.05983743e-02, 2.92223949e-02, 2.25418749e-02,
       1.87322411e-02, 5.68183862e-02, 6.39483264e-02, 2.30259872e-01,
       5.44441814e-02, 3.87492361e-02, 3.91656446e-02, 2.11314339e-02,
       6.94254851e-02, 1.42598908e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 8.28646047e-10, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 4.98887597e-06, 0.00000000e+00,
       3.53291516e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 7.71383243e-05, 0.00000000e+00, 1.78554101e-05,
      

#check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [1009]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[81980,     0],
       [    0, 10000]], dtype=int64)

In [1010]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.6967899889989


array([[45000,     0],
       [   96,     5]], dtype=int64)

In [1011]:
#Upsampling/downsampling on training and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

ag_2017_updownsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority_upsampled]) 
ag_2017_updownsampled['is_excluded'].value_counts()

1    100000
0     81980
Name: is_excluded, dtype: int64

In [1012]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017_updownsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_updownsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [1013]:
#pca = decomposition.PCA(n_components='mle')
#X_train = pca.fit_transform(X_train)
#X_test = pca.fit_transform(X_test)

In [1014]:
#print(pca.explained_variance_ratio_)

In [1015]:
#Labels = df.drop(["is_excluded"],axis = 1).columns

In [1016]:
#new Labels after PCA
#most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
#most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
#dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
#newLabels = list(dic.values())
#newLabels

In [1017]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [1018]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [1019]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

100000


In [1020]:
clf.feature_importances_

array([3.74039808e-02, 2.46856831e-02, 2.63192231e-02, 2.42197702e-02,
       7.66672423e-03, 2.07871093e-02, 1.63440115e-02, 4.30809628e-03,
       1.10724453e-02, 3.65096987e-02, 2.04375486e-02, 1.82263831e-02,
       3.31764951e-03, 2.13220605e-02, 1.95423383e-02, 2.22099942e-02,
       2.94877396e-02, 3.96808028e-02, 9.41842295e-02, 2.31707762e-01,
       8.50136019e-02, 5.37605267e-02, 2.91085145e-02, 9.89096097e-03,
       6.44001709e-02, 2.98395741e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.41615244e-06, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.79128007e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.79210884e-04, 0.00000000e+00, 1.37700850e-05,
      

#check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [1021]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[ 81980,      0],
       [     0, 100000]], dtype=int64)

In [1022]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.717469196919692


array([[45000,     0],
       [   96,     5]], dtype=int64)

In conclusion, results from downsampling is the best.