In [33]:
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook, tqdm

In [34]:
new_main_2017 = pd.read_csv('data/ml_2017.csv', low_memory=False)
print("The data has a size of {}".format(new_main_2017.shape))

The data has a size of (904999, 32)


In [35]:
new_main_2017.head(1)

Unnamed: 0         npi specialty_description nppes_provider_state  \
0           0  1023417649     Internal Medicine                   PA   

   t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     512.29                       14               2.7   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  ...  \
0                0.0              0.0               0.0  ...   

   antipsych_cost_per_claim_ge65  antipsych_claim_per_bene_ge65  \
0                            0.0                            0.0   

   total_30_day_fill_count  total_day_supply  total_30_day_fill_count_ge65  \
0                    605.0             13547                         533.9   

   total_day_supply_ge65  opioid_day_supply  opioid_prescriber_rate  \
0                12009.0                0.0                     0.0   

   is_excluded       year  
0            0  2017-2018  

[1 rows x 32 columns]

In [36]:
new_main_2017.drop(['Unnamed: 0'], axis=1, inplace = True)

In [37]:
new_main_2017.drop(['npi', 'specialty_description','nppes_provider_state','year'], axis=1, inplace = True)

In [38]:
new_main_2017.head(1)

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     512.29                       14               2.7   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
0                0.0              0.0               0.0             0.0   

   t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
0            6966.0                 5285.0                  269.0  ...   

   antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
0                      116.0                            0.0   

   antipsych_claim_per_bene_ge65  total_30_day_fill_count  total_day_supply  \
0                            0.0                    605.0             13547   

   total_30_day_fill_count_ge65  total_day_supply_ge65  opioid_day_supply  \
0                         533.9                12009.0                0.0   

   opioid_prescriber_rate  is_excluded  
0                     0.0            0  

[1 rows x 27 columns]

In [39]:
len(new_main_2017[new_main_2017['is_excluded'] == 1])

101

In [40]:
dropIndex = new_main_2017[new_main_2017['is_excluded'] == 1].index

In [41]:
len(new_main_2017[new_main_2017['is_excluded'] == 0])

904898

In [42]:
only_excluded = new_main_2017[new_main_2017['is_excluded'] == 1]
new_main_2017.drop(dropIndex, inplace = True)
new_main_2017 = new_main_2017.sample(frac=1)
random_sample = new_main_2017.iloc[0:85000]
new_df = pd.concat([only_excluded, random_sample])
new_main_2017 = new_main_2017.drop(new_main_2017.iloc[0:85000].index, axis = 0)
new_df = new_df.sample(frac=1)
#part_d_df.iloc[0:85000].index

In [43]:
#new_df.drop(['Unnamed: 0'], axis=1, inplace = True)
new_df.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
297787                     107.31                        8               1.7   
644611                    1011.83                       50               8.3   
608194                     860.27                        7               7.2   
891615                    1584.81                        1               0.0   
87009                     4852.07                       25               7.2   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
297787                0.0              0.0               0.0             0.0   
644611               20.0             57.0              20.0            56.0   
608194                0.0              0.0               0.0             0.0   
891615                0.0              0.0               0.0             0.0   
87009                20.0             75.0              20.0            75.0   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
297787             693.0                  683.0                  158.0  ...   
644611            4455.0                 4388.0                  793.0  ...   
608194            6298.0                 6491.0                    0.0  ...   
891615            9684.0                    0.0                    0.0  ...   
87009             6442.0                 5872.0                  671.0  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
297787                      126.0                            0.0   
644611                      140.0                            0.0   
608194                        0.0                         3819.0   
891615                        0.0                            0.0   
87009                       227.0                            0.0   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
297787                            0.0                    278.0   
644611                            0.0                   6575.6   
608194                            0.0                    300.8   
891615                            0.0                     17.0   
87009                             0.0                   3462.9   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
297787              1843                         133.0                 1034.0   
644611            191506                        6148.4               179745.0   
608194              6740                         289.8                 6428.0   
891615               416                           0.0                    0.0   
87009              96560                        2747.0                76910.0   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
297787              240.0                   29.86            0  
644611             2006.0                    3.46            0  
608194                0.0                    0.00            0  
891615                0.0                    0.00            0  
87009                 0.0                    0.00            0  

[5 rows x 27 columns]

In [44]:
new_main_2017.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count               8.198980e+05            819898.000000     819898.000000   
mean                2.209397e+03                25.571760          6.395758   
std                 5.697890e+03                40.619923          7.124802   
min                 0.000000e+00                 0.000000          0.000000   
25%                 1.670400e+02                 2.000000          1.900000   
50%                 6.754350e+02                 7.000000          3.600000   
75%                 2.372575e+03                29.000000          8.300000   
max                 1.713038e+06               394.000000        307.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      819898.000000    819898.000000     819898.000000   819898.000000   
mean           12.580431        38.951690         12.361099       38.894972   
std            16.518460        37.128341         15.885783       36.904146   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        42.000000         10.000000       43.000000   
75%            20.000000        73.000000         20.000000       73.000000   
max           100.000000       100.000000        100.000000      100.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count      8.198980e+05           8.198980e+05          819898.000000  ...   
mean       1.255493e+04           1.030051e+04             479.508627  ...   
std        5.510932e+04           3.684677e+04             686.952454  ...   
min        0.000000e+00           0.000000e+00               0.000000  ...   
25%        2.354000e+03           1.396000e+03               0.000000  ...   
50%        5.504000e+03           4.654000e+03             222.000000  ...   
75%        9.329000e+03           7.989750e+03             652.000000  ...   
max        1.712797e+07           7.622389e+06           27000.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              819898.000000                  819898.000000   
mean                   92.354290                    1388.965754   
std                    82.658339                    7006.366784   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                   113.000000                       0.000000   
75%                   143.000000                       0.000000   
max                  3422.000000                  479253.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  819898.000000            819898.000000   
mean                       28.261118              2511.452801   
std                       144.304301              5142.801557   
min                         0.000000                11.000000   
25%                         0.000000               141.000000   
50%                         0.000000               445.200000   
75%                         0.000000              2269.175000   
max                      6007.000000            447960.500000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      8.198980e+05                 819898.000000           8.198980e+05   
mean       6.982174e+04                   2035.361320           5.690062e+04   
std        1.441068e+05                   4463.190532           1.254358e+05   
min        1.100000e+01                      0.000000           0.000000e+00   
25%        2.164000e+03                     72.100000           9.720000e+02   
50%        1.028700e+04                    298.200000           6.695000e+03   
75%        6.289150e+04                   1611.675000           4.444700e+04   
max        5.634058e+06                 379751.000

In [45]:
import math

In [46]:
from sklearn import decomposition
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, auc
from sklearn.utils import resample
from sklearn.preprocessing import label_binarize
from sklearn.svm import SVC
from scipy.stats import pointbiserialr

In [47]:
#part_d_excluded = new_df[new_df["is_excluded"]==1]

fudge = resample(only_excluded, replace=True, n_samples=1000000, random_state = 0)
#fudge.drop(['Unnamed: 0'], axis=1, inplace = True)
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count             1000000.000000           1000000.000000    1000000.000000   
mean                 5194.967630                38.609067          9.485671   
std                 28249.745002                55.813583          9.620971   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count     1000000.000000   1000000.000000    1000000.000000  1000000.000000   
mean           11.374050        36.234950         10.876360       36.026284   
std            14.980311        36.168503         12.989995       35.937057   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count    1000000.000000         1000000.000000         1000000.000000  ...   
mean       10551.133795            8908.213605             751.031469  ...   
std        17528.724650           16454.262782             932.513383  ...   
min          294.000000               0.000000               0.000000  ...   
25%         4406.000000            2876.000000               0.000000  ...   
50%         7223.000000            5345.000000             378.000000  ...   
75%        10419.000000            7982.000000            1163.000000  ...   
max       141957.000000          125896.000000            4355.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count             1000000.000000                 1000000.000000   
mean                   77.438471                    2743.050558   
std                    88.433065                    8561.702769   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   157.000000                     633.000000   
max                   322.000000                   50758.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                 1000000.000000           1000000.000000   
mean                       43.789287              3131.733322   
std                       158.750327              5513.810033   
min                         0.000000                13.000000   
25%                         0.000000               109.000000   
50%                         0.000000               632.600000   
75%                         0.000000              3164.200000   
max                       803.000000             33073.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count    1000000.000000                1000000.000000         1000000.000000   
mean       88423.346199                   2090.284659           59364.759391   
std       156739.468845                   4178.857341          118866.398677   
min          221.000000                      0.000000               0.000000   
25%         2955.000000                     62.000000            1280.000000   
50%        18369.000000                    368.400000           10843.000000   
75%        90194.000000                   1882.600000           52000.000000   
max       934916.000000                  22770.800

In [48]:
std = fudge.describe().loc["std"]
std = std[0:26]

In [49]:
rtstd = std.map(lambda x : math.sqrt(x)/2) #use half of square root of standard deviation as the range for gaussian normal
rtstd = rtstd.to_dict()

In [50]:
for key in rtstd:
    #fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, rtstd[key])))
    fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, 2)))
fudge = fudge[fudge>=0]
fudge.dropna(inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [51]:
rtstd

{'t_cost_per_claim_excluded': 84.03830228283725,
 't_claim_count_schedule2': 3.735424432090368,
 't_claim_per_bene': 1.5508844893809823,
 '%b2bg_claim_count': 1.9352203219559672,
 '%b2bg_drug_cost': 3.007012758064355,
 '%b2t_claim_count': 1.802081760350314,
 '%b2t_drug_cost': 2.99737621069871,
 't_cost_per_claim': 66.19804500548426,
 't_cost_per_claim_ge65': 64.13708518052151,
 't_claim_per_bene_ge65': 15.268541048298102,
 'mapd_cost_per_claim': 64.61408506431768,
 'pdp_cost_per_claim': 67.25735816485223,
 'lis_cost_per_claim': 68.22596052313033,
 'nonlis_cost_per_claim': 62.07153722436618,
 'opioid_cost_per_claim': 46.504668620058595,
 'opioid_claim_per_bene': 8.847407251096762,
 'antibiotic_cost_per_claim': 29.817508674809556,
 'antibiotic_claim_per_bene': 4.701942818546453,
 'antipsych_cost_per_claim_ge65': 46.26473486591827,
 'antipsych_claim_per_bene_ge65': 6.299808071086247,
 'total_30_day_fill_count': 37.12751686106159,
 'total_day_supply': 197.95167898077315,
 'total_30_day_fil

In [52]:
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              114622.000000            114622.000000     114622.000000   
mean                 3602.969559               121.901658         21.031840   
std                  3117.035020                76.030301         10.513412   
min                    41.900375                 0.002324          0.001408   
25%                  1819.196539                62.556297         14.024704   
50%                  2713.379803               117.695094         19.579685   
75%                  4191.540625               152.224358         24.774101   
max                286887.451425               306.913061         53.851171   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      114622.000000    114622.000000     114622.000000   114622.000000   
mean           17.624841        66.621965         17.625948       66.132175   
std             6.728363        12.613858          6.733981       12.619541   
min             0.000005         0.000335          0.000550        0.001690   
25%            11.455060        63.797753         11.478050       63.455250   
50%            18.963433        68.947357         18.975253       68.679309   
75%            21.202202        73.462212         21.212524       72.886967   
max            64.406384       102.945683         64.438949      103.074154   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     114622.000000          114622.000000          114622.000000  ...   
mean        8191.107056            7527.705096            2018.186048  ...   
std         5400.618416            4753.203695            1059.334484  ...   
min          366.269534             368.345807               0.002775  ...   
25%         5312.905817            4754.006890            1418.654990  ...   
50%         5956.975795            5688.010614            1767.902759  ...   
75%        10246.504468            9553.789328            2606.701512  ...   
max       141956.546968          125895.187440            4363.680150  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              114622.000000                  114622.000000   
mean                  168.405030                    8506.569113   
std                    51.573874                   14305.137208   
min                     0.000056                       0.000140   
25%                   157.482380                     754.672491   
50%                   172.300383                    3287.751401   
75%                   209.815001                    4982.156008   
max                   328.162467                   50762.912598   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  114622.000000            114622.000000   
mean                      247.987514             10445.311295   
std                       307.714449              8893.439995   
min                         0.000020                34.417766   
25%                         1.154530              3233.061530   
50%                         3.026954              9283.869231   
75%                       623.028572             13862.122713   
max                       811.423039             33080.540829   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count     114622.000000                 114622.000000          114622.000000   
mean      294465.927656                   7274.268250          205755.499586   
std       251922.643219                   6939.334237          196654.047690   
min          231.356380                     12.502294             219.731061   
25%        91532.400571                   2206.235567           63404.012801   
50%       268680.574462                   5177.430789          147270.932853   
75%       390052.714176                   9289.389705          270398.075516   
max       934924.454048                  22777.887

In [53]:
only_excluded.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count                 101.000000               101.000000        101.000000   
mean                 5221.393465                38.673267          9.499010   
std                 28518.834547                56.116684          9.667021   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count         101.000000       101.000000        101.000000      101.000000   
mean           11.386139        36.306931         10.891089       36.099010   
std            15.035272        36.333935         13.045996       36.102771   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count        101.000000             101.000000             101.000000  ...   
mean       10562.524752            8919.534653             751.980198  ...   
std        17653.641240           16564.118105             937.517232  ...   
min          294.000000               0.000000               0.000000  ...   
25%         4406.000000            2876.000000               0.000000  ...   
50%         7223.000000            5345.000000             378.000000  ...   
75%        10419.000000            7982.000000            1163.000000  ...   
max       141957.000000          125896.000000            4355.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count                 101.000000                     101.000000   
mean                   77.495050                    2757.247525   
std                    88.851182                    8633.955942   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   157.000000                     633.000000   
max                   322.000000                   50758.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                     101.000000               101.000000   
mean                       44.079208              3136.292079   
std                       159.991417              5542.441612   
min                         0.000000                13.000000   
25%                         0.000000               109.000000   
50%                         0.000000               632.600000   
75%                         0.000000              3164.200000   
max                       803.000000             33073.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count        101.000000                    101.000000             101.000000   
mean       88552.960396                   2093.873267           59466.841584   
std       157554.695894                   4202.779267          119551.162208   
min          221.000000                      0.000000               0.000000   
25%         2955.000000                     62.000000            1280.000000   
50%        18369.000000                    368.400000           10843.000000   
75%        90194.000000                   1882.600000           52000.000000   
max       934916.000000                  22770.800

In [54]:
fudge.shape

(114622, 27)

In [55]:
fudge=fudge.sample(n=10000)
fudge.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
524064                2270.278661                61.466141         20.514117   
44316                 4191.113055                29.566353          7.718957   
135853                3335.267448                 8.362670          9.022023   
250232                2056.803424               136.816904         24.040141   
250232                2055.886264               135.716226         18.276672   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
524064          18.206389        68.941691         18.962827       71.206752   
44316           21.263597        73.252182         22.695988       72.160532   
135853          18.197454        72.412914         18.031250       74.333978   
250232          21.023476        67.062726         18.611447       66.874188   
250232          19.092386        68.301992         17.294433       68.608783   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
524064      11313.436305            6202.757955            1466.446691  ...   
44316        5915.161710            4176.826105             816.189716  ...   
135853      12970.948312            6922.509588               1.017477  ...   
250232       5318.414967            4752.670316            2071.069430  ...   
250232       5321.272054            4757.036130            2067.327278  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
524064                 220.252775                       1.731196   
44316                  166.714292                       1.377174   
135853                   1.055160                       1.890315   
250232                 160.520699                    4458.233736   
250232                 157.354584                    4460.298079   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
524064                       2.087379              3126.343014   
44316                        2.213541              2566.287351   
135853                       3.464168               267.743993   
250232                     461.948074              9671.062192   
250232                     460.540017              9667.768459   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
524064      89839.994716                   2202.194902           63399.085681   
44316       63728.317683                    633.562809           16326.118847   
135853       7542.130225                     40.728987             997.335229   
250232     268681.029760                   7810.786149          219080.235410   
250232     268681.068452                   7811.857184          219079.981898   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
524064        5443.459032               11.562675            1  
44316        25235.586282               48.325374            1  
135853        4622.965878               68.935422            1  
250232       10878.165840                6.230274            1  
250232       10876.820785                4.770959            1  

[5 rows x 27 columns]

In [56]:
ag_2017 = pd.concat([new_main_2017, fudge])
ag_2017.dropna(inplace=True)

In [57]:
ag_2017[ag_2017["is_excluded"]==1].shape

(10000, 27)

In [58]:
ag_2017.shape

(829898, 27)

#Applying PCA, 2 components and 3 components for variance visualization

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_), color='r')

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_cross_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

plt.vlines(1, color='grey', ymax=0.1, ymin=0, linestyle=':')
plt.vlines(2, color='grey', ymax=0.1, ymin=0, linestyle=':')

plt.annotate('1 components', xy=(0.6, 0.05), xytext=(0.9, 0.05), fontsize=15, rotation=90)
plt.annotate('2 components', xy=(1.6, 0.05), xytext=(1.9, 0.05), fontsize=15, rotation=90)

plt.savefig('VarExp.jpeg', dpi=1000)
plt.tight_layout()
plt.show()

In [59]:
#Training without Upsampling or Downsampling
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017.drop(['is_excluded'], axis=1)
y_train = ag_2017['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X = new_main_2017.drop(['is_excluded'], axis=1)
#y = new_main_2017['is_excluded']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [60]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [61]:
print(pca.explained_variance_ratio_)

[7.55624846e-01 1.75888228e-01 2.25410162e-02 1.58776591e-02
 1.04282443e-02 5.89805273e-03 5.55271872e-03 3.39409623e-03
 2.01583979e-03 1.06416590e-03 8.18676546e-04 5.22530227e-04
 3.55722779e-04 1.31748643e-05 4.19840119e-06 3.53842574e-07
 2.47372171e-07 1.11584540e-07 5.49614505e-08 5.04209631e-08
 5.30553423e-09 3.01414248e-09 2.68924110e-09 2.37384013e-10
 1.53460003e-10]


In [62]:
Labels = ag_2017.drop(["is_excluded"],axis = 1).columns

In [63]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 'lis_cost_per_claim',
 'mapd_cost_per_claim',
 'nonlis_cost_per_claim',
 'pdp_cost_per_claim',
 't_cost_per_claim',
 'total_day_supply_ge65',
 'nonlis_cost_per_claim',
 'antibiotic_cost_per_claim',
 'opioid_day_supply',
 'antipsych_cost_per_claim_ge65',
 't_cost_per_claim_excluded',
 'opioid_cost_per_claim',
 'total_30_day_fill_count',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 'total_30_day_fill_count_ge65',
 '%b2bg_drug_cost',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2t_drug_cost']

In [64]:
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [65]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [66]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [67]:
clf.feature_importances_

array([0.04922774, 0.02896428, 0.02686408, 0.02074517, 0.02184047,
       0.03194073, 0.08563378, 0.0208111 , 0.01695076, 0.03840078,
       0.04637532, 0.02607229, 0.05426006, 0.02640538, 0.04222551,
       0.02833913, 0.0522174 , 0.03515179, 0.01988627, 0.02478147,
       0.0129427 , 0.0190813 , 0.03762268, 0.01027842, 0.2229814 ])

coef_df = pd.DataFrame(clf.feature_importances_, Labels, columns = ["Importances"])
coef_df.sort_values("Importances", ascending = False)

check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [68]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(y_pred_prob)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
1.0


array([[819898,      0],
       [     2,   9998]], dtype=int64)

In [69]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(y_pred_prob)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.6933726266744321


array([[85000,     0],
       [  100,     1]], dtype=int64)

In [70]:
#Upsampling only

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Increase by 10 times
ag_2017_minority_upsampled = resample(ag_2017_minority, replace=True, n_samples=100000, random_state=42) 
ag_2017_upsampled = pd.concat([ag_2017_majority, ag_2017_minority_upsampled])  
ag_2017_upsampled['is_excluded'].value_counts()

0    819898
1    100000
Name: is_excluded, dtype: int64

In [71]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_upsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_upsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [72]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [73]:
print(pca.explained_variance_ratio_)

[7.55624846e-01 1.75888228e-01 2.25410162e-02 1.58776591e-02
 1.04282443e-02 5.89805273e-03 5.55271872e-03 3.39409623e-03
 2.01583979e-03 1.06416590e-03 8.18676546e-04 5.22530227e-04
 3.55722779e-04 1.31748643e-05 4.19840119e-06 3.53842574e-07
 2.47372171e-07 1.11584540e-07 5.49614505e-08 5.04209631e-08
 5.30553423e-09 3.01414248e-09 2.68924110e-09 2.37384013e-10
 1.53460003e-10]


In [74]:
Labels = ag_2017.drop(["is_excluded"],axis = 1).columns

In [75]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 'lis_cost_per_claim',
 'mapd_cost_per_claim',
 'nonlis_cost_per_claim',
 'pdp_cost_per_claim',
 't_cost_per_claim',
 'total_day_supply_ge65',
 'nonlis_cost_per_claim',
 'antibiotic_cost_per_claim',
 'opioid_day_supply',
 'antipsych_cost_per_claim_ge65',
 't_cost_per_claim_excluded',
 'opioid_cost_per_claim',
 'total_30_day_fill_count',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 'total_30_day_fill_count_ge65',
 '%b2bg_drug_cost',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2t_drug_cost']

In [76]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [77]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [78]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

100000


In [79]:
clf.feature_importances_

array([0.06874497, 0.0264882 , 0.02457834, 0.02186707, 0.10327989,
       0.04318013, 0.01656931, 0.0202053 , 0.01561402, 0.0285029 ,
       0.02629664, 0.02910601, 0.06932389, 0.02777577, 0.02400121,
       0.07851918, 0.05135257, 0.03759006, 0.01299638, 0.01190349,
       0.00785344, 0.0475888 , 0.00835924, 0.00599141, 0.19231179])

In [80]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[819898,      0],
       [     0, 100000]], dtype=int64)

In [81]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.542018520675597


array([[85000,     0],
       [  101,     0]], dtype=int64)

In [82]:
#Training on downsampled only and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Reduce by 10 times
ag_2017_majority_downsampled = resample(ag_2017_majority, replace=True, n_samples=81980, random_state=42) 
ag_2017_downsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority]) 
ag_2017_downsampled['is_excluded'].value_counts()

0    81980
1    10000
Name: is_excluded, dtype: int64

In [83]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_downsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_downsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [84]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [85]:
print(pca.explained_variance_ratio_)

[7.55624846e-01 1.75888228e-01 2.25410162e-02 1.58776591e-02
 1.04282443e-02 5.89805273e-03 5.55271872e-03 3.39409623e-03
 2.01583979e-03 1.06416590e-03 8.18676546e-04 5.22530227e-04
 3.55722779e-04 1.31748643e-05 4.19840119e-06 3.53842574e-07
 2.47372171e-07 1.11584540e-07 5.49614505e-08 5.04209631e-08
 5.30553423e-09 3.01414248e-09 2.68924110e-09 2.37384013e-10
 1.53460003e-10]


In [86]:
Labels = ag_2017.drop(["is_excluded"],axis = 1).columns

In [87]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 'lis_cost_per_claim',
 'mapd_cost_per_claim',
 'nonlis_cost_per_claim',
 'pdp_cost_per_claim',
 't_cost_per_claim',
 'total_day_supply_ge65',
 'nonlis_cost_per_claim',
 'antibiotic_cost_per_claim',
 'opioid_day_supply',
 'antipsych_cost_per_claim_ge65',
 't_cost_per_claim_excluded',
 'opioid_cost_per_claim',
 'total_30_day_fill_count',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 'total_30_day_fill_count_ge65',
 '%b2bg_drug_cost',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2t_drug_cost']

In [88]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [89]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [90]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [91]:
clf.feature_importances_

array([0.04809911, 0.02670161, 0.0224888 , 0.01456178, 0.11102795,
       0.01760979, 0.03626688, 0.01368643, 0.02377026, 0.04213942,
       0.03337352, 0.0277199 , 0.07126094, 0.03895674, 0.03812661,
       0.08614701, 0.05480246, 0.03227302, 0.01663207, 0.01653667,
       0.00985061, 0.04548387, 0.00977167, 0.00505817, 0.15765471])

In [92]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[81980,     0],
       [    1,  9999]], dtype=int64)

In [93]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5780599883517764


array([[84225,   775],
       [  100,     1]], dtype=int64)

In [94]:
#Upsampling/downsampling on training and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

ag_2017_updownsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority_upsampled]) 
ag_2017_updownsampled['is_excluded'].value_counts()

1    100000
0     81980
Name: is_excluded, dtype: int64

In [95]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017_updownsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_updownsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [96]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [97]:
print(pca.explained_variance_ratio_)

[7.55624846e-01 1.75888228e-01 2.25410162e-02 1.58776591e-02
 1.04282443e-02 5.89805273e-03 5.55271872e-03 3.39409623e-03
 2.01583979e-03 1.06416590e-03 8.18676546e-04 5.22530227e-04
 3.55722779e-04 1.31748643e-05 4.19840119e-06 3.53842574e-07
 2.47372171e-07 1.11584540e-07 5.49614505e-08 5.04209631e-08
 5.30553423e-09 3.01414248e-09 2.68924110e-09 2.37384013e-10
 1.53460003e-10]


In [98]:
Labels = ag_2017.drop(["is_excluded"],axis = 1).columns

In [99]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 'lis_cost_per_claim',
 'mapd_cost_per_claim',
 'nonlis_cost_per_claim',
 'pdp_cost_per_claim',
 't_cost_per_claim',
 'total_day_supply_ge65',
 'nonlis_cost_per_claim',
 'antibiotic_cost_per_claim',
 'opioid_day_supply',
 'antipsych_cost_per_claim_ge65',
 't_cost_per_claim_excluded',
 'opioid_cost_per_claim',
 'total_30_day_fill_count',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 'total_30_day_fill_count_ge65',
 '%b2bg_drug_cost',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2t_drug_cost']

In [100]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [101]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [102]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

100000


In [103]:
clf.feature_importances_

array([0.16369178, 0.02236719, 0.15741082, 0.0548665 , 0.02354605,
       0.03439135, 0.05561815, 0.00961526, 0.02339643, 0.01660169,
       0.01857692, 0.05758233, 0.01848202, 0.03919844, 0.01180195,
       0.05084072, 0.02538314, 0.02036149, 0.01310358, 0.08717779,
       0.01394692, 0.03371268, 0.02425228, 0.00123037, 0.02284417])

In [104]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[ 81980,      0],
       [     0, 100000]], dtype=int64)

In [105]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5052888759464181


array([[85000,     0],
       [  101,     0]], dtype=int64)

In conclusion, results from downsampling is the best.