In [3]:
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook, tqdm

In [4]:
new_main_2015 = pd.read_csv('data/ml_2015.csv', low_memory=False)
print("The data has a size of {}".format(new_main_2015.shape))

The data has a size of (853583, 32)


In [5]:
new_main_2015.head(1)

Unnamed: 0         npi specialty_description nppes_provider_state  \
0           0  1033279500    Orthopedic Surgery                   FL   

   t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                      85.69                        2               2.2   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  ...  \
0                0.0              0.0               0.0  ...   

   antipsych_cost_per_claim_ge65  antipsych_claim_per_bene_ge65  \
0                            0.0                            0.0   

   total_30_day_fill_count  total_day_supply  total_30_day_fill_count_ge65  \
0                     54.3               930                           0.0   

   total_day_supply_ge65  opioid_day_supply  opioid_prescriber_rate  \
0                    0.0              364.0                   65.96   

   is_excluded       year  
0            0  2015-2016  

[1 rows x 32 columns]

In [6]:
new_main_2015.drop(['Unnamed: 0'], axis=1, inplace = True)

In [7]:
new_main_2015.drop(['npi', 'specialty_description','nppes_provider_state','year'], axis=1, inplace = True)

In [8]:
new_main_2015.head(1)

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                      85.69                        2               2.2   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
0                0.0              0.0               0.0             0.0   

   t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
0            3624.0                    0.0                    0.0  ...   

   antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
0                        0.0                            0.0   

   antipsych_claim_per_bene_ge65  total_30_day_fill_count  total_day_supply  \
0                            0.0                     54.3               930   

   total_30_day_fill_count_ge65  total_day_supply_ge65  opioid_day_supply  \
0                           0.0                    0.0              364.0   

   opioid_prescriber_rate  is_excluded  
0                   65.96            0  

[1 rows x 27 columns]

In [9]:
len(new_main_2015[new_main_2015['is_excluded'] == 1])

150

In [10]:
dropIndex = new_main_2015[new_main_2015['is_excluded'] == 1].index

In [11]:
len(new_main_2015[new_main_2015['is_excluded'] == 0])

853433

In [12]:
only_excluded = new_main_2015[new_main_2015['is_excluded'] == 1]
new_main_2015.drop(dropIndex, inplace = True)
new_main_2015 = new_main_2015.sample(frac=1)
random_sample = new_main_2015.iloc[0:170567]
new_df = pd.concat([only_excluded, random_sample])
new_main_2015 = new_main_2015.drop(new_main_2015.iloc[0:170567].index, axis = 0)
new_df = new_df.sample(frac=1)
#part_d_df.iloc[0:85000].index

In [13]:
#new_df.drop(['Unnamed: 0'], axis=1, inplace = True)
new_df.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
240106                    2995.78                      145              22.8   
845770                    1757.03                       98              13.7   
9751                       844.94                       29               7.1   
770596                    4376.59                        2               4.3   
453402                     387.31                       11               5.8   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
240106               20.0             73.0              20.0            73.0   
845770               20.0             58.0              20.0            58.0   
9751                 20.0             78.0              20.0            78.0   
770596               10.0             93.0              10.0            93.0   
453402               20.0             67.0              20.0            67.0   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
240106            8219.0                 7475.0                 2348.0  ...   
845770            4603.0                 3884.0                 1303.0  ...   
9751              5974.0                 4823.0                  718.0  ...   
770596           50580.0                53287.0                    0.0  ...   
453402            5724.0                    0.0                    0.0  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
240106                      233.0                        23184.0   
845770                      137.0                            0.0   
9751                        127.0                            0.0   
770596                        0.0                            0.0   
453402                        0.0                            0.0   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
240106                            0.0                  11970.8   
845770                            0.0                   9418.2   
9751                              0.0                   1952.2   
770596                            0.0                    440.3   
453402                            0.0                   1129.7   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
240106            332650                        8707.9               248561.0   
845770            274076                        8700.6               254165.0   
9751               55767                        1305.6                37800.0   
770596             12974                         415.0                12214.0   
453402             33087                           0.0                    0.0   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
240106            14046.0                    8.25            0  
845770             2925.0                    2.39            0  
9751                405.0                    2.28            0  
770596                0.0                    0.00            0  
453402                0.0                    0.00            0  

[5 rows x 27 columns]

In [14]:
new_main_2015.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              682866.000000            682866.000000     682866.000000   
mean                 2009.041913                26.936456          6.675349   
std                  4013.793568                43.008961          7.378996   
min                     0.000000                 0.000000          0.000000   
25%                   184.310000                 2.000000          2.000000   
50%                   789.705000                 8.000000          3.700000   
75%                  2431.967500                30.000000          8.700000   
max                873196.430000               445.000000        285.500000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      682866.000000    682866.000000     682866.000000   682866.000000   
mean           13.910928        38.118086         13.501155       38.023731   
std            18.326862        37.174891         17.043763       36.891228   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        40.000000         10.000000       41.000000   
75%            20.000000        73.000000         20.000000       72.000000   
max           100.000000       100.000000        100.000000      100.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count      6.828660e+05           6.828660e+05          682866.000000  ...   
mean       1.167671e+04           9.573523e+03             504.936431  ...   
std        4.683407e+04           3.729486e+04             718.210685  ...   
min        1.000000e+00           0.000000e+00               0.000000  ...   
25%        2.650000e+03           1.582000e+03               0.000000  ...   
50%        5.497000e+03           4.728000e+03             229.000000  ...   
75%        9.109000e+03           7.858000e+03             687.000000  ...   
max        9.181316e+06           3.741203e+06           18935.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              682866.000000                  682866.000000   
mean                   93.586723                    1891.967149   
std                    84.347597                    7885.206094   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                   113.000000                       0.000000   
75%                   145.000000                       0.000000   
max                  3279.000000                  258910.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  682866.000000            682866.000000   
mean                       28.269713              2419.715746   
std                       144.018960              4910.691032   
min                         0.000000                11.000000   
25%                         0.000000               135.800000   
50%                         0.000000               429.300000   
75%                         0.000000              2193.600000   
max                      6162.000000            197802.400000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      6.828660e+05                 682866.000000           6.828660e+05   
mean       6.716874e+04                   1934.543476           5.402867e+04   
std        1.380300e+05                   4227.887678           1.191695e+05   
min        1.100000e+01                      0.000000           0.000000e+00   
25%        2.105000e+03                     68.000000           9.210000e+02   
50%        9.899000e+03                    277.500000           6.241500e+03   
75%        6.074800e+04                   1520.100000           4.190775e+04   
max        4.189555e+06                 175172.400

In [15]:
import math

In [16]:
from sklearn import decomposition
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, auc
from sklearn.utils import resample
from sklearn.preprocessing import label_binarize
from sklearn.svm import SVC
from scipy.stats import pointbiserialr

In [17]:
#part_d_excluded = new_df[new_df["is_excluded"]==1]

fudge = resample(only_excluded, replace=True, n_samples=1000000, random_state = 0)
#fudge.drop(['Unnamed: 0'], axis=1, inplace = True)
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count             1000000.000000           1000000.000000    1000000.000000   
mean                 2197.433460                40.065730         10.473341   
std                  3154.152633                57.016876         10.917712   
min                    56.190000                 1.000000          0.000000   
25%                   280.010000                 3.000000          2.900000   
50%                  1224.700000                14.000000          6.700000   
75%                  3056.870000                49.000000         13.900000   
max                 28054.360000               250.000000         49.800000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count     1000000.000000    1000000.00000    1000000.000000  1000000.000000   
mean           14.019920         43.96602         13.952790       43.819566   
std            13.020047         34.77013         12.911248       34.648841   
min             0.000000          0.00000          0.000000        0.000000   
25%             0.000000          0.00000          0.000000        0.000000   
50%            10.000000         62.00000         10.000000       62.000000   
75%            20.000000         74.00000         20.000000       74.000000   
max            60.000000         97.00000         60.000000       97.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count    1000000.000000         1000000.000000         1000000.000000  ...   
mean        8353.638053            7689.931352             822.089077  ...   
std         6594.110247            9049.060428            1052.090253  ...   
min          576.000000               0.000000               0.000000  ...   
25%         4604.000000            4015.000000               0.000000  ...   
50%         6586.000000            5953.000000             450.000000  ...   
75%        10263.000000            9235.000000            1139.000000  ...   
max        40686.000000           75644.000000            4694.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count             1000000.000000                 1000000.000000   
mean                   81.299678                    6167.321013   
std                    98.332246                   15323.303023   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   155.000000                    2055.000000   
max                   385.000000                   99337.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                 1000000.000000           1000000.000000   
mean                       57.063938              3189.284980   
std                       197.615468              5387.374421   
min                         0.000000                15.000000   
25%                         0.000000               185.600000   
50%                         0.000000               637.000000   
75%                         0.000000              3283.400000   
max                      1108.000000             25662.800000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count    1000000.000000                1000000.000000         1000000.000000   
mean       89990.292793                   2103.785106           59493.299547   
std       153848.715942                   3909.123268          111615.351934   
min          186.000000                      0.000000               0.000000   
25%         5034.000000                     81.100000            2010.000000   
50%        17417.000000                    337.900000            9711.000000   
75%        91753.000000                   1824.000000           51681.000000   
max       740619.000000                  19083.500

In [18]:
std = fudge.describe().loc["std"]
std = std[0:26]

In [19]:
rtstd = std.map(lambda x : math.sqrt(x)/2) #use half of square root of standard deviation as the range for gaussian normal
rtstd = rtstd.to_dict()

In [20]:
for key in rtstd:
    #fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, rtstd[key])))
    fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, 2)))
fudge = fudge[fudge>=0]
fudge.dropna(inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [21]:
rtstd

{'t_cost_per_claim_excluded': 28.080921607414407,
 't_claim_count_schedule2': 3.7754760045184454,
 't_claim_per_bene': 1.6520980880376244,
 '%b2bg_claim_count': 1.8041650819109079,
 '%b2bg_drug_cost': 2.948310128773032,
 '%b2t_claim_count': 1.7966112356911172,
 '%b2t_drug_cost': 2.9431633272301396,
 't_cost_per_claim': 40.60206351461477,
 't_cost_per_claim_ge65': 47.56327477151798,
 't_claim_per_bene_ge65': 16.217970378194327,
 'mapd_cost_per_claim': 40.07577172238087,
 'pdp_cost_per_claim': 44.53175902030115,
 'lis_cost_per_claim': 42.99758163661715,
 'nonlis_cost_per_claim': 49.80454620670591,
 'opioid_cost_per_claim': 31.144689357802495,
 'opioid_claim_per_bene': 8.665294687709283,
 'antibiotic_cost_per_claim': 21.233372187307246,
 'antibiotic_claim_per_bene': 4.958130852656166,
 'antipsych_cost_per_claim_ge65': 61.8936649090098,
 'antipsych_claim_per_bene_ge65': 7.028788441009106,
 'total_30_day_fill_count': 36.699367912895596,
 'total_day_supply': 196.1177681536746,
 'total_30_day

In [22]:
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              134638.000000            134638.000000     134638.000000   
mean                 3463.842323               131.675959         23.284449   
std                  2114.786880                67.219336         12.755857   
min                    53.942510                 0.004268          0.003176   
25%                  1952.918878                80.295011         13.303191   
50%                  3115.273823               149.170147         22.600232   
75%                  5153.503251               195.310005         30.982580   
max                 28059.417718               257.780607         57.266242   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      134638.000000    134638.000000     134638.000000   134638.000000   
mean           21.176915        70.133033         21.170228       69.758934   
std             7.072809        12.297597          7.079881       12.167472   
min             0.000731         0.002590          0.000852        0.003451   
25%            18.207196        66.669965         18.206314       66.241897   
50%            20.445298        71.971733         20.437443       71.560194   
75%            24.582926        77.681604         24.552477       77.179333   
max            56.380071        92.360030         57.078519       91.244302   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     134638.000000          134638.000000          134638.000000  ...   
mean        7570.728840            7166.108549            2209.467554  ...   
std         3342.176287            3184.083500            1221.736610  ...   
min          783.546151               0.594944               0.003053  ...   
25%         5733.866753            4887.937250            1234.689745  ...   
50%         6662.190936            6461.022440            2159.297052  ...   
75%         8630.795631            8123.388182            2858.809643  ...   
max        40688.056912           60054.710884            4701.613533  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              134638.000000                  134638.000000   
mean                  193.124431                   15208.539276   
std                    68.782825                   20372.252422   
min                     0.000013                       0.000076   
25%                   152.003970                     906.601278   
50%                   186.493831                    9675.465640   
75%                   255.675624                   24699.899163   
max                   389.849598                   99342.410635   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  134638.000000            134638.000000   
mean                      232.512284             11475.721679   
std                       318.062399              7417.604507   
min                         0.000085                30.471641   
25%                         1.071197              5060.926453   
50%                         2.640747             10239.629130   
75%                       436.038556             17076.353181   
max                      1113.118942             25669.323434   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count     134638.000000                 134638.000000          134638.000000   
mean      323855.784418                   7961.136286          224936.528253   
std       212848.024544                   5805.538565          165969.350526   
min          489.787827                      2.144002               0.980266   
25%       147420.938956                   2685.013107           78436.395079   
50%       297339.334885                   6885.216427          197850.861454   
75%       496661.042103                  11736.095514          337534.618924   
max       740625.441060                  19090.328

In [23]:
only_excluded.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count                 150.000000               150.000000        150.000000   
mean                 2189.672400                40.060000         10.465333   
std                  3153.093795                57.224652         10.951718   
min                    56.190000                 1.000000          0.000000   
25%                   280.907500                 3.000000          2.900000   
50%                  1216.845000                14.000000          6.600000   
75%                  3017.287500                48.500000         13.900000   
max                 28054.360000               250.000000         49.800000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count         150.000000       150.000000        150.000000      150.000000   
mean           14.000000        43.913333         13.933333       43.766667   
std            13.056408        34.894267         12.947839       34.772205   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        62.000000         10.000000       62.000000   
75%            20.000000        74.000000         20.000000       74.000000   
max            60.000000        97.000000         60.000000       97.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count        150.000000             150.000000             150.000000  ...   
mean        8350.813333            7686.386667             821.460000  ...   
std         6621.442726            9094.882945            1055.219311  ...   
min          576.000000               0.000000               0.000000  ...   
25%         4610.500000            4056.750000               0.000000  ...   
50%         6527.000000            5944.000000             448.000000  ...   
75%        10169.250000            9232.250000            1118.750000  ...   
max        40686.000000           75644.000000            4694.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count                 150.000000                     150.000000   
mean                   81.386667                    6142.180000   
std                    98.766743                   15356.575889   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   154.500000                    1991.250000   
max                   385.000000                   99337.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                     150.000000               150.000000   
mean                       56.813333              3188.420000   
std                       197.780483              5406.105092   
min                         0.000000                15.000000   
25%                         0.000000               186.700000   
50%                         0.000000               630.550000   
75%                         0.000000              3240.725000   
max                      1108.000000             25662.800000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count        150.000000                    150.000000             150.000000   
mean       89958.806667                   2104.858000           59517.600000   
std       154369.582621                   3923.767831          112018.125211   
min          186.000000                      0.000000               0.000000   
25%         5035.000000                     81.400000            2019.000000   
50%        17361.500000                    341.200000            8829.000000   
75%        90712.750000                   1822.275000           50595.750000   
max       740619.000000                  19083.500

In [24]:
fudge.shape

(134638, 27)

In [25]:
fudge=fudge.sample(n=10000)
fudge.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
410161                3294.101479               161.550302         26.953120   
711034                5409.706216               249.736893         44.912803   
289404                 851.423031                36.130484         14.223778   
737163                3127.912704               173.430311         30.936028   
716576                3487.092078               200.522455         45.617827   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
410161          16.559879        70.680603         18.616718       72.150652   
711034          22.845705        66.596091         21.193217       67.357658   
289404           9.061573        55.161900         10.328659       49.753927   
737163          16.594672        69.492098         17.155585       66.195356   
716576          19.440043        60.533189         19.442129       61.447588   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
410161       6209.467435            5870.467770            2543.070092  ...   
711034       6026.286347            5649.490513            4244.702113  ...   
289404       3088.433340            2864.613338            1514.552084  ...   
737163       4854.905460            4960.439098            2542.578951  ...   
716576       5327.115426            4887.976661            4518.327251  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
410161                 206.305970                    2994.698754   
711034                 209.930618                   21558.064266   
289404                 280.954291                       0.248748   
737163                 186.121950                   10749.754446   
716576                 305.125344                    9460.634971   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
410161                       2.554328             17078.347062   
711034                       1.369877             25661.832722   
289404                       0.358317              1660.898307   
737163                       0.401240             15884.708978   
716576                     840.004109             16751.632171   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
410161     496659.559235                  14397.145964          420766.960188   
711034     740620.123364                  17127.587299          496420.216445   
289404      44995.537959                    470.768015           12861.747843   
737163     458991.160417                   6887.820059          199821.517329   
716576     424392.309318                  15034.019151          383414.807980   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
410161       27254.709613               11.544156            1  
711034       23087.433227                4.447098            1  
289404        5680.563506               11.683475            1  
737163       38903.309958               10.986193            1  
716576        6567.857849                1.571651            1  

[5 rows x 27 columns]

In [26]:
ag_2015 = pd.concat([new_main_2015, fudge])
ag_2015.dropna(inplace=True)

In [27]:
ag_2015[ag_2015["is_excluded"]==1].shape

(10000, 27)

In [28]:
ag_2015.shape

(692866, 27)

#Applying PCA, 2 components and 3 components for variance visualization

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_), color='r')

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_cross_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

plt.vlines(1, color='grey', ymax=0.1, ymin=0, linestyle=':')
plt.vlines(2, color='grey', ymax=0.1, ymin=0, linestyle=':')

plt.annotate('1 components', xy=(0.6, 0.05), xytext=(0.9, 0.05), fontsize=15, rotation=90)
plt.annotate('2 components', xy=(1.6, 0.05), xytext=(1.9, 0.05), fontsize=15, rotation=90)

plt.savefig('VarExp.jpeg', dpi=1000)
plt.tight_layout()
plt.show()

In [29]:
#Training without Upsampling or Downsampling
#fudged data (ag_2015) only for train, regular data (new_df) only for test

X_train = ag_2015.drop(['is_excluded'], axis=1)
y_train = ag_2015['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X = new_main_2015.drop(['is_excluded'], axis=1)
#y = new_main_2015['is_excluded']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [30]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [31]:
print(pca.explained_variance_ratio_)

[7.52720731e-01 1.79536920e-01 2.97302340e-02 1.07781679e-02
 7.69058505e-03 6.53720267e-03 5.17372105e-03 3.52432635e-03
 1.34694627e-03 1.30840517e-03 1.00394419e-03 3.46558160e-04
 2.83685442e-04 1.25181314e-05 5.13866729e-06 3.73494552e-07
 2.84689125e-07 1.21533940e-07 6.78219097e-08 5.48538577e-08
 6.97370975e-09 3.28377571e-09 2.95173801e-09 2.57846423e-10
 1.83654940e-10]


In [32]:
Labels = ag_2015.drop(["is_excluded"],axis = 1).columns

In [33]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 'lis_cost_per_claim',
 'mapd_cost_per_claim',
 'mapd_cost_per_claim',
 'lis_cost_per_claim',
 'total_day_supply_ge65',
 't_cost_per_claim',
 't_cost_per_claim_ge65',
 'antibiotic_cost_per_claim',
 'antipsych_cost_per_claim_ge65',
 'opioid_day_supply',
 'opioid_cost_per_claim',
 't_cost_per_claim_excluded',
 'total_30_day_fill_count',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 'total_30_day_fill_count_ge65',
 '%b2bg_drug_cost',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2bg_drug_cost']

In [34]:
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [35]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

150


In [36]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [37]:
clf.feature_importances_

array([0.07017156, 0.03788294, 0.03734324, 0.0336074 , 0.03082007,
       0.07288469, 0.04791129, 0.03531189, 0.05065275, 0.03904364,
       0.04743999, 0.04310944, 0.03868391, 0.03827668, 0.06859035,
       0.03093044, 0.04503225, 0.03939113, 0.01952151, 0.02393726,
       0.00940129, 0.0236442 , 0.02862551, 0.00767438, 0.0801122 ])

coef_df = pd.DataFrame(clf.feature_importances_, Labels, columns = ["Importances"])
coef_df.sort_values("Importances", ascending = False)

check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [38]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(y_pred_prob)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
1.0


array([[682866,      0],
       [     1,   9999]], dtype=int64)

In [39]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(y_pred_prob)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.6265393657624276


array([[170567,      0],
       [   150,      0]], dtype=int64)

In [40]:
#Upsampling only

ag_2015_majority = ag_2015[ag_2015['is_excluded'] == 0]
ag_2015_minority = ag_2015[ag_2015['is_excluded'] > 0]

# Increase by 10 times
ag_2015_minority_upsampled = resample(ag_2015_minority, replace=True, n_samples=100000, random_state=42) 
ag_2015_upsampled = pd.concat([ag_2015_majority, ag_2015_minority_upsampled])  
ag_2015_upsampled['is_excluded'].value_counts()

0    682866
1    100000
Name: is_excluded, dtype: int64

In [41]:
#fudged data (ag_2015) only for train, regular data (new_df) only for test
X_train = ag_2015_upsampled.drop(['is_excluded'], axis=1)
y_train = ag_2015_upsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [42]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [43]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [44]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[682866,      0],
       [     0, 100000]], dtype=int64)

In [45]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5586883551136308


array([[170567,      0],
       [   150,      0]], dtype=int64)

In [46]:
#Training on downsampled only and testing on regular

ag_2015_majority = ag_2015[ag_2015['is_excluded'] == 0]
ag_2015_minority = ag_2015[ag_2015['is_excluded'] > 0]

# Reduce by 10 times
ag_2015_majority_downsampled = resample(ag_2015_majority, replace=True, n_samples=81980, random_state=42) 
ag_2015_downsampled = pd.concat([ag_2015_majority_downsampled, ag_2015_minority]) 
ag_2015_downsampled['is_excluded'].value_counts()

0    81980
1    10000
Name: is_excluded, dtype: int64

In [47]:
#fudged data (ag_2015) only for train, regular data (new_df) only for test
X_train = ag_2015_downsampled.drop(['is_excluded'], axis=1)
y_train = ag_2015_downsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [48]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [49]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [50]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[81980,     0],
       [    1,  9999]], dtype=int64)

In [51]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5569806781694778


array([[170567,      0],
       [   150,      0]], dtype=int64)

In [52]:
#Upsampling/downsampling on training and testing on regular

ag_2015_majority = ag_2015[ag_2015['is_excluded'] == 0]
ag_2015_minority = ag_2015[ag_2015['is_excluded'] > 0]

ag_2015_updownsampled = pd.concat([ag_2015_majority_downsampled, ag_2015_minority_upsampled]) 
ag_2015_updownsampled['is_excluded'].value_counts()

1    100000
0     81980
Name: is_excluded, dtype: int64

In [53]:
#fudged data (ag_2015) only for train, regular data (new_df) only for test

X_train = ag_2015_updownsampled.drop(['is_excluded'], axis=1)
y_train = ag_2015_updownsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [54]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [55]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [56]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[ 81980,      0],
       [     0, 100000]], dtype=int64)

In [57]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5232763469291636


array([[170565,      2],
       [   150,      0]], dtype=int64)

In conclusion, results from downsampling is the best.

In [58]:
#Classification Model Comparisons

def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn

from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import cross_validate, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, auc, recall_score, precision_score, accuracy_score, f1_score

seed = 42

#Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

scoring = {'AUC': 'roc_auc', 'Accuracy': 'accuracy', 'F1': 'f1'}

names = ["Naive Bayes", "Nearest Neighbors", "RBF SVM", 
         "AdaBoost", "GradientBoost", "ExtraTrees", "Random Forest"]

classifiers = [
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            SVC(kernel="rbf", C=1, probability=True),
            AdaBoostClassifier(n_estimators=25, random_state=seed),
            GradientBoostingClassifier(n_estimators=1000, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),]

trace_dict = {'x_vals':[], 'y_vals':[], 'y_error':[], 'colors':[], 'names':[]}
                                                                                         
#iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    cv_results = cross_validate(clf, X, y, scoring=scoring, cv=5, return_train_score=True)
    print('########################### \nFor {}'.format(name))
    for score in scoring:
        print('{0:s}: Mean-{1:.4f}  STD-{2:.4f}'.format(score, cv_results['test_'+score].mean(),\
                                                        cv_results['test_'+score].std()))
    
    trace_dict['x_vals'].append(counter)
    counter += 1
    trace_dict['y_vals'].append(cv_results['test_F1'].mean())
    trace_dict['y_error'].append()
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)
    trace_dict['y_error'].append(np.std(cv_results['test_F1']))

In [59]:
# Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

names = ["GradientBoost", "ExtraTrees", "Random Forest", "Naive Bayes", "Nearest Neighbors", "AdaBoost"]

classifiers = [
            GradientBoostingClassifier(n_estimators=50, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),      
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            AdaBoostClassifier(n_estimators=25, random_state=seed)]

In [60]:
trace_dict = {'x_vals':[], 'y_vals':[], 'colors':[], 'names':[]}
                                                                                         
# iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    X_train = ag_2015.drop(['is_excluded'], axis=1)
    y_train = ag_2015['is_excluded']
    X_test = new_df.drop(['is_excluded'], axis =1)
    y_test = new_df["is_excluded"]
    clf.fit(X_train, y_train)
    y_pred_prob = clf.predict_proba(X_test)
    cv_results = roc_auc_score(y_test, y_pred_prob[:,1])
    print('########################### \nFor {}'.format(name))
              
    trace_dict['x_vals'].append(counter)
    counter += 1
    print(cv_results)
    trace_dict['y_vals'].append(cv_results.mean())
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)

########################### 
For GradientBoost
0.5835133798839556
########################### 
For ExtraTrees
0.758441003632981
########################### 
For Random Forest
0.6460748757575225
########################### 
For Naive Bayes
0.62173124539526
########################### 
For Nearest Neighbors
0.8231742169743658
########################### 
For AdaBoost
0.4180364314316369



In [61]:
# Plotting ROC curves of the models
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
import plotly

n_classes = 1
fpr = dict()
tpr = dict()
roc_auc = dict()
plt.figure()
lw = 2
trace_dict = {}

for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    y_score = clf.fit(X_train, y_train).predict_proba(X_test)
    fpr[name], tpr[name], _ = roc_curve(y_test[:], y_score[:, 1])
    roc_auc[name] = auc(fpr[name], tpr[name])
    trace_dict.update({'trace' + name: go.Scatter(x=fpr[name], y=tpr[name], mode='lines', 
                                       line=dict(color=color, width=lw),
                                       showlegend=True,
                                       name='{0:s} AUC: {1:.2f}'.format(name, roc_auc[name]))})
trace_guess = go.Scatter(x=[0, 1], y=[0, 1], 
                mode='lines', 
                line=dict(color='navy', width=lw, dash='dash'),
                showlegend=False)
data = [trace_dict[trace] for trace in trace_dict] + [trace_guess]
layout = go.Layout(title='Receiver Operating Characteristics',
                   xaxis=dict(title='False Positive Rate'),
                   yaxis=dict(title='True Positive Rate'),
                   margin=go.Margin(l=50, r=50, b=30, t=65, pad=4),
                   legend=dict(x=0.7, y=0.4, font=dict(size=18))
                  )
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='ROCs')

<Figure size 432x288 with 0 Axes>