In [7]:
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook, tqdm

In [8]:
new_main_2017 = pd.read_csv('data/ml_2017.csv', low_memory=False)
print("The data has a size of {}".format(new_main_2017.shape))

The data has a size of (904999, 32)


In [9]:
new_main_2017.head(1)

Unnamed: 0         npi specialty_description nppes_provider_state  \
0           0  1023417649     Internal Medicine                   PA   

   t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     512.29                       14               2.7   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  ...  \
0                0.0              0.0               0.0  ...   

   antipsych_cost_per_claim_ge65  antipsych_claim_per_bene_ge65  \
0                            0.0                            0.0   

   total_30_day_fill_count  total_day_supply  total_30_day_fill_count_ge65  \
0                    605.0             13547                         533.9   

   total_day_supply_ge65  opioid_day_supply  opioid_prescriber_rate  \
0                12009.0                0.0                     0.0   

   is_excluded       year  
0            0  2017-2018  

[1 rows x 32 columns]

In [10]:
new_main_2017.drop(['Unnamed: 0'], axis=1, inplace = True)

In [11]:
new_main_2017.drop(['npi', 'specialty_description','nppes_provider_state','year'], axis=1, inplace = True)

In [12]:
new_main_2017.head(1)

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
0                     512.29                       14               2.7   

   %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
0                0.0              0.0               0.0             0.0   

   t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
0            6966.0                 5285.0                  269.0  ...   

   antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
0                      116.0                            0.0   

   antipsych_claim_per_bene_ge65  total_30_day_fill_count  total_day_supply  \
0                            0.0                    605.0             13547   

   total_30_day_fill_count_ge65  total_day_supply_ge65  opioid_day_supply  \
0                         533.9                12009.0                0.0   

   opioid_prescriber_rate  is_excluded  
0                     0.0            0  

[1 rows x 27 columns]

In [13]:
len(new_main_2017[new_main_2017['is_excluded'] == 1])

101

In [14]:
dropIndex = new_main_2017[new_main_2017['is_excluded'] == 1].index

In [15]:
len(new_main_2017[new_main_2017['is_excluded'] == 0])

904898

In [16]:
only_excluded = new_main_2017[new_main_2017['is_excluded'] == 1]
new_main_2017.drop(dropIndex, inplace = True)
new_main_2017 = new_main_2017.sample(frac=1)
random_sample = new_main_2017.iloc[0:180899]
new_df = pd.concat([only_excluded, random_sample])
new_main_2017 = new_main_2017.drop(new_main_2017.iloc[0:180899].index, axis = 0)
new_df = new_df.sample(frac=1)
#part_d_df.iloc[0:85000].index

In [17]:
#new_df.drop(['Unnamed: 0'], axis=1, inplace = True)
new_df.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
466824                    1758.30                        3               2.9   
206998                     131.97                        4               2.1   
807636                    5300.41                       25               5.0   
813353                     275.65                        8              10.3   
36021                      160.92                        4               1.8   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
466824               40.0             81.0              40.0            81.0   
206998                0.0              0.0               0.0             0.0   
807636                0.0              0.0               0.0             0.0   
813353               10.0             67.0              10.0            67.0   
36021                 0.0              0.0               0.0             0.0   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
466824            5733.0                 5973.0                  325.0  ...   
206998             502.0                    0.0                    0.0  ...   
807636            8652.0                 8950.0                  479.0  ...   
813353            6288.0                  642.0                    0.0  ...   
36021             1939.0                 1890.0                  174.0  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
466824                        0.0                            0.0   
206998                      142.0                            0.0   
807636                      170.0                            0.0   
813353                        0.0                            0.0   
36021                       102.0                            0.0   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
466824                            0.0                    252.7   
206998                            0.0                    117.0   
807636                            0.0                   5101.8   
813353                            0.0                    293.0   
36021                             0.0                    223.5   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
466824              6352                         213.3                 5359.0   
206998               894                           0.0                    0.0   
807636            147824                        4566.3               132626.0   
813353              8689                          12.0                  340.0   
36021               2917                         166.5                 2256.0   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
466824                0.0                    0.00            0  
206998              106.0                   25.64            0  
807636              178.0                    1.65            0  
813353                0.0                    0.00            0  
36021                 0.0                    0.00            0  

[5 rows x 27 columns]

In [18]:
new_main_2017.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count               7.239990e+05            723999.000000     723999.000000   
mean                2.210160e+03                25.530147          6.386812   
std                 5.771132e+03                40.555249          7.114008   
min                 0.000000e+00                 0.000000          0.000000   
25%                 1.669950e+02                 2.000000          1.900000   
50%                 6.752100e+02                 7.000000          3.600000   
75%                 2.368745e+03                29.000000          8.300000   
max                 1.713038e+06               393.000000        277.800000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      723999.000000    723999.000000     723999.000000   723999.000000   
mean           12.577421        38.910510         12.358263       38.853846   
std            16.533628        37.127757         15.901208       36.904739   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        42.000000         10.000000       43.000000   
75%            20.000000        73.000000         20.000000       73.000000   
max           100.000000       100.000000        100.000000      100.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count      7.239990e+05           7.239990e+05          723999.000000  ...   
mean       1.252597e+04           1.029608e+04             478.547249  ...   
std        5.388923e+04           3.694538e+04             685.111804  ...   
min        0.000000e+00           0.000000e+00               0.000000  ...   
25%        2.348000e+03           1.396000e+03               0.000000  ...   
50%        5.504000e+03           4.653000e+03             222.000000  ...   
75%        9.327000e+03           7.985000e+03             651.000000  ...   
max        1.712797e+07           7.622389e+06           23799.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count               723999.00000                  723999.000000   
mean                    92.37953                    1379.623603   
std                     82.63806                    6947.354752   
min                      0.00000                       0.000000   
25%                      0.00000                       0.000000   
50%                    113.00000                       0.000000   
75%                    143.00000                       0.000000   
max                   3422.00000                  479253.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  723999.000000            723999.000000   
mean                       28.164180              2506.340293   
std                       143.730003              5127.581359   
min                         0.000000                11.000000   
25%                         0.000000               141.000000   
50%                         0.000000               444.800000   
75%                         0.000000              2263.600000   
max                      6007.000000            447960.500000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count      7.239990e+05                 723999.000000           7.239990e+05   
mean       6.968663e+04                   2031.273047           5.679396e+04   
std        1.438054e+05                   4450.714717           1.252032e+05   
min        1.100000e+01                      0.000000           0.000000e+00   
25%        2.160000e+03                     72.000000           9.690000e+02   
50%        1.026800e+04                    298.000000           6.686000e+03   
75%        6.274450e+04                   1609.600000           4.435900e+04   
max        5.634058e+06                 379751.000

In [19]:
import math

In [20]:
from sklearn import decomposition
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, auc
from sklearn.utils import resample
from sklearn.preprocessing import label_binarize
from sklearn.svm import SVC
from scipy.stats import pointbiserialr

In [21]:
#part_d_excluded = new_df[new_df["is_excluded"]==1]

fudge = resample(only_excluded, replace=True, n_samples=1000000, random_state = 0)
#fudge.drop(['Unnamed: 0'], axis=1, inplace = True)
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count             1000000.000000           1000000.000000    1000000.000000   
mean                 5194.967630                38.609067          9.485671   
std                 28249.745002                55.813583          9.620971   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count     1000000.000000   1000000.000000    1000000.000000  1000000.000000   
mean           11.374050        36.234950         10.876360       36.026284   
std            14.980311        36.168503         12.989995       35.937057   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count    1000000.000000         1000000.000000         1000000.000000  ...   
mean       10551.133795            8908.213605             751.031469  ...   
std        17528.724650           16454.262782             932.513383  ...   
min          294.000000               0.000000               0.000000  ...   
25%         4406.000000            2876.000000               0.000000  ...   
50%         7223.000000            5345.000000             378.000000  ...   
75%        10419.000000            7982.000000            1163.000000  ...   
max       141957.000000          125896.000000            4355.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count             1000000.000000                 1000000.000000   
mean                   77.438471                    2743.050558   
std                    88.433065                    8561.702769   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   157.000000                     633.000000   
max                   322.000000                   50758.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                 1000000.000000           1000000.000000   
mean                       43.789287              3131.733322   
std                       158.750327              5513.810033   
min                         0.000000                13.000000   
25%                         0.000000               109.000000   
50%                         0.000000               632.600000   
75%                         0.000000              3164.200000   
max                       803.000000             33073.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count    1000000.000000                1000000.000000         1000000.000000   
mean       88423.346199                   2090.284659           59364.759391   
std       156739.468845                   4178.857341          118866.398677   
min          221.000000                      0.000000               0.000000   
25%         2955.000000                     62.000000            1280.000000   
50%        18369.000000                    368.400000           10843.000000   
75%        90194.000000                   1882.600000           52000.000000   
max       934916.000000                  22770.800

In [22]:
std = fudge.describe().loc["std"]
std = std[0:26]

In [23]:
rtstd = std.map(lambda x : math.sqrt(x)/2) #use half of square root of standard deviation as the range for gaussian normal
rtstd = rtstd.to_dict()

In [24]:
for key in rtstd:
    #fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, rtstd[key])))
    fudge[key] = fudge[key].map(lambda x: (np.random.normal(x, 2)))
fudge = fudge[fudge>=0]
fudge.dropna(inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [25]:
rtstd

{'t_cost_per_claim_excluded': 84.03830228283725,
 't_claim_count_schedule2': 3.735424432090368,
 't_claim_per_bene': 1.5508844893809823,
 '%b2bg_claim_count': 1.9352203219559672,
 '%b2bg_drug_cost': 3.007012758064355,
 '%b2t_claim_count': 1.802081760350314,
 '%b2t_drug_cost': 2.99737621069871,
 't_cost_per_claim': 66.19804500548426,
 't_cost_per_claim_ge65': 64.13708518052151,
 't_claim_per_bene_ge65': 15.268541048298102,
 'mapd_cost_per_claim': 64.61408506431768,
 'pdp_cost_per_claim': 67.25735816485223,
 'lis_cost_per_claim': 68.22596052313033,
 'nonlis_cost_per_claim': 62.07153722436618,
 'opioid_cost_per_claim': 46.504668620058595,
 'opioid_claim_per_bene': 8.847407251096762,
 'antibiotic_cost_per_claim': 29.817508674809556,
 'antibiotic_claim_per_bene': 4.701942818546453,
 'antipsych_cost_per_claim_ge65': 46.26473486591827,
 'antipsych_claim_per_bene_ge65': 6.299808071086247,
 'total_30_day_fill_count': 37.12751686106159,
 'total_day_supply': 197.95167898077315,
 'total_30_day_fil

In [26]:
fudge.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count              114614.000000            114614.000000     114614.000000   
mean                 3601.756292               121.438488         21.006105   
std                  3114.345851                76.193715         10.531309   
min                    37.632197                 0.003885          0.001018   
25%                  1819.133133                62.053449         13.966485   
50%                  2714.243261               117.330161         19.596501   
75%                  4191.867014               152.031767         24.757748   
max                286886.189412               306.932710         54.107895   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count      114614.000000    114614.000000     114614.000000   114614.000000   
mean           17.641714        66.618130         17.641537       66.121510   
std             6.764048        12.605969          6.755279       12.610141   
min             0.011429         0.000376          0.000343        0.002834   
25%            11.455097        63.778013         11.456827       63.410387   
50%            18.969051        68.921362         18.964485       68.646112   
75%            21.215187        73.454749         21.229835       72.860628   
max            99.239140       102.621679         65.639046      104.877802   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count     114614.000000          114614.000000          114614.000000  ...   
mean        8187.002639            7525.365594            2015.481828  ...   
std         5356.621404            4706.676377            1061.209775  ...   
min          368.025454               0.446584               0.001516  ...   
25%         5312.967547            4753.820395            1418.412868  ...   
50%         5956.452606            5687.735726            1767.750619  ...   
75%        10246.425001            9553.873661            2606.625443  ...   
max       141955.443466          125897.123272            4363.477866  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count              114614.000000                  114614.000000   
mean                  168.130768                    8494.845846   
std                    51.912143                   14308.509967   
min                     0.001925                       0.000071   
25%                   157.428689                     753.490376   
50%                   172.255070                    3287.627890   
75%                   209.808076                    4982.146397   
max                   327.454752                   50759.246017   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                  114614.000000            114614.000000   
mean                      248.057950             10401.437974   
std                       307.743561              8900.908078   
min                         0.000031                35.851855   
25%                         1.154627              3166.114293   
50%                         3.054553              9283.784267   
75%                       622.975133             13861.634775   
max                       810.903993             33081.115944   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count     114614.000000                 114614.000000          114614.000000   
mean      293218.615680                   7235.892038          204673.498393   
std       252150.999507                   6938.251379          196640.850738   
min          234.376730                      0.376790               1.688859   
25%        89842.496629                   2204.598794           63402.327773   
50%       268680.439431                   5176.675221          147270.228961   
75%       390052.222558                   9288.970658          270397.599927   
max       934924.792562                  22778.391

In [27]:
only_excluded.describe()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
count                 101.000000               101.000000        101.000000   
mean                 5221.393465                38.673267          9.499010   
std                 28518.834547                56.116684          9.667021   
min                    40.990000                 1.000000          0.000000   
25%                   293.230000                 3.000000          2.200000   
50%                  1206.820000                11.000000          5.800000   
75%                  3338.240000                54.000000         13.800000   
max                286886.380000               299.000000         46.100000   

       %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
count         101.000000       101.000000        101.000000      101.000000   
mean           11.386139        36.306931         10.891089       36.099010   
std            15.035272        36.333935         13.045996       36.102771   
min             0.000000         0.000000          0.000000        0.000000   
25%             0.000000         0.000000          0.000000        0.000000   
50%            10.000000        43.000000         10.000000       43.000000   
75%            20.000000        71.000000         20.000000       70.000000   
max           100.000000       100.000000         60.000000       98.000000   

       t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
count        101.000000             101.000000             101.000000  ...   
mean       10562.524752            8919.534653             751.980198  ...   
std        17653.641240           16564.118105             937.517232  ...   
min          294.000000               0.000000               0.000000  ...   
25%         4406.000000            2876.000000               0.000000  ...   
50%         7223.000000            5345.000000             378.000000  ...   
75%        10419.000000            7982.000000            1163.000000  ...   
max       141957.000000          125896.000000            4355.000000  ...   

       antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
count                 101.000000                     101.000000   
mean                   77.495050                    2757.247525   
std                    88.851182                    8633.955942   
min                     0.000000                       0.000000   
25%                     0.000000                       0.000000   
50%                     0.000000                       0.000000   
75%                   157.000000                     633.000000   
max                   322.000000                   50758.000000   

       antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
count                     101.000000               101.000000   
mean                       44.079208              3136.292079   
std                       159.991417              5542.441612   
min                         0.000000                13.000000   
25%                         0.000000               109.000000   
50%                         0.000000               632.600000   
75%                         0.000000              3164.200000   
max                       803.000000             33073.000000   

       total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
count        101.000000                    101.000000             101.000000   
mean       88552.960396                   2093.873267           59466.841584   
std       157554.695894                   4202.779267          119551.162208   
min          221.000000                      0.000000               0.000000   
25%         2955.000000                     62.000000            1280.000000   
50%        18369.000000                    368.400000           10843.000000   
75%        90194.000000                   1882.600000           52000.000000   
max       934916.000000                  22770.800

In [28]:
fudge.shape

(114614, 27)

In [29]:
fudge=fudge.sample(n=10000)
fudge.head()

t_cost_per_claim_excluded  t_claim_count_schedule2  t_claim_per_bene  \
90154                 3477.631390                84.902692         13.328618   
82944                 3483.191065               218.961908         18.176163   
658804                4740.016456                41.768320         10.232283   
488570               11008.088513               299.680378         48.462880   
214693                2124.990406                63.161283          9.485080   

        %b2bg_claim_count  %b2bg_drug_cost  %b2t_claim_count  %b2t_drug_cost  \
90154           15.944613        86.629701         17.875684       83.722283   
82944           20.172728        71.494058         19.747527       72.308896   
658804          22.158073        65.428292         15.868095       63.764361   
488570          28.678917        74.954107         32.053680       71.262490   
214693          18.788915        72.524141         20.794812       72.373539   

        t_cost_per_claim  t_cost_per_claim_ge65  t_claim_per_bene_ge65  ...  \
90154        7908.864845            6991.044450            1494.445871  ...   
82944        7777.209747            7640.926994            1766.426444  ...   
658804      17797.589272           15803.287630             885.842130  ...   
488570      12813.667525           12155.828611            4356.817124  ...   
214693       9999.288428           13683.153585            1120.111689  ...   

        antibiotic_claim_per_bene  antipsych_cost_per_claim_ge65  \
90154                  212.869522                     661.781782   
82944                  170.249844                    1759.340597   
658804                 181.441802                   48023.061728   
488570                 222.954019                    3289.043990   
214693                 218.922930                       3.769477   

        antipsych_claim_per_bene_ge65  total_30_day_fill_count  \
90154                        0.551826              5294.189227   
82944                        1.712725             19636.422309   
658804                     314.551495              1723.094085   
488570                     711.326165             33073.007900   
214693                       0.227220              4239.472696   

        total_day_supply  total_30_day_fill_count_ge65  total_day_supply_ge65  \
90154      148547.546748                   2909.424034           82516.440520   
82944      546799.805809                  17458.290627          487706.858700   
658804      49003.210021                    952.146883           27246.987930   
488570     934913.891187                  22772.411816          647622.229933   
214693     110542.866818                   2339.028562           63978.144513   

        opioid_day_supply  opioid_prescriber_rate  is_excluded  
90154         6083.733587                3.784186            1  
82944        13260.433760                4.200442            1  
658804        5332.994006               11.599609            1  
488570       26080.478316                2.976029            1  
214693        3107.435194               11.070894            1  

[5 rows x 27 columns]

In [30]:
ag_2017 = pd.concat([new_main_2017, fudge])
ag_2017.dropna(inplace=True)

In [31]:
ag_2017[ag_2017["is_excluded"]==1].shape

(10000, 27)

In [32]:
ag_2017.shape

(733999, 27)

#Applying PCA, 2 components and 3 components for variance visualization

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_), color='r')

pca = decomposition.PCA(n_components='mle')
pca.fit(part_d_df)
npi_drug_cross_df_transformed = pca.transform(part_d_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

plt.vlines(1, color='grey', ymax=0.1, ymin=0, linestyle=':')
plt.vlines(2, color='grey', ymax=0.1, ymin=0, linestyle=':')

plt.annotate('1 components', xy=(0.6, 0.05), xytext=(0.9, 0.05), fontsize=15, rotation=90)
plt.annotate('2 components', xy=(1.6, 0.05), xytext=(1.9, 0.05), fontsize=15, rotation=90)

plt.savefig('VarExp.jpeg', dpi=1000)
plt.tight_layout()
plt.show()

In [33]:
#Training without Upsampling or Downsampling
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017.drop(['is_excluded'], axis=1)
y_train = ag_2017['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X = new_main_2017.drop(['is_excluded'], axis=1)
#y = new_main_2017['is_excluded']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [34]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [35]:
print(pca.explained_variance_ratio_)

[7.14271723e-01 2.06599354e-01 3.14520396e-02 1.56335707e-02
 1.28546558e-02 5.65953857e-03 5.19924783e-03 3.88319009e-03
 1.80274903e-03 1.04145880e-03 8.54438730e-04 4.67840215e-04
 2.61039301e-04 1.42325895e-05 4.12647885e-06 3.33391779e-07
 2.39324837e-07 1.03665118e-07 6.20453876e-08 4.63821661e-08
 5.24182857e-09 2.80181390e-09 2.51189779e-09 2.17071776e-10
 1.44326355e-10]


In [36]:
Labels = ag_2017.drop(["is_excluded"],axis = 1).columns

In [37]:
#new Labels after PCA
most_important = [np.abs(pca.components_[i]).argmax() for i in range(len(pca.components_))]
most_important_names = [Labels[most_important[i]] for i in range(len(pca.components_))]
dic = {'PC{}'.format(i+1): most_important_names[i] for i in range(len(pca.components_))}
newLabels = list(dic.values())
newLabels

['total_day_supply',
 't_cost_per_claim',
 'mapd_cost_per_claim',
 'lis_cost_per_claim',
 'mapd_cost_per_claim',
 't_cost_per_claim',
 'total_day_supply_ge65',
 't_cost_per_claim_ge65',
 'antibiotic_cost_per_claim',
 'opioid_day_supply',
 'antipsych_cost_per_claim_ge65',
 't_cost_per_claim_excluded',
 'opioid_cost_per_claim',
 'total_30_day_fill_count',
 't_claim_per_bene_ge65',
 'opioid_claim_per_bene',
 'antipsych_claim_per_bene_ge65',
 'antibiotic_claim_per_bene',
 'total_30_day_fill_count_ge65',
 '%b2bg_drug_cost',
 'opioid_prescriber_rate',
 '%b2bg_claim_count',
 't_claim_count_schedule2',
 't_claim_per_bene',
 '%b2t_drug_cost']

In [38]:
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [39]:
#excluded samples in test data
count = 0
for x in y_test:
    if int(x)== 1:
        count +=1
print(count)

101


In [40]:
#excluded samples in train data
count2 = 0
for x in y_train:
    if int(x)== 1:
        count2 +=1
print(count2)

10000


In [41]:
clf.feature_importances_

array([0.05493719, 0.03064783, 0.02749169, 0.02979386, 0.01840385,
       0.04753002, 0.10608716, 0.01758074, 0.01406856, 0.03743263,
       0.05004504, 0.02590497, 0.05077932, 0.0340774 , 0.04465477,
       0.03510807, 0.04770221, 0.02759643, 0.01803008, 0.01997155,
       0.01350865, 0.02141994, 0.0330878 , 0.00688876, 0.18725148])

coef_df = pd.DataFrame(clf.feature_importances_, Labels, columns = ["Importances"])
coef_df.sort_values("Importances", ascending = False)

check for contamination by not dropping the npis and seeing if any of them overlap between training and testing
train_nps = set(X_train['npi'])
test_nps = set(X_test['npi'])
print(len(train_nps.intersection(test_nps))) # should be zero

In [42]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(y_pred_prob)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

[[1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]
 ...
 [0.   1.  ]
 [0.   1.  ]
 [0.08 0.92]]
1.0


array([[723999,      0],
       [     2,   9998]], dtype=int64)

In [43]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(y_pred_prob)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.6694413309456253


array([[180899,      0],
       [   101,      0]], dtype=int64)

In [44]:
#Upsampling only

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Increase by 10 times
ag_2017_minority_upsampled = resample(ag_2017_minority, replace=True, n_samples=100000, random_state=42) 
ag_2017_upsampled = pd.concat([ag_2017_majority, ag_2017_minority_upsampled])  
ag_2017_upsampled['is_excluded'].value_counts()

0    723999
1    100000
Name: is_excluded, dtype: int64

In [45]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_upsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_upsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [46]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [47]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [48]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[723999,      0],
       [     0, 100000]], dtype=int64)

In [49]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5389046477934545


array([[180899,      0],
       [   101,      0]], dtype=int64)

In [50]:
#Training on downsampled only and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

# Reduce by 10 times
ag_2017_majority_downsampled = resample(ag_2017_majority, replace=True, n_samples=81980, random_state=42) 
ag_2017_downsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority]) 
ag_2017_downsampled['is_excluded'].value_counts()

0    81980
1    10000
Name: is_excluded, dtype: int64

In [51]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test
X_train = ag_2017_downsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_downsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [52]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [53]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [54]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[81980,     0],
       [    0, 10000]], dtype=int64)

In [55]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.5570986523358941


array([[180893,      6],
       [   101,      0]], dtype=int64)

In [56]:
#Upsampling/downsampling on training and testing on regular

ag_2017_majority = ag_2017[ag_2017['is_excluded'] == 0]
ag_2017_minority = ag_2017[ag_2017['is_excluded'] > 0]

ag_2017_updownsampled = pd.concat([ag_2017_majority_downsampled, ag_2017_minority_upsampled]) 
ag_2017_updownsampled['is_excluded'].value_counts()

1    100000
0     81980
Name: is_excluded, dtype: int64

In [57]:
#fudged data (ag_2017) only for train, regular data (new_df) only for test

X_train = ag_2017_updownsampled.drop(['is_excluded'], axis=1)
y_train = ag_2017_updownsampled['is_excluded']
X_test = new_df.drop(['is_excluded'], axis =1)
y_test = new_df["is_excluded"]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [58]:
pca = decomposition.PCA(n_components='mle')
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [59]:
clf = RandomForestClassifier(n_estimators=25, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [60]:
y_pred = clf.predict(X_train)
y_pred_prob = clf.predict_proba(X_train)
print(roc_auc_score(y_train, y_pred_prob[:,1]))
confusion_matrix(y_train, y_pred)

1.0


array([[ 81980,      0],
       [     0, 100000]], dtype=int64)

In [61]:
y_pred = clf.predict(X_test)
y_pred_prob = clf.predict_proba(X_test)
print(roc_auc_score(y_test, y_pred_prob[:,1]))
confusion_matrix(y_test, y_pred)

0.4559811806807136


array([[180899,      0],
       [   101,      0]], dtype=int64)

In conclusion, results from downsampling is the best.

In [62]:
#Classification Model Comparisons

def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn

from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import cross_validate, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, auc, recall_score, precision_score, accuracy_score, f1_score

seed = 42

#Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#4292c6", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

scoring = {'AUC': 'roc_auc', 'Accuracy': 'accuracy', 'F1': 'f1'}

names = ["Naive Bayes", "Nearest Neighbors", "RBF SVM", 
         "AdaBoost", "GradientBoost", "ExtraTrees", "Random Forest"]

classifiers = [
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            SVC(kernel="rbf", C=1, probability=True),
            AdaBoostClassifier(n_estimators=25, random_state=seed),
            GradientBoostingClassifier(n_estimators=1000, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),]

trace_dict = {'x_vals':[], 'y_vals':[], 'y_error':[], 'colors':[], 'names':[]}
                                                                                         
#iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    cv_results = cross_validate(clf, X, y, scoring=scoring, cv=5, return_train_score=True)
    print('########################### \nFor {}'.format(name))
    for score in scoring:
        print('{0:s}: Mean-{1:.4f}  STD-{2:.4f}'.format(score, cv_results['test_'+score].mean(),\
                                                        cv_results['test_'+score].std()))
    
    trace_dict['x_vals'].append(counter)
    counter += 1
    trace_dict['y_vals'].append(cv_results['test_F1'].mean())
    trace_dict['y_error'].append()
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)
    trace_dict['y_error'].append(np.std(cv_results['test_F1']))

In [63]:
# Identifying the best model algorithm
colors = ["#08306b", "#08519c", "#1361a9", "#6baed6", 'rgb(76,000,153)', 'rgb(153,000,153)']

names = ["GradientBoost", "ExtraTrees", "Random Forest", "Naive Bayes", "Nearest Neighbors", "AdaBoost"]

classifiers = [
            GradientBoostingClassifier(n_estimators=50, random_state=seed),
            ExtraTreesClassifier(n_estimators=25, random_state=seed),
            RandomForestClassifier(n_estimators=25, random_state=seed),      
            GaussianNB(),
            KNeighborsClassifier(n_neighbors=5),
            AdaBoostClassifier(n_estimators=25, random_state=seed)]

In [64]:
trace_dict = {'x_vals':[], 'y_vals':[], 'colors':[], 'names':[]}
                                                                                         
# iterate over classifiers
counter = 0
for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    X_train = ag_2017.drop(['is_excluded'], axis=1)
    y_train = ag_2017['is_excluded']
    X_test = new_df.drop(['is_excluded'], axis =1)
    y_test = new_df["is_excluded"]
    clf.fit(X_train, y_train)
    y_pred_prob = clf.predict_proba(X_test)
    cv_results = roc_auc_score(y_test, y_pred_prob[:,1])
    print('########################### \nFor {}'.format(name))
              
    trace_dict['x_vals'].append(counter)
    counter += 1
    print(cv_results)
    trace_dict['y_vals'].append(cv_results.mean())
    trace_dict['colors'].append(color)
    trace_dict['names'].append(name)

########################### 
For GradientBoost
0.5735060355050702
########################### 
For ExtraTrees
0.7365808687403327
########################### 
For Random Forest
0.6777052005224292
########################### 
For Naive Bayes
0.5651941384719956
########################### 
For Nearest Neighbors
0.8265773981750881
########################### 
For AdaBoost
0.4384846278479666



In [65]:
# Plotting ROC curves of the models
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
import plotly

n_classes = 1
fpr = dict()
tpr = dict()
roc_auc = dict()
plt.figure()
lw = 2
trace_dict = {}

for color, name, clf in tqdm_notebook(zip(colors, names, classifiers), total=len(names)):
    y_score = clf.fit(X_train, y_train).predict_proba(X_test)
    fpr[name], tpr[name], _ = roc_curve(y_test[:], y_score[:, 1])
    roc_auc[name] = auc(fpr[name], tpr[name])
    trace_dict.update({'trace' + name: go.Scatter(x=fpr[name], y=tpr[name], mode='lines', 
                                       line=dict(color=color, width=lw),
                                       showlegend=True,
                                       name='{0:s} AUC: {1:.2f}'.format(name, roc_auc[name]))})
trace_guess = go.Scatter(x=[0, 1], y=[0, 1], 
                mode='lines', 
                line=dict(color='navy', width=lw, dash='dash'),
                showlegend=False)
data = [trace_dict[trace] for trace in trace_dict] + [trace_guess]
layout = go.Layout(title='Receiver Operating Characteristics',
                   xaxis=dict(title='False Positive Rate'),
                   yaxis=dict(title='True Positive Rate'),
                   margin=go.Margin(l=50, r=50, b=30, t=65, pad=4),
                   legend=dict(x=0.7, y=0.4, font=dict(size=18))
                  )
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='ROCs')

<Figure size 432x288 with 0 Axes>